### ISSUE TITLE
Code which worked fine yesterday - now hates me

### ISSUE THREAD

**Issue by Pemhughes** [DynamoDS/Dynamo#6077] opened 2016-02-04 09:19 UTC
I've written a code using dynamo to check revit rooms and rename a parameter within that room to the area each room sits in.

![rename all room comments to apartment area name](https://cloud.githubusercontent.com/assets/17062362/12810798/583d09ca-cb20-11e5-8166-aee0d01a4766.png)

Worked perfectly yesterday evening, today the code is not my friend.

Using version 0.9.0.3067

Packages attached.
![packages](https://cloud.githubusercontent.com/assets/17062362/12810797/583928c8-cb20-11e5-9631-e3c45817770b.JPG)

"Index was outside the bounds of the array.

   at ProtoCore.DSASM.Executive.GetProcedureNode(Int32 blockId, Int32 classIndex, Int32 functionIndex)
   at ProtoCore.DSASM.Executive.UpdateMethodDependencyGraph(Int32 entry, Int32 procIndex, Int32 classIndex)
   at ProtoCore.DSASM.Executive.SetupEntryPoint()
   at ProtoCore.DSASM.Executive.SetupExecutive(Int32 exeblock, Int32 entry)
   at ProtoCore.DSASM.Executive.Execute(Int32 exeblock, Int32 entry, Language language)
   at ProtoCore.DSASM.Executive.BounceUsingExecutive(Executive executive, Int32 exeblock, Int32 entry, StackFrame stackFrame, Int32 locals, Boolean fepRun, Executive exec, List`1 breakpoints)
   at ProtoScript.Runners.ProtoScriptRunner.ExecuteLive(Core core, RuntimeCore runtimeCore)
   at ProtoScript.Runners.LiveRunner.Execute(Boolean isCodeCompiled)
   at ProtoScript.Runners.LiveRunner.CompileAndExecute(List`1 astList)
   at ProtoScript.Runners.LiveRunner.CompileAndExecuteForDeltaExecution(List`1 astList)
   at ProtoScript.Runners.LiveRunner.UpdateGraph(GraphSyncData syncData)
   at Dynamo.Core.Threading.AsyncTask.Execute()"

**Comment by ke-yu** [comment] 2016-04-22 03:18
hi @Pemhughes , notice you are using 0.9.0, please let me know if the problem is still there or not.

**Comment by johnpierson** [comment] 2018-12-14 14:12
Closing as this issue is for an outdated version of Dynamo. If this persists in 2.0.x for you, please feel free to reopen and update accordingly.

**Closed by johnpierson** 2018-12-14 14:12 UTC
Labels: 0.x
