### ISSUE TITLE
Empty list breaks PolyCurve.ByJoinedCurves and Surface.ByPatch

### ISSUE THREAD

**Issue by inleiva** [DynamoDS/Dynamo#9616] opened 2019-04-02 07:19 UTC
If this issue is with Dynamo for Revit, please post your issue on the [Dynamo for Revit Issues page](https://github.com/DynamoDS/DynamoRevit/issues).

If this issue is **not** a bug report or improvement request, please check the [Dynamo forum](https://forum.dynamobim.com/), and start a thread there to discuss your issue.

## Dynamo version

Dynamo Revit 2.0.2.6833

## Operating system

Windows 7 professional

## What did you do? 

Created a code that organized the geometries by type. In case that there is no geometry of the sort, it generates an empty list. When this happens, PolyCurve.By.JoinedCurves and Surface.ByPatch crash dynamo generating the error shown below

## What did you expect to see?

Continue working with empty lists

## What did you see instead?

I attached the picture, but I recieved an Unhandled Exception in Dynamo Engine. 

![Error](https://user-images.githubusercontent.com/49183938/55383371-4ff4b200-5528-11e9-99bd-23657bec1e0f.png)

Error shown:
"
Index was outside the bounds of the array.

   at ProtoCore.Lang.ArrayUtilsForBuiltIns.Transpose(StackValue sv, Interpreter runtime)
   at ProtoCore.Lang.BuiltInFunctionEndPoint.Execute(Context c, List`1 formalParameters, StackFrame stackFrame, RuntimeCore runtimeCore)
   at ProtoCore.CallSite.ExecWithZeroRI(List`1 functionEndPoint, Context c, List`1 formalParameters, StackFrame stackFrame, RuntimeCore runtimeCore, SingleRunTraceData previousTraceData, SingleRunTraceData newTraceData)
   at ProtoCore.CallSite.Execute(List`1 functionEndPoint, Context c, List`1 formalParameters, List`1 replicationInstructions, StackFrame stackFrame, RuntimeCore runtimeCore)
   at ProtoCore.CallSite.DispatchNew(Context context, List`1 arguments, List`1 partialReplicationGuides, DominantListStructure domintListStructure, StackFrame stackFrame, RuntimeCore runtimeCore)
   at ProtoCore.DSASM.Executive.Callr(Int32 blockDeclId, Int32 functionIndex, Int32 classIndex, Boolean& explicitCall, Boolean isDynamicCall, Boolean hasDebugInfo)
   at ProtoCore.DSASM.Executive.CALLR_Handler(Instruction instruction)
   at ProtoCore.DSASM.Executive.Execute(Int32 exeblock, Int32 entry, Language language)
   at ProtoCore.DSASM.Executive.Execute(Int32 exeblock, Int32 entry, List`1 breakpoints, Language language)
   at ProtoCore.DSASM.Executive.BounceUsingExecutive(Executive executive, Int32 exeblock, Int32 entry, StackFrame stackFrame, Int32 locals, Boolean fepRun, Executive exec, List`1 breakpoints)
   at ProtoScript.Runners.ProtoScriptRunner.ExecuteLive(Core core, RuntimeCore runtimeCore)
   at ProtoScript.Runners.LiveRunner.Execute(Boolean isCodeCompiled)
   at ProtoScript.Runners.LiveRunner.CompileAndExecute(List`1 astList)
   at ProtoScript.Runners.LiveRunner.CompileAndExecuteForDeltaExecution(List`1 astList)
   at ProtoScript.Runners.LiveRunner.SynchronizeInternal(GraphSyncData syncData)
   at ProtoScript.Runners.LiveRunner.UpdateGraph(GraphSyncData syncData)
   at Dynamo.Scheduler.UpdateGraphAsyncTask.HandleTaskExecutionCore()
   at Dynamo.Scheduler.AsyncTask.Execute()
"

**Comment by mjkkirschner** [comment] 2019-04-02 15:16
@saintentropy is this related to your PR that you mentioned?

**Comment by mjkkirschner** [comment] 2019-11-18 19:13
tracked crash with: https://jira.autodesk.com/browse/DYN-2288

**Comment by QilongTang** [comment] 2019-11-27 19:19
@inleiva Do you mind sharing this graph because the team believe something downstream crashed Dynamo instead of the geometry nodes

**Comment by mjkkirschner** [comment] 2020-06-15 17:28
closing this as we cannot reproduce it and no more info has been given - please reopen with more info if it reproduces.

**Closed by mjkkirschner** 2020-06-15 17:28 UTC
Labels: crash, error/warning/crash, needs more info, tracked
