### ISSUE TITLE
Improvement: Scalable controller handles and symbol for vectors

### ISSUE THREAD

**Issue by ThomasMahon** [DynamoDS/Dynamo#6547] opened 2016-04-29 12:30 UTC
## Dynamo version

0.9.2
## Operating system

Win 10
## Improvement Suggestion

Would be great to have control of the symbol size of the handles that points and other manipulatable geometry have in the geometry window. When working in Revit, the differences in unit size make these symbols, including symbols for planes and coordinates systems effectively invisible as they are so small. 

Would also be good for vectors to have a symbol - I find my self creating lines using the vector just to visualise them!

**Comment by dimven** [comment] 2016-04-30 03:36
This is sort of a dupe of the below issue, so I'll close my version:
https://github.com/DynamoDS/Dynamo/issues/4155

**Comment by smangarole** [comment] 2017-08-14 15:14
@ThomasMahon Are these issues still valid with 1.3 Dynamo? Can you please clarify whether they apply to only Dynamo?

**Comment by Racel** [comment] 2017-10-16 20:12
We had planned on working on this a while back, but since we are no longer going to investing resources in the current geometry viewer, I think we have to close this for now. We will try and get back to this issue in the next generation of Dynamo.

**Closed by Racel** 2017-10-16 20:12 UTC
Labels: Revit, UI
