### ISSUE TITLE
Issue when using groups in custom nodes.

### ISSUE THREAD

**Issue by misterBIM** [DynamoDS/Dynamo#4852] opened 2015-07-05 09:11 UTC
I am experiencing an issue when closing any custom node where grouping nodes has been used.
It is ok as I can save my work, but Dynamo 0.8.1 just stop running.
Please check this out. This is the error I get:

La cadena de entrada no tiene el formato correcto.

   en System.Number.ParseDouble(String value, NumberStyles options, NumberFormatInfo numfmt)
   en System.Double.Parse(String s, NumberStyles style, IFormatProvider provider)
   en Dynamo.Controls.GroupFontSizeToEditorEnabledConverter.Convert(Object[] values, Type targetType, Object parameter, CultureInfo culture)
   en System.Windows.Data.MultiBindingExpression.TransferValue()
   en System.Windows.Data.MultiBindingExpression.HandlePropertyInvalidation(DependencyObject d, DependencyPropertyChangedEventArgs args)
   en System.Windows.Data.BindingExpressionBase.OnPropertyInvalidation(DependencyObject d, DependencyPropertyChangedEventArgs args)
   en System.Windows.DependentList.InvalidateDependents(DependencyObject source, DependencyPropertyChangedEventArgs sourceArgs)
   en System.Windows.DependencyObject.NotifyPropertyChange(DependencyPropertyChangedEventArgs args)
   en System.Windows.DependencyObject.UpdateEffectiveValue(EntryIndex entryIndex, DependencyProperty dp, PropertyMetadata metadata, EffectiveValueEntry oldEntry, EffectiveValueEntry& newEntry, Boolean coerceWithDeferredReference, Boolean coerceWithCurrentValue, OperationType operationType)
   en System.Windows.TreeWalkHelper.OnInheritablePropertyChanged(DependencyObject d, InheritablePropertyChangeInfo info, Boolean visitedViaVisualTree)
   en System.Windows.DescendentsWalker`1._VisitNode(DependencyObject d, Boolean visitedViaVisualTree)
   en System.Windows.DescendentsWalker`1.WalkFrameworkElementLogicalThenVisualChildren(FrameworkElement feParent, Boolean hasLogicalChildren)
   en System.Windows.DescendentsWalker`1.IterateChildren(DependencyObject d)
   en System.Windows.DescendentsWalker`1.StartWalk(DependencyObject startNode, Boolean skipStartNode)
   en System.Windows.TreeWalkHelper.InvalidateOnInheritablePropertyChange(FrameworkElement fe, FrameworkContentElement fce, InheritablePropertyChangeInfo info, Boolean skipStartNode)
   en System.Windows.FrameworkElement.OnPropertyChanged(DependencyPropertyChangedEventArgs e)
   en System.Windows.DependencyObject.NotifyPropertyChange(DependencyPropertyChangedEventArgs args)
   en System.Windows.DependencyObject.UpdateEffectiveValue(EntryIndex entryIndex, DependencyProperty dp, PropertyMetadata metadata, EffectiveValueEntry oldEntry, EffectiveValueEntry& newEntry, Boolean coerceWithDeferredReference, Boolean coerceWithCurrentValue, OperationType operationType)
   en System.Windows.DependencyObject.SetValueCommon(DependencyProperty dp, Object value, PropertyMetadata metadata, Boolean coerceWithDeferredReference, Boolean coerceWithCurrentValue, OperationType operationType, Boolean isInternal)
   en System.Windows.DependencyObject.SetValue(DependencyProperty dp, Object value)
   en System.Windows.Controls.ContentPresenter.OnContentChanged(DependencyObject d, DependencyPropertyChangedEventArgs e)
   en System.Windows.DependencyObject.OnPropertyChanged(DependencyPropertyChangedEventArgs e)
   en System.Windows.FrameworkElement.OnPropertyChanged(DependencyPropertyChangedEventArgs e)
   en System.Windows.DependencyObject.NotifyPropertyChange(DependencyPropertyChangedEventArgs args)
   en System.Windows.DependencyObject.UpdateEffectiveValue(EntryIndex entryIndex, DependencyProperty dp, PropertyMetadata metadata, EffectiveValueEntry oldEntry, EffectiveValueEntry& newEntry, Boolean coerceWithDeferredReference, Boolean coerceWithCurrentValue, OperationType operationType)
   en System.Windows.DependencyObject.InvalidateProperty(DependencyProperty dp, Boolean preserveCurrentValue)
   en System.Windows.StyleHelper.InvalidateDependents(Style ownerStyle, FrameworkTemplate frameworkTemplate, DependencyObject container, DependencyProperty dp, FrugalStructList`1& dependents, Boolean invalidateOnlyContainer)
   en System.Windows.StyleHelper.OnTriggerSourcePropertyInvalidated(Style ownerStyle, FrameworkTemplate frameworkTemplate, DependencyObject container, DependencyProperty dp, DependencyPropertyChangedEventArgs changedArgs, Boolean invalidateOnlyContainer, FrugalStructList`1& triggerSourceRecordFromChildIndex, FrugalMap& propertyTriggersWithActions, Int32 sourceChildIndex)
   en System.Windows.FrameworkElement.OnPropertyChanged(DependencyPropertyChangedEventArgs e)
   en System.Windows.DependencyObject.NotifyPropertyChange(DependencyPropertyChangedEventArgs args)
   en System.Windows.DependencyObject.UpdateEffectiveValue(EntryIndex entryIndex, DependencyProperty dp, PropertyMetadata metadata, EffectiveValueEntry oldEntry, EffectiveValueEntry& newEntry, Boolean coerceWithDeferredReference, Boolean coerceWithCurrentValue, OperationType operationType)
   en System.Windows.DependencyObject.SetValueCommon(DependencyProperty dp, Object value, PropertyMetadata metadata, Boolean coerceWithDeferredReference, Boolean coerceWithCurrentValue, OperationType operationType, Boolean isInternal)
   en System.Windows.DependencyObject.SetValue(DependencyPropertyKey key, Object value)
   en System.Windows.Controls.TabControl.UpdateSelectedContent()
   en System.Windows.Controls.TabControl.OnSelectionChanged(SelectionChangedEventArgs e)
   en System.Windows.Controls.Primitives.Selector.SelectionChanger.End()
   en System.Windows.Controls.Primitives.Selector.RemoveFromSelection(NotifyCollectionChangedEventArgs e)
   en System.Windows.Controls.Primitives.Selector.OnItemsChanged(NotifyCollectionChangedEventArgs e)
   en System.Windows.Controls.TabControl.OnItemsChanged(NotifyCollectionChangedEventArgs e)
   en System.Collections.Specialized.NotifyCollectionChangedEventHandler.Invoke(Object sender, NotifyCollectionChangedEventArgs e)
   en System.Windows.Data.CollectionView.OnCollectionChanged(NotifyCollectionChangedEventArgs args)
   en System.Windows.WeakEventManager.ListenerList`1.DeliverEvent(Object sender, EventArgs e, Type managerType)
   en System.Windows.WeakEventManager.DeliverEventToList(Object sender, EventArgs args, ListenerList list)
   en System.Windows.WeakEventManager.DeliverEvent(Object sender, EventArgs args)
   en System.Windows.Data.CollectionView.OnCollectionChanged(NotifyCollectionChangedEventArgs args)
   en System.Windows.Data.ListCollectionView.ProcessCollectionChangedWithAdjustedIndex(NotifyCollectionChangedEventArgs args, Int32 adjustedOldIndex, Int32 adjustedNewIndex)
   en System.Collections.ObjectModel.ObservableCollection`1.OnCollectionChanged(NotifyCollectionChangedEventArgs e)
   en System.Collections.ObjectModel.Collection`1.Remove(T item)
   en System.Action`1.Invoke(T obj)
   en Dynamo.Models.DynamoModel.OnWorkspaceRemoved(WorkspaceModel obj)
   en System.Windows.Controls.Button.OnClick()
   en System.Windows.Controls.Primitives.ButtonBase.OnMouseLeftButtonUp(MouseButtonEventArgs e)
   en System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   en System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   en System.Windows.UIElement.ReRaiseEventAs(DependencyObject sender, RoutedEventArgs args, RoutedEvent newEvent)
   en System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   en System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   en System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   en System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   en System.Windows.Input.InputManager.ProcessStagingArea()
   en System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   en System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
   en System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   en System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   en MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   en MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   en System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   en MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(Object source, Delegate method, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by lillismith** [comment] 2015-07-06 14:17
I cannot reproduce this in a simple case. Could you please send your file and a few more details?  Are you using Dynamo for Revit? 2015 or 16?

**Comment by misterBIM** [comment] 2015-07-06 14:42
I am using Revit 2015.

I’ve found out that the issue comes ONLY when trying to close a custom node when grouping other nodes (Dynamo just exits although I can save work if I need it).

It does not happen when using groups in a Dynamo file.

Hope this helps. Thanks in advance.

 


José María Abellán Alemán


Director de Proyecto


 


jm.abellan@BiMMate.com


+34 653 242 785


 


 <http://www.bimmate.com/> 

 <https://www.facebook.com/pages/BiMMate/498570280247764?ref=bookmarks> 

 <https://www.linkedin.com/company/bimmate?trk=biz-companies-cym> 

 <https://twitter.com/BiMMate> 

 <https://plus.google.com/b/109297205399097098764/+Bimmate-Spain/posts> 


  _____  

 

 

 

De: Lilli Smith [mailto:notifications@github.com] 
Enviado el: lunes, 6 de julio de 2015 16:18
Para: DynamoDS/Dynamo
CC: José María
Asunto: Re: [Dynamo] Issue when using groups in custom nodes. (#4852)

 

I cannot reproduce this in a simple case. Could you please send your file and a few more details? Are you using Dynamo for Revit? 2015 or 16?

**Comment by lillismith** [comment] 2015-07-06 14:52
Still can't reproduce. I'm not sure I totally understand your statement "the issue comes ONLY when trying to close a custom node when grouping other nodes".  You are exiting a custom node when you've grouped some nodes inside of the custom node?  This doesn't crash for me in a simple case.  Maybe you could send your files?

**Comment by misterBIM** [comment] 2015-07-08 17:39
My apologies if I cannot make explain myself properly.

I’m trying to use the new feature (included in release 0.8.1) to group nodes inside a custom node, so I can assign a colour and a description to that group, which makes a lot more understandable the program.

The issue comes when I try to close the custom node after using groups to make things clear, but I have no issues when I use the group feature inside a dynamo file (not a custom node) and I close it.

I hope this helps. Thank you for your patient.

 

 


José María Abellán Alemán


Director de Proyecto


 


jm.abellan@BiMMate.com


+34 653 242 785


 


 <http://www.bimmate.com/> 

 <https://www.facebook.com/pages/BiMMate/498570280247764?ref=bookmarks> 

 <https://www.linkedin.com/company/bimmate?trk=biz-companies-cym> 

 <https://twitter.com/BiMMate> 

 <https://plus.google.com/b/109297205399097098764/+Bimmate-Spain/posts> 


  _____  

 

 

 

De: Lilli Smith [mailto:notifications@github.com] 
Enviado el: lunes, 6 de julio de 2015 16:53
Para: DynamoDS/Dynamo
CC: José María
Asunto: Re: [Dynamo] Issue when using groups in custom nodes. (#4852)

 

Still can't reproduce. I'm not sure I totally understand your statement "the issue comes ONLY when trying to close a custom node when grouping other nodes". You are exiting a custom node when you've grouped some nodes inside of the custom node? This doesn't crash for me in a simple case. Maybe you could send your files?

**Comment by jnealb** [comment] 2015-07-08 18:43
@misterBIM @lillismith  I am unable to reproduce this: groups can be created within custom nodes at will, and the custom nodes can be saved at will with 8.1 and re-opened. We may need more specific details, it may have to do with your dyn, dyf etc, thanks.

**Comment by smangarole** [comment] 2017-06-19 17:00
Closing this issue based on the discussion above. @lillismith @jnealb @misterBIM

**Closed** 2017-06-19 17:01 UTC
Labels: Blocker, Bug, UI, Waiting for feedback
