### ISSUE TITLE
Dynamo crashes when opening another dynamo file listed in recent files.

### ISSUE THREAD

**Issue by ellipsebd** [DynamoDS/Dynamo#5118] opened 2015-08-14 15:24 UTC
![crashes while opening another file](https://cloud.githubusercontent.com/assets/13789181/9276932/c5d259d0-42c8-11e5-9d79-439fb7794ca1.jpg)
saved a file which i was working on within revit conceptual mass family  and tried to open another dynamo file (related with other revit conceptual mass) within the same revit-dynamo workspace and it crashed. Is it because
2 different conceptual family cross-affecting each while automatic run was set?

**Comment by jnealb** [comment] 2015-08-14 15:56
@ellipsebd Can you reproduce the crash and if so can you please expand the Details so we can see the stack dump?

**Comment by ellipsebd** [comment] 2015-08-15 00:09
Thanks Neal,
I will try to reproduce but not sure...but if i can i will send you the
details and if somehow don't forget to do this.
Thanks again.

**Comment by jnealb** [comment] 2015-08-17 15:40
@ellipsebd Any update on this?

**Comment by tothom** [comment] 2015-09-01 14:14
Hi. I have the same issue. Dynamo crashes when I open a file after closing another. The second file I open always crashes. I can open a file from 'Recent Files', but only only first time after I launch Dynamo. After closing a Dynamo file, Dynamo crashes when I open another.

Here are the details from the crash:

Object reference not set to an instance of an object.

   at Dynamo.Views.WorkspaceView.OnMouseMove(Object sender, MouseEventArgs e)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
   at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(Object source, Delegate method, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by tothom** [comment] 2015-09-02 07:52
I tried the latest pre-release "DynamoInstall0.8.3.20150901T1250.exe" and the problem is gone.

**Comment by tothom** [comment] 2015-09-02 08:56
Hi, sorry for spamming the forum, but the problem is back. It started from the moment I copied some nodes with ctrl + c, closed a graph and then tried to open a new graph. I crashed upon opening the second graph. After that it crashes consistently on opening a second graph (after closing a first one) or closing a edit custom node tab.

**Comment by jnealb** [comment] 2015-09-10 20:11
@tothom We have a working theory of what is going on and are tracking it with MAGN-8387.

**Comment by ikeough** [comment] 2016-05-03 04:49
Internal issue has been closed as can't reproduce. Please re-open if you are still experiencing this with newer versions of Dynamo.

**Closed by ikeough** 2016-05-03 04:49 UTC

**Comment by ellipsebd** [comment] 2016-07-19 06:34
@Neal Am now using Dynamo 1.0.0, it is working fine in 2d mode but when i
went to enable background 3d preview..it crashes...here is the detail (
probably my built in GC could not support the 3d as i told before)-

HRESULT: [0x8876086C], Module: [SharpDX.Direct3D9], ApiCode:
[D3DERR_INVALIDCALL/InvalidCall], Message: Unknown

   at SharpDX.Result.CheckError()
   at SharpDX.Direct3D9.Direct3DEx.CreateDeviceEx(Int32 adapter, DeviceType
deviceType, IntPtr hFocusWindow, Int32 behaviorFlags, PresentParameters[]
presentationParametersRef, DisplayModeEx[] fullscreenDisplayModeRef,
DeviceEx returnedDeviceInterfaceOut)
   at HelixToolkit.Wpf.SharpDX.DX11ImageSource.StartD3D()
   at HelixToolkit.Wpf.SharpDX.DX11ImageSource..ctor()
   at HelixToolkit.Wpf.SharpDX.DPFCanvas.StartD3D()
   at
HelixToolkit.Wpf.SharpDX.DPFCanvas.RenderTechniquesManagerPropertyChanged()
   at
System.Windows.DependencyObject.OnPropertyChanged(DependencyPropertyChangedEventArgs
e)
   at
System.Windows.FrameworkElement.OnPropertyChanged(DependencyPropertyChangedEventArgs
e)
   at
System.Windows.DependencyObject.NotifyPropertyChange(DependencyPropertyChangedEventArgs
args)
   at System.Windows.DependencyObject.UpdateEffectiveValue(EntryIndex
entryIndex, DependencyProperty dp, PropertyMetadata metadata,
EffectiveValueEntry oldEntry, EffectiveValueEntry& newEntry, Boolean
coerceWithDeferredReference, Boolean coerceWithCurrentValue, OperationType
operationType)
   at System.Windows.DependencyObject.SetValueCommon(DependencyProperty dp,
Object value, PropertyMetadata metadata, Boolean
coerceWithDeferredReference, Boolean coerceWithCurrentValue, OperationType
operationType, Boolean isInternal)
   at System.Windows.DependencyObject.SetValue(DependencyProperty dp,
Object value)
   at HelixToolkit.Wpf.SharpDX.Viewport3DX.OnApplyTemplate()
   at System.Windows.FrameworkElement.ApplyTemplate()
   at System.Windows.FrameworkElement.MeasureCore(Size availableSize)
   at System.Windows.UIElement.Measure(Size availableSize)
   at System.Windows.Controls.Grid.MeasureOverride(Size constraint)
   at System.Windows.FrameworkElement.MeasureCore(Size availableSize)
   at System.Windows.UIElement.Measure(Size availableSize)
   at MS.Internal.Helper.MeasureElementWithSingleChild(UIElement element,
Size constraint)
   at System.Windows.Controls.ContentPresenter.MeasureOverride(Size
constraint)
   at System.Windows.FrameworkElement.MeasureCore(Size availableSize)
   at System.Windows.UIElement.Measure(Size availableSize)
   at System.Windows.Controls.Border.MeasureOverride(Size constraint)
   at System.Windows.FrameworkElement.MeasureCore(Size availableSize)
   at System.Windows.UIElement.Measure(Size availableSize)
   at System.Windows.Controls.Control.MeasureOverride(Size constraint)
   at System.Windows.FrameworkElement.MeasureCore(Size availableSize)
   at System.Windows.UIElement.Measure(Size availableSize)
   at System.Windows.Controls.Grid.MeasureOverride(Size constraint)
   at System.Windows.FrameworkElement.MeasureCore(Size availableSize)
   at System.Windows.UIElement.Measure(Size availableSize)
   at System.Windows.ContextLayoutManager.UpdateLayout()
   at System.Windows.ContextLayoutManager.UpdateLayoutCallback(Object arg)
   at System.Windows.Media.MediaContext.FireInvokeOnRenderCallbacks()
   at System.Windows.Media.MediaContext.RenderMessageHandlerCore(Object
resizedCompositionTarget)
   at System.Windows.Media.MediaContext.RenderMessageHandler(Object
resizedCompositionTarget)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate
callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source,
Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by jnealb** [comment] 2016-07-19 09:59
@ellipsebd Can you please provide more detail: what OS, are you running Studio or Dynamo for Revit, and your dyn file? Thanks.
