### ISSUE TITLE
Request: Internalized custom nodes

### ISSUE THREAD

**Issue by cjm771** [DynamoDS/Dynamo#7017] opened 2016-08-10 03:23 UTC
One feature I would love is internalized custom nodes. Often I like to "modularize" portions of code without externalizing it, to make it easier to manage. Currently you can only define custom nodes, w inputs and outputs and share it, by exporting dyfs either online or locally.  

If there was a way to make custom nodes that were part of the main definition that would be great, thanks.

**Comment by andydandy74** [comment] 2016-08-10 07:16
Collapsable groups might be a nice solution for this...

**Comment by josols** [comment] 2016-08-10 09:02
Somewhat related to this: #6633 ?

**Comment by ikeough** [comment] 2016-08-10 17:30
@cjm771, I'm closing this one as a duplicate of the one that @josols linked above. I totally agree though, and we've discussed this internally. @andydandy74's suggestion is one possible method, although slightly different.

**Closed by ikeough** 2016-08-10 17:30 UTC

**Comment by cjm771** [comment] 2016-08-10 18:52
Ok great yes #6333 is exactly what I meant,  thanks.
