### ISSUE TITLE
Dynamo Crash

### ISSUE THREAD

**Issue by maxhobos** [DynamoDS/Dynamo#6387] opened 2016-04-07 01:22 UTC
## Dynamo version

Dynamo version 0.9.1

## Operating system

Windows 7

## What did you do? 

Tried to run the script, but crashed

## What did you expect to see?

Values extracted from the Revit Document

## What did you see instead?

Index was outside the bounds of the array.

   at ProtoCore.Lang.ArrayUtilsForBuiltIns.Transpose(StackValue sv, Interpreter runtime)
   at ProtoCore.Lang.BuiltInFunctionEndPoint.Execute(Context c, List`1 formalParameters, StackFrame stackFrame, RuntimeCore runtimeCore)
   at ProtoCore.CallSite.ExecWithZeroRI(List`1 functionEndPoint, Context c, List`1 formalParameters, StackFrame stackFrame, RuntimeCore runtimeCore, FunctionGroup funcGroup, SingleRunTraceData previousTraceData, SingleRunTraceData newTraceData)
   at ProtoCore.CallSite.ExecWithRISlowPath(List`1 functionEndPoint, Context c, List`1 formalParameters, List`1 replicationInstructions, StackFrame stackFrame, RuntimeCore runtimeCore, FunctionGroup funcGroup, SingleRunTraceData previousTraceData, SingleRunTraceData newTraceData)
   at ProtoCore.CallSite.ExecWithRISlowPath(List`1 functionEndPoint, Context c, List`1 formalParameters, List`1 replicationInstructions, StackFrame stackFrame, RuntimeCore runtimeCore, FunctionGroup funcGroup, SingleRunTraceData previousTraceData, SingleRunTraceData newTraceData)
   at ProtoCore.CallSite.Execute(List`1 functionEndPoint, Context c, List`1 formalParameters, List`1 replicationInstructions, StackFrame stackFrame, RuntimeCore runtimeCore, FunctionGroup funcGroup)
   at ProtoCore.CallSite.DispatchNew(Context context, List`1 arguments, List`1 partialReplicationGuides, StackFrame stackFrame, RuntimeCore runtimeCore)
   at ProtoCore.CallSite.JILDispatch(List`1 arguments, List`1 replicationGuides, StackFrame stackFrame, RuntimeCore runtimeCore, Context context)
   at ProtoCore.DSASM.Executive.Callr(Int32 blockDeclId, Int32 functionIndex, Int32 classIndex, Boolean& explicitCall, Boolean isDynamicCall, Boolean hasDebugInfo)
   at ProtoCore.DSASM.Executive.CALLR_Handler(Instruction instruction)
   at ProtoCore.DSASM.Executive.Execute(Int32 exeblock, Int32 entry, Language language)
   at ProtoCore.DSASM.Executive.Execute(Int32 exeblock, Int32 entry, List`1 breakpoints, Language language)
   at ProtoCore.DSASM.Executive.BounceUsingExecutive(Executive executive, Int32 exeblock, Int32 entry, StackFrame stackFrame, Int32 locals, Boolean fepRun, Executive exec, List`1 breakpoints)
   at ProtoScript.Runners.ProtoScriptRunner.ExecuteLive(Core core, RuntimeCore runtimeCore)
   at ProtoScript.Runners.LiveRunner.Execute(Boolean isCodeCompiled)
   at ProtoScript.Runners.LiveRunner.CompileAndExecute(List`1 astList)
   at ProtoScript.Runners.LiveRunner.CompileAndExecuteForDeltaExecution(List`1 astList)
   at ProtoScript.Runners.LiveRunner.UpdateGraph(GraphSyncData syncData)
   at Dynamo.Scheduler.UpdateGraphAsyncTask.HandleTaskExecutionCore()
   at Dynamo.Scheduler.AsyncTask.Execute()

**Comment by ke-yu** [comment] 2016-04-07 14:54
@maxhobos , could you share the script or provide more information about this crash?

**Comment by maxhobos** [comment] 2016-04-08 00:40
Thanks for your reply, Yu Ke. I realized its caused by the code shown in the picture below. 

When an empty list is fed into the input 'h', an error occurs, stating that 'List.UniqueItems cannot receive an empty list'. Somehow, the crash occurs because of this. Deleting this code block seems to resolve this crash. 

I'm really new to Dynamo. I copied this code from somewhere on the web, but I don't know how to modify it using conditional statements to allow empty lists to be fed. I only know that it works for lists that are not empty. 

Please advise, and thanks for your help in advance!

Max


![1](https://cloud.githubusercontent.com/assets/18318542/14370992/8867d5b8-fd65-11e5-8e94-39cfff7d1462.PNG)

**Comment by ke-yu** [comment] 2016-04-08 01:06
@maxhobos thanks! I can reproduce the crash, it is a defect. 

However there is an error in code block node:
```
Transpose({i<1>, k<1>})
```
Firstly `Tranpose()` function is outdated, so please use `List.Transpose()`, and `Tranpose()` is expected to accept only 1 parameter. 

@riteshchandawar @monikaprabhu @jnealb  FYI

**Comment by ikeough** [comment] 2016-04-21 16:25
@maxhobos Closing this issue as it is being tracked internally now. @ke-yu will provide an update when the issue is fixed.

**Closed by ikeough** 2016-04-21 16:25 UTC
Labels: Bug
