### ISSUE TITLE
latest daily build won't start

### ISSUE THREAD

**Issue by jbenoit44** [DynamoDS/Dynamo#4256] opened 2015-04-16 07:28 UTC
![image](https://cloud.githubusercontent.com/assets/4572196/7176024/ec7b6af2-e41a-11e4-9013-c5bb26cb997e.png)

this is the message I get when trying to open dynamo 0.8.1.

**Comment by jnealb** [comment] 2015-04-16 17:20
@jbenoit44 We can reproduce a crash in French Windows as well; tracked as MAGN-7125.

**Comment by anagpuyol** [comment] 2015-04-22 20:52
I have a similar problem:

![image](https://cloud.githubusercontent.com/assets/2687679/7285054/d70722f2-e90f-11e4-9eea-3f297d8c78e7.png)

and then:

![image](https://cloud.githubusercontent.com/assets/2687679/7285065/e33f487e-e90f-11e4-901e-a96fb79263f3.png)

Then Dynamo crashes and closes Revit  too.

**Comment by jbenoit44** [comment] 2015-04-27 21:22
![image](https://cloud.githubusercontent.com/assets/4572196/7358192/2d4a1a8e-ed34-11e4-8d46-6a3f627eb6a9.png)
latest daily available

**Comment by jbenoit44** [comment] 2015-04-27 21:22
FYI Sandbox doesn't run either.

**Comment by monikaprabhu** [comment] 2015-04-28 12:34
@anagpuyol , The error registering about sharpdx_direct3d11_effects_x64.dll is discussed seperately in this thread. This has been fixed by development.Please try the latest daily build. its dsicussed in thread-https://github.com/DynamoDS/Dynamo/issues/4211#issuecomment-96989014.
  
@jbenoit44 - which Windows version are you using- I tried this on Win7 and Win8.1 with non english locale and could not reproduce.Is that french OS?  Do you have multiple versions of Dynamo installed?

**Comment by monikaprabhu** [comment] 2015-04-28 14:03
@jbenoit44 , Need some more info to narrow down the issue. Can you also share the value in the env variable PATH. You can also send it on my email monika.prabhu@autodesk.com

**Comment by jbenoit44** [comment] 2015-04-28 20:48
this is French OS, win 7 64b. I have dynamo 0.7.6 and 0.8 official. will share PATH tomorrow.

**Comment by RodRecker** [comment] 2015-04-28 21:17
I would recommend uninstalling 0.7.6 since that was never released as a stable build. It is basically a daily build prior to 0.8.0.

**Comment by jbenoit44** [comment] 2015-04-29 05:54
no change after uninstall. 
![image](https://cloud.githubusercontent.com/assets/4572196/7385363/01362d54-ee45-11e4-8b82-e027a5f8c6a1.png)

**Comment by jbenoit44** [comment] 2015-04-29 05:57
Microsoft Windows [version 6.1.7601]
Copyright (c) 2009 Microsoft Corporation. Tous droits réservés.


C:\Users\julien.benoit>set path
Path=C:\ProgramData\Oracle\Java\javapath;C:\Program Files\Common Files\Microsoft
 Shared\Windows Live;C:\Program Files (x86)\Common Files\Microsoft Shared\Window
s Live;C:\Program Files (x86)\Intel\iCLS Client\;C:\Program Files\Intel\iCLS Cli
ent\;C:\Program Files\Dell\DW WLAN Card;;C:\Program Files (x86)\NVIDIA Corporati
on\PhysX\Common;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windo
ws\System32\WindowsPowerShell\v1.0\;C:\Program Files\WIDCOMM\Bluetooth Software\
;C:\Program Files\WIDCOMM\Bluetooth Software\syswow64;C:\Program Files\Intel\Int
el(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Managemen
t Engine Components\IPT;C:\Program Files (x86)\Intel\Intel(R) Management Engine
Components\DAL;C:\Program Files (x86)\Intel\Intel(R) Management Engine Component
s\IPT;C:\Program Files (x86)\Windows Live\Shared;C:\Program Files\Common Files\A
utodesk Shared\;C:\Program Files (x86)\Common Files\Graitec\;C:\Program Files\Co
mmon Files\Graitec\;C:\Program Files (x86)\Autodesk\Backburner\;C:\Program Files
 (x86)\Riverbed\Steelhead Mobile\;C:\Program Files (x86)\Skype\Phone\;C:\Program
 Files\OpenNI\Bin64;C:\Users\julien.benoit\AppData\Roaming\Dashlane\3.2.2.76978\
bin\Firefox_Extension\{442718d9-475e-452a-b3e1-fb1ee16b8e9f}\components;C:\Users
\julien.benoit\AppData\Roaming\Dashlane\3.2.4.78888\bin\Firefox_Extension\{44271
8d9-475e-452a-b3e1-fb1ee16b8e9f}\components;C:\Users\julien.benoit\AppData\Roami
ng\Dashlane\3.2.5.79983\bin\Firefox_Extension\{442718d9-475e-452a-b3e1-fb1ee16b8
e9f}\components;C:\Users\julien.benoit\AppData\Roaming\Dashlane\3.2.5.83379\bin\
Firefox_Extension\{442718d9-475e-452a-b3e1-fb1ee16b8e9f}\components
PATHEXT=.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC

is that you asked?

**Comment by ke-yu** [comment] 2015-04-29 06:21
@jbenoit44 sorry, it is a bug. Will fix it soon.

**Comment by monikaprabhu** [comment] 2015-04-29 07:21
@jbenoit44 - You can try removing Firefox_Extension{442718d9-475e-452a-b3e1-fb1ee16b8e9f} and try launch Dynamo- Can you please confirm if that fixes the issue.

**Comment by jbenoit44** [comment] 2015-04-29 11:53
New PATH:

Microsoft Windows [version 6.1.7601]
Copyright (c) 2009 Microsoft Corporation. Tous droits réservés.

C:\Users\julien.benoit>set path
Path=C:\ProgramData\Oracle\Java\javapath;C:\Program Files\Common Files\Microsoft
 Shared\Windows Live;C:\Program Files (x86)\Common Files\Microsoft Shared\Window
s Live;C:\Program Files (x86)\Intel\iCLS Client\;C:\Program Files\Intel\iCLS Cli
ent\;C:\Program Files\Dell\DW WLAN Card;;C:\Program Files (x86)\NVIDIA Corporati
on\PhysX\Common;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windo
ws\System32\WindowsPowerShell\v1.0\;C:\Program Files\WIDCOMM\Bluetooth Software\
;C:\Program Files\WIDCOMM\Bluetooth Software\syswow64;C:\Program Files\Intel\Int
el(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Managemen
t Engine Components\IPT;C:\Program Files (x86)\Intel\Intel(R) Management Engine
Components\DAL;C:\Program Files (x86)\Intel\Intel(R) Management Engine Component
s\IPT;C:\Program Files (x86)\Windows Live\Shared;C:\Program Files\Common Files\A
utodesk Shared\;C:\Program Files (x86)\Common Files\Graitec\;C:\Program Files\Co
mmon Files\Graitec\;C:\Program Files (x86)\Autodesk\Backburner\;C:\Program Files
 (x86)\Riverbed\Steelhead Mobile\;C:\Program Files (x86)\Skype\Phone\;C:\Program
 Files\OpenNI\Bin64
PATHEXT=.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC

Console from dynamo:

Welcome to Dynamo!
00:00:01.7082718 elapsed for loading Dynamo main window.
Dynamo is up to date.

starts as usual. unsinstall Dashlane does fix the issue, but is mandatory on my laptop....

thx

**Comment by RodRecker** [comment] 2015-04-29 12:22
It appears to be a defect on our side when encountering a path with a '{' character. Sorry for the hassle and we will work to get this fixed soon.

**Comment by ikeough** [comment] 2015-04-29 13:05
@jbenoit44 A fix has been supplied (see link to PR above), and is now under review.

**Comment by dbaldacchino** [comment] 2015-05-07 14:43
Tried again today with DynamoInstall0.8.1.20150507T0035.exe, no improvement yet. Has this fix been baked into the daily build yet?

**Comment by RodRecker** [comment] 2015-05-07 15:03
Sorry - its not yet in the build. I'll see if I can move it along.

**Comment by monikaprabhu** [comment] 2015-05-14 02:45
@jbenoit44 - The issue related to curly braces in PATH is fixed (MAGN-7268)- please try the latest build(DynamoInstall0.8.1.20150513T0845.exe) with your configuration.

**Comment by jbenoit44** [comment] 2015-05-16 06:23
This is fixed.both revit and sandbox.

**Closed** 2015-05-21 12:59 UTC
Labels: Critical, Graphics
