### ISSUE TITLE
Crash Report 20150702

### ISSUE THREAD

**Issue by vykrum** [DynamoDS/Dynamo#4838] opened 2015-07-02 05:41 UTC
Ver:0.8.2.1814
OS: Win7

Ran a file with a function. 
Worked as expected.
Deleted the second from last line of the function in [this](http://a360.co/1H29hgj) file.
Altered the return statement and ran.
Dynamo crashed.

Index was outside the bounds of the array.

   at HelixToolkit.Wpf.SharpDX.BillboardTextModel3D.CreateBillboardVertexArray()
   at HelixToolkit.Wpf.SharpDX.BillboardTextModel3D.Attach(IRenderHost host)
   at Dynamo.Controls.Watch3DView.Attach()
   at Dynamo.Controls.Watch3DView.AggregateRenderPackages(PackageAggregationParams parameters)
   at Dynamo.Controls.Watch3DView.RenderDrawables(VisualizationEventArgs e)
   at Dynamo.VisualizationManager.ClearVisualizations(Object sender, EventArgs e)
   at System.EventHandler.Invoke(Object sender, EventArgs e)
   at Dynamo.ViewModels.DynamoViewModel.CloseHomeWorkspace(Object parameter)
   at System.Windows.Controls.Button.OnClick()
   at System.Windows.Controls.Primitives.ButtonBase.OnMouseLeftButtonUp(MouseButtonEventArgs e)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.ReRaiseEventAs(DependencyObject sender, RoutedEventArgs args, RoutedEvent newEvent)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
   at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(Object source, Delegate method, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Application.RunInternal(Window window)
   at DynamoSandbox.Program.MakeStandaloneAndRun(String commandFilePath, DynamoViewModel& viewModel)
   at DynamoSandbox.Program.Main(String[] args)

**Comment by ke-yu** [comment] 2016-06-16 03:27
@vykrum I'm not able to reproduce it.

**Comment by vykrum** [comment] 2016-06-16 08:20
@ke-yu Too late for me to recollect or try to reproduce this :-)

**Comment by ke-yu** [comment] 2016-07-13 06:49
Close it as we dont have enough information to do investigation. Please reopen it if you encounter same crash again.

**Closed by ke-yu** 2016-07-13 06:49 UTC
Labels: Blocker, Bug
