### ISSUE TITLE
1.0.0.20160116T0825  codeblock crashes

### ISSUE THREAD

**Issue by epeter-** [DynamoDS/Dynamo#5988] opened 2016-01-21 10:43 UTC
Codeblock:
when trying to add a value in a multilined codeblock after the last semicolon. dynamo crashes.
locale = german
![image](https://cloud.githubusercontent.com/assets/6928491/12478258/30aef216-c034-11e5-9f1d-29bedf9adfae.png)

message:
Der Vorgang ist aufgrund des aktuellen Zustands des Objekts ungültig.

   bei Dynamo.UI.Controls.PreviewControl.BeginFadeOutTransition()
   bei System.Windows.Media.Animation.Clock.FireEvent(EventPrivateKey key)
   bei System.Windows.Media.Animation.Clock.RaiseAccumulatedEvents()
   bei System.Windows.Media.Animation.TimeManager.RaiseEnqueuedEvents()
   bei System.Windows.Media.Animation.TimeManager.Tick()
   bei System.Windows.Media.MediaContext.RenderMessageHandlerCore(Object resizedCompositionTarget)
   bei System.Windows.Media.MediaContext.AnimatedRenderMessageHandler(Object resizedCompositionTarget)
   bei System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   bei System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by aparajit-pratap** [comment] 2016-01-22 05:54
@epeter- I think this should be fixed by @aosyatnik here: https://github.com/DynamoDS/Dynamo/pull/5975. Could you try the latest build? Thanks.

**Comment by riteshchandawar** [comment] 2016-02-10 05:49
@epeter- Not exactly similar but I found a crash while typing in newly created CBN. I am not able to reproduce the crash on existing CBN.

Tracking internally here.. http://adsk-oss.myjetbrains.com/youtrack/issue/MAGN-9490

-Ritesh

**Comment by ikeough** [comment] 2016-05-02 04:11
Internal issue has been closed.

**Closed by ikeough** 2016-05-02 04:11 UTC
Labels: Blocker, Bug, UI
