### ISSUE TITLE
Conflict with pyRevit (Newtonsoft.Json lib)

### ISSUE THREAD

**Issue by melnikovalex** [DynamoDS/Dynamo#9497] opened 2019-02-18 11:17 UTC
## Dynamo version

2.0.2

## Operating system

Windows 8.1 Pro, the same issue on Win10 Home

## What did you do? 

Open a dynamo script or creating a new one in Revit instance, where pyRevit is installed.

## What did you expect to see?

I expect it to open dynamo-script without any error.

## What did you see instead?

With insalled pyRevit when you're opening Dynamo script there are no wires between nodes, some of the nodes are disappearing. There is an error in Dynamo console:
`This graph has a nodeview with id:2d0d810a-6489-46ab-8686-a86bb1755f6d and name:Watch, but does not contain a matching nodeModel`

If you're creating new nodes some of them are also do not work (return null) 

The similar issues is also described here: https://forum.dynamobim.com/t/nodes-dissapear-after-reopening-file/30954
And in pyRevit issues:  https://github.com/eirannejad/pyRevit/issues/525

Thank you for your help with finding solution!

**Comment by mjkkirschner** [comment] 2019-02-21 16:26
Hi @melnikovalex - I would like to get to the bottom of this - can you provide the list of addins you currently have installed on the machine where this problem occurs?

Do you only see problems after pyRevit is started? or just installing it is enough to cause issues?

I understand that JSON.net may not be the issue here - or there is some interesting load order problem occurring, like another addin forcing assemblies to load from somewhere else.

**Comment by johnpierson** [comment] 2019-02-25 17:57
@melnikovalex , if you could get Mike the above information that would help us get this checked out.

**Comment by kaiaurelienzhu** [comment] 2019-02-25 22:15
@mjkkirschner 

Hi Mike,

I have the same issue on my machine. I can confirm that I have the following add in's installed:

- Revit Lookup
- PyRevit

It seems to be an issue only with pyRevit. I uninstalled pyRevit off my machine (Revit Lookup still there) and Dynamo was working as expected (no nodes missing). 

Please let me know if you need any more information from me.

**Comment by mjkkirschner** [comment] 2019-02-25 22:24
what versions of these addins are you using, version of dynamo, etc would be a good starting point. Thanks.

**Comment by kaiaurelienzhu** [comment] 2019-02-25 22:42
@mjkkirschner 
Sorry about that, I'll be more specific

pyRevit : v 4.6.15

Dynamo Core: v 2.0.2.6826
Dynamo Revit: v 2.0.2.6833

Revit LookUp: v 2017

**Comment by mjkkirschner** [comment] 2019-02-25 22:42
@kaiaurelienzhu thanks, and what version of revit (just to be sure)?

**Comment by kaiaurelienzhu** [comment] 2019-02-25 22:48
@mjkkirschner
 
Revit 2017 & 2018. Both versions of Revit w/ Dynamo are missing nodes when pyRevit is installed.

Off memory, even earlier versions of Dynamo on my personal machine were also missing nodes. I can confirm that for you once I am home and provide exact versions of relevant plug ins.

**Comment by mjkkirschner** [comment] 2019-02-25 23:21
Hi @melnikovalex and @kaiaurelienzhu - one thing I note is that some of pyRevit is built targeting .net 4.7.1 - Revit 2017 and 2018 were not yet updated to host .net 4.7 runtime. AFAIK... but I'm not an expert there.

have either of you seen this issue on 2019?

**Comment by kaiaurelienzhu** [comment] 2019-02-25 23:50
@mjkkirschner 

Have not yet tested this on Revit 2019. I will give it a go once I am home. According to the machine at work, I have .NET Framework 4.7.2 as the minimum on my computer according to this guide:

https://docs.microsoft.com/en-us/dotnet/framework/migration-guide/how-to-determine-which-versions-are-installed

**Comment by melnikovalex** [comment] 2019-02-26 22:40
Sorry for a delay with the answer guys. I've tried to reproduce the issue on clean VM (Windows 10 Enterprise) - here are the results.
Default installation of Revit 2019 (with eTransmit, Model Review, Batch Print, Collaboration and Dynamo 1.3 (?) included) + Dynamo 2.0.2 + pyRevit 4.6.16 cause no errors.
The same conditions with Revit 2018 (20170223_1515) produce the issue with disappeared wires and nodes returning `null`

**Comment by melnikovalex** [comment] 2019-02-27 08:33
Update 3:
@mjkkirschner Installing pyRevit is enough to reproduce it.

Sometimes, without any regularity such window could appear (screenshot from Ehsan Iran-Nejad):
https://user-images.githubusercontent.com/8197916/53456469-6a94b200-39e3-11e9-936f-ec00e34c05c7.png
I had it on several PCs, but it didn't appear on VM for some reason.

**Comment by mjkkirschner** [comment] 2019-03-15 03:03
@melnikovalex I believe this was fixed on the pyRevit side. Please reopen if you see it using latest pyrevit.

**Closed by mjkkirschner** 2019-03-15 03:03 UTC
Labels: 2.x, needs investigation, needs more info
