### ISSUE TITLE
run mode menu coloration is misleading

### ISSUE THREAD

**Issue by AndrewHeumann** [DynamoDS/Dynamo#6631] opened 2016-05-16 15:04 UTC
If this issue is with Dynamo for Revit, please post your issue on the [Dynamo for Revit Issues page](https://github.com/DynamoDS/DynamoRevit/issues).

If this issue is **not** a bug report or improvement request, please check the [Dynamo forum](http://dynamobim.org/forums/forum/dyn/), and start a thread there to discuss your issue.
## Dynamo version

1.0
## Operating system

windows 7
## What did you do?

open run mode menu ("Automatic" "Manual" "Periodic")
## What did you expect to see?

Grey text for "unavailable," black for "available", as is standard in most UIs (you can't use it so it's "greyed out")
## What did you see instead?

![image](https://cloud.githubusercontent.com/assets/2157902/15293439/f1f96f24-1b55-11e6-83cd-7e5d5fd4f3d8.png)

black text for unavailable, grey text for available

**Comment by ikeough** [comment] 2016-05-16 16:09
![image](https://cloud.githubusercontent.com/assets/1139788/15295528/c0165496-1b45-11e6-8234-8f49607d0fa5.png)

@AndrewHeumann This is and image of the standard style for Dynamo. Perhaps the style is not being correctly applied on your machine.

**Comment by ikeough** [comment] 2016-05-16 16:11
<img width="232" alt="capture" src="https://cloud.githubusercontent.com/assets/1139788/15295576/f5ac2f72-1b45-11e6-9042-27c5871d63fe.png">

@AndrewHeumann This is a capture from my machine which shows the correct application of the standard style for the run settings control. Perhaps this style is not being applied correctly on your machine. Is anyone else in your firm having this issue? Do you have your windows desktop settings to "classic"?

**Comment by AndrewHeumann** [comment] 2016-05-16 17:49
my "Theme" is a typical aero theme (not "Basic"). I think I have seen others with the same problem but I am not 100% sure.

**Comment by AndrewHeumann** [comment] 2016-05-17 13:20
more info - this only occurs inside dynamo for revit, not standalone.

**Comment by brianringley** [comment] 2016-05-17 13:21
I am experiencing the same issue in Dynamo 0.9 for Revit 2015 on Windows 7

**Comment by jnealb** [comment] 2016-05-17 13:38
@AndrewHeumann @brianringley Curious, I can not repro this on WIn7 running Dynamo 1.0 ontop of Revit2016 with the WIn7 Aero theme.

**Comment by kronz** [comment] 2016-05-17 22:32
@brianringley @AndrewHeumann do you see this in Revit 2016 or 2017?

**Comment by AndrewHeumann** [comment] 2016-05-27 14:55
yes it still happens in 2016

**Comment by smangarole** [comment] 2017-07-27 19:53
@AndrewHeumann I cannot reproduce this issue. Closing this issue.

**Closed by smangarole** 2017-07-27 19:53 UTC
Labels: Bug, UI
