### ISSUE TITLE
getting crash from Display.ByGeometry

### ISSUE THREAD

**Issue by paoloemilioserra** [DynamoDS/Dynamo#6151] opened 2016-02-19 20:46 UTC
Dynamo 0.9.0.3572, Windows 7, Revit 2015

I created a color range to override the geometries based on the Cross-Section Rotation of beams in the Dynamo environment, crashed with the following log, second attempt Dynamo crashes at the welcome page, can't close Revit.

Unable to copy the ENTITY : NO_CUR_BB -- no current bulletin board exists

   at Autodesk.LibG.Solid.clone()
   at Autodesk.LibG.SolidHost.Clone()
   at Autodesk.LibG.GeometryHost.Scale(Double amount)
   at Revit.GeometryConversion.UnitConverter.InHostUnits[T](T geometry)
   at Revit.GeometryConversion.ProtoToRevitMesh.ToRevitType(Solid solid, TessellatedShapeBuilderTarget target, TessellatedShapeBuilderFallback fallback, ElementId MaterialId, Boolean performHostUnitConversion)
   at Dynamo.Applications.ViewModel.RevitWatch3DViewModel.RevitGeometryObjectFromGraphicItem(IGraphicItem item, List`1& geoms)
   at Dynamo.Applications.ViewModel.RevitWatch3DViewModel.Draw()
   at System.ComponentModel.PropertyChangedEventHandler.Invoke(Object sender, PropertyChangedEventArgs e)
   at Dynamo.Models.NodeModel.UpdateValueCore(UpdateValueParams updateValueParams)
   at Dynamo.Models.WorkspaceModel.UpdateModelValue(IEnumerable`1 modelGuids, String propertyName, String value)
   at Dynamo.Models.DynamoModel.UpdateModelValueImpl(UpdateModelValueCommand command)
   at Dynamo.ViewModels.NodeViewModel.ToggleIsVisible(Object parameter)
   at System.Windows.Controls.MenuItem.InvokeClickAfterRender(Object arg)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(Object source, Delegate method, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by ikeough** [comment] 2016-04-21 21:40
@aparajit-pratap Sounds like some interesting geometry stuff.

**Comment by aparajit-pratap** [comment] 2016-06-08 06:30
@paoloemilioserra we're having difficulty reproducing the crash. Could you share the Revit file and Dynamo graph you used so that we can reproduce and fix the crash. Thanks!

**Comment by smangarole** [comment] 2017-06-19 18:53
We have released a new version of Dynamo since this issue was opened. The issue has been waiting for feedback for almost a year. Closing due to these reasons. Please reopen if this issue resurfaces.

**Closed by smangarole** 2017-06-19 18:53 UTC
Labels: Bug, Critical, Geometry, Revit, Waiting for feedback
