### ISSUE TITLE
Wish: same size for nodes

### ISSUE THREAD

**Issue by epeter-** [DynamoDS/Dynamo#3709] opened 2015-02-06 09:04 UTC
![list1](https://cloud.githubusercontent.com/assets/6928491/6076717/5a9d9fce-ade7-11e4-88ba-16b205bdc1ca.png)
left is a codeblock node
right is a list.create node
were nice if same number of lines in a node results in a node of same size (length)

**Comment by Racel** [comment] 2017-10-16 19:20
I am assuming that the request is to automatically create a list of all the individual lines from the code block node. I suggest that they user either use the DS syntax {x,y,z} which will automatically create a list as they are typing in the list items. Or, read from an excel or csv file. From a development/UX standpoint, it will be difficult for us to predict whether or not you want us to create a list from all of the lines in a code-block or just some. This will require significant design/implementation effort to figure out. Closing.

**Closed by Racel** 2017-10-16 19:20 UTC
Labels: Improvement, UI

**Comment by Racel** [comment] 2017-10-16 20:21
It was called to my attention, that I might have misinterpreted the initial request. If the request was to have the node ports match up, we do not plan on working on this in the WPF UI. We will consider it as we work on the next generation of Dynamo. Still closing this for now.

**Comment by Racel** [comment] 2017-10-16 20:24
Duplicate of #8138
