### ISSUE TITLE
Dynamo will not start in the culture of correct language

### ISSUE THREAD

**Issue by Kelcyo** [DynamoDS/Dynamo#5456] opened 2015-10-06 15:20 UTC
Dynamo have the latest build installed on Windows 10 with Revit 2016 in pt-BR language. But to start the Dynamo it takes the English culture. I know I can start it off by changing the culture attribute, but would like to report this bug to identify where it performs the search of the boot language.

**Comment by ikeough** [comment] 2015-10-06 16:20
I believe this is because the daily builds do not have localized content, so it is falling back to english. This should not be the case with "stable" releases. @jnealb might know more.

**Comment by jnealb** [comment] 2015-10-06 17:51
@Kelcyo Are you running Portugese Windows 10 or English with locale set to BR? Are you starting Dynamo as a Revit Addin or standalone? What happens if you setup a desktop icon for Dynamo standalone with the cmd line option /L "pt-BR" and launch it?

**Comment by Kelcyo** [comment] 2015-10-06 19:49
@jnealb I am running Windows 10 with Language, and Region configured for Portuguese - Brazil.
I also know I can start it with the attribute / L "pr-BR" via shortcut as informed earlier.
The problem in question is in the booting Revit Addin.
Revit also in Portuguese-Brazil.
![sem titulo](https://cloud.githubusercontent.com/assets/11540152/10320507/2a47c760-6c4a-11e5-83ae-60a06f4954aa.png)

**Comment by jnealb** [comment] 2015-10-06 20:15
@Kelcyo Thank you - investigating.

**Comment by mjkkirschner** [comment] 2015-10-07 18:30
is this a dailybuild or a stable release install?

**Comment by jnealb** [comment] 2015-10-07 18:39
@Kelcyo One last question: can you tell us what your Revit Desktop icon has for a command line, under Properties? Is there a /language option at the end of the command line?

**Comment by jnealb** [comment] 2015-10-07 21:26
@Kelcyo @mjkkirschner  I can not reproduce your issue: on Windows 10 if my Revit Desktop icon has Properties of: "...\Revit.exe /language PTB" and I launch Dynamo as an Addin our app is loaded with Brazilian Portuguese menus etc. What is different with your scenario?

**Comment by jnealb** [comment] 2015-10-12 16:18
@Kelcyo Closing, unless you disagree? @Racel fyi

**Closed by jnealb** 2015-10-12 16:18 UTC

**Comment by Kelcyo** [comment] 2015-10-12 16:44
I'm performing testing on the Windows 10 Insider Preview builds to see if it is any incompatibility OS.
