### ISSUE TITLE
Element.GetParameterValueByName - inconsistent results

### ISSUE THREAD

**Issue by dbaldacchino** [DynamoDS/Dynamo#4310] opened 2015-04-22 21:36 UTC
Please see this simple graph (running 0.8.0.950). I am getting inconsistent results for the level names. Notice how some report just the name and others report more information, including the element id of the level. If I make a change to a level, the list changes and the output will shuffle again. This doesn't seem right. I tried it with rooms too, same result. Thanks.
![getparam](https://cloud.githubusercontent.com/assets/4656191/7285894/bc88ba50-e90d-11e4-80ee-9e7c748bf946.png)

**Comment by dbaldacchino** [comment] 2015-04-22 22:19
On a related note, I noticed that you cannot retrieve the value of a key associated with an object. For example if I have a key schedule associated with rooms, I cannot retrieve the key value, even though it appears as a parameter in the Revit model. I suppose those is expected since a key is technically not  parameter, but was wondering if there was a way to retrieve this in some way. Thanks.

**Comment by dbaldacchino** [comment] 2015-04-27 19:31
Just checked the same graph in 0.7.5 and it does the same (similar) thing. The exception as compared to the above, is that it doesn't throw a warning since instead of "null", the list would just have a blank. The other difference is that the list was sometimes writing element ids as string values it seems and not as clickable IDs highlighted in green as shown above. The inconsistency with reporting is still there for other parameters though, such as Design Options and Phases. Is this a Revit API problem, or an issue with this node?

![075 issue](https://cloud.githubusercontent.com/assets/4656191/7355839/1814b8a8-ecea-11e4-85e6-cea0d66873de.png)

**Comment by ThorHow** [comment] 2015-05-07 09:57
I have had a similar issue for weeks and coded my own little Python to get correct values - seems to be an issue with numbers....
My Dynamo stays at 0.8.1.1106 on 2015, since I'm currently demo:ing Dynamo for customers, but I tried a newer build a few days ago with the same issue.

![2015-05-07 11-53-14](https://cloud.githubusercontent.com/assets/12293403/7512802/c5362798-f4af-11e4-9296-b599df295a1d.png)

The python is just: 
items = UnwrapElement(IN[0])
parameternamn = IN[1]

elementlist = list()
for item in items:
	elementlist.append(item.LookupParameter(parameternamn).AsString())
OUT = (elementlist))

**Comment by cgrammens** [comment] 2015-05-08 18:01
@ThorHow I am trying to use you python work around and I have been getting an error in line 11

![image](https://cloud.githubusercontent.com/assets/4682090/7542367/0585812e-f571-11e4-981e-cd3fbcf74307.png)

SyntaxError: expected an indented block.  
I am new to python so I am not entirely sure what I am missing.

**Comment by ThorHow** [comment] 2015-05-08 18:06
Python wants it's loops indented, that is, tabbed. So just tab the "elementlist.append..." once and it should work.

But do consider using the normal Sheet.Sheet.Name node instead - it works.

**Comment by dbaldacchino** [comment] 2015-05-08 18:06
Simple fix...at the start of line 11, hit tab. That line needs to be indented as it is part of the For loop in line 10.

**Comment by dbaldacchino** [comment] 2015-05-08 18:25
@ThorHow I tried the Python script you posted but it doesn't retrieve most parameters. First of all it doesn't like parameter names with a space (errors out). I was looking at the parameters reported through Element.Parameters and using some of those to see if it returned those values but I was only successful getting room names and numbers in my example. Level returns null (and so did Perimeter, etc.). Any idea why? Thanks!

![roompython](https://cloud.githubusercontent.com/assets/4656191/7542835/a5725afe-f585-11e4-883f-68b037359a08.png)

**Comment by ThorHow** [comment] 2015-05-08 18:31
Well, it's a dirty hack ;-)

I do ".AsString" - and that one will only work if the parameter's storage type is actually string - a level is stored as an ElementId and will require another bit of magic.
Usually you have a bit check of the storagetype of the parameter and then alter your code to match - so sorry! My little code an incomplete little hack which only fix my issue (which was to hide the bug when I demo:ed Dynamo to customers....

**Comment by dbaldacchino** [comment] 2015-05-08 20:50
Ahhh gotcha :) Thanks for the info. I'm still in the novice stages, so this will take me some time to figure out!

**Comment by ThorHow** [comment] 2015-05-08 21:22
You a novice? That's a good one ;-)

There must already be a Python snipped around which does the proper job, it's not that hard to do (it's in the sample SDKs and in the very basic C# coding examples at like Tammik's place) but it'd be much nicer if the Dynamo node gets corrected since it's a pretty critical node.....

**Comment by dbaldacchino** [comment] 2015-05-08 22:20
When it comes to the Revit API and Python, the description "Noob" is too generous :)
I'll keep searching and will find something for sure. In the meantime I'm exploring other ways to get the same data, which is flexing my weak Dynamo muscles, especially when it comes to list management, processing and using more than basic functions.

**Comment by ThorHow** [comment] 2015-05-09 05:27
Yes, yes - of course - the famous man whose name can neither be spelled nor pronounced is a noob - sure...

The level of a room is in the API defined from the element - so I actually think the parameter lookup would fail anyway. I use the Clockwork node element.level.

**Comment by dbaldacchino** [comment] 2015-05-12 21:46
Here's my current workaround (just forcing myself to write definitions from scratch rather than using cutom nodes, just to learn and stretch my brian muscles! Not to mention ease of re-use without having to install packages). I'm simply altering the output of the node:

![level solution](https://cloud.githubusercontent.com/assets/4656191/7599300/6b160ccc-f8c6-11e4-8ad2-399d30ca4911.png)

**Comment by dbaldacchino** [comment] 2015-05-15 16:47
Phase is reporting the Phase Id instead. Man this node needs some serious work!

**Comment by monikaprabhu** [comment] 2015-05-20 15:23
Sorry for the inconvenience. I think this might be similar to the issue discussed in forum -http://dynamobim.com/forums/topic/sheet-numbers-and-getparametervaluebyname/ and is already tracked in MAGN- 5870.I'll discuss and request the  priority of this fix to be raised as many users are affected by this.

**Comment by dbaldacchino** [comment] 2015-05-20 15:36
Thanks, this node is very important to have working right for some basic data management/manipulation in Revit.

**Comment by ksobon** [comment] 2017-05-30 00:41
@kronz can we close this? This was resolved in 1.3 and discussed on numerous occasions. Please use BuiltInParameters instead of Parameter Name. Cheers!

**Comment by kronz** [comment] 2017-05-30 19:28
Yep!  It's way better in 1.3.  Thanks

**Closed by kronz** 2017-05-30 19:28 UTC
Labels: Critical, Revit

**Comment by ParametricMonkey** [comment] 2017-10-31 16:31
Sorry how is this fixed in 1.3? I have the same issue with rooms trying to get their phase. @ksobon are you saying I should be using another node instead...

![error](https://user-images.githubusercontent.com/10913639/32236010-1b6c459e-beb5-11e7-86e3-d59020f42bad.JPG)

**Comment by ksobon** [comment] 2017-10-31 16:53
I am saying that this is actually "functionality" of Revit API. It let's you select a parameter by name or by builtInparameter name. The former comes with a "risk" of inconsistent results since there are multiple parameters with the same name present in an un-ordered set. That's not a bug, it's just how it works to make it faster. If anything you should be asking for a new node that let's you select by BIP name instead, but that's a different conversation.

**Comment by ParametricMonkey** [comment] 2017-10-31 17:15
@ksobon 'Multiple parameters with the same name' - are you saying I have 2 parameters called 'Phase' assigned to the room category?

**Comment by ksobon** [comment] 2017-10-31 17:38
Possible, if you can have multiple Category and Level parameters like this: 

![untitled-1](https://user-images.githubusercontent.com/529781/32239359-b7cb506c-be40-11e7-8096-4c916d25df3d.jpg)

**Comment by ParametricMonkey** [comment] 2017-10-31 17:56
@ksobon there is only one phase in BIP  but there are 2 categories and 2 levels. How does this happen for a single element? I'm confused.

**Comment by ksobon** [comment] 2017-10-31 18:10
Well it stores Level name which returns a string name for that level, and Level Id which returns ElementId for that level in two parameters that have a name "Level", but different BIP pointers. It makes sense if you are hiding one of those from the user anyways. Parameters have a singular storage type so if you want to store a string and element id you need two parameters. But I am just saying that it's possible and these nodes in Dynamo work as intended, but they need to better explain what CAN potentially happen.

**Comment by ParametricMonkey** [comment] 2017-10-31 18:22
Sorry I'm still confused. I'm dealing with rooms and their phases. How does this occur - some models works fine, other not? What triggers this?

And how can I fix it? Is it a Dynamo issue or a Revit modelling issue?

**Comment by ksobon** [comment] 2017-10-31 18:32
If you do something along these lines: 

https://forum.dynamobim.com/t/finding-builtinparameters-for-view-specifically-view-name/15702/11?u=konrad_k_sobon

...and still are having issues then we can narrow it down to something else than faulty Dynamo node.

**Comment by dbaldacchino** [comment] 2017-10-31 19:15
So Konrad you're saying that using the BIP is more reliable than using the
get parameter by name node, correct?

**Comment by ThorHow** [comment] 2017-10-31 19:53
Like Konrad said, some elements have several parameters with the same name - some of those are exposed to the user and some are not. 
However they are all exposed to the API, and therefore, also Dynamo. 
Sometimes there are even parameters with the same name, some changeable (read-write) and some not (read-only). 

When you use the function ParameterByName a parameter is selected/found and if there are multiple parameters with the same name then one of chosen almost by random. Sometimes a read-write, sometimes a read-only and chaos might occur.

The BIP, built-in-parameter, is a way around that - those codes/pointers will directly point to the correct, desired parameter. Such as ParameterByBuilt-in-parameter - there are a few of those functions around in packages.
