### ISSUE TITLE
Forbidden characters for custom node inputs

### ISSUE THREAD

**Issue by andydandy74** [DynamoDS/Dynamo#5072] opened 2015-08-10 09:38 UTC
When using an input node it seems that some characters are forbidden now.
Example:
I wanted to type:
`my_label_name : string = ","`
but ended up with:
`my_label_name : string = ""`
This does not only happen with a comma but also with a semicolon...
Dynamo 0.8.1

**Comment by andydandy74** [comment] 2015-09-15 04:48
Workaround: Special characters can be copy/pasted into an input node...

**Comment by ikeough** [comment] 2016-05-01 15:50
@andydandy74 This is because the input node now accepts design script expressions. I would assume we disallow these characters for that reason. @ke-yu Can you comment here, and close if this is by design?

**Comment by Racel** [comment] 2017-10-16 20:03
This is working in the latest build of 2.0. Closing as fixed.

**Closed by Racel** 2017-10-16 20:03 UTC
Labels: Custom Nodes, Improvement, UI
