### ISSUE TITLE
Dynamo crashes daily build 20150122T2151

### ISSUE THREAD

**Issue by epeter-** [DynamoDS/Dynamo#3618] opened 2015-01-24 10:16 UTC
crashes when changing from custom node window to standard workspace.
what i observed:
since now input and output of custom nodes are named automatically (output starting from 0 to n). 
i changed the names of input and output.
when swapping from custom node worspace back to the dyn workspace. 
the changes were ignored, dynamo chrashed (in the custom node created the renaming worked)

**Comment by epeter-** [comment] 2015-01-24 11:33
problem persists in daily build of 20150123T2126
crashes when switching from dyf workspace to dyn workspace

**Comment by jnealb** [comment] 2015-01-25 15:29
@epeter- I am unable to reproduce this with 20150123T0810 (version 0.7.6.3881). 

My steps are:
1. Create definition with 3 number inputs, 1 list create and 1 list.sort
2. Populate the inputs, click the + 2 times in list create and hook everything up
3. With the mouse select the list.create and list.sort nodes and create a custom node
4. Double click it to open a new custom node pane
5. Rename the inputs and outputs from the right click menu
6. Click Run
7. Click on the Home workspace tab
// no crash
8. Continue to change values, Run and switch back and forth between the two panes

Can you please provide us with exact steps? The definition contents and/or steps may matter.

Thanks!

**Comment by epeter-** [comment] 2015-01-25 18:00
neal, thank you for your email.
meanwile i moved to the daily build of 20150124T05xx
this new version seems to be stable again.
I will close the issue for now and keep on testing.
regards peter

Am 25.01.2015 um 16:29 schrieb Neal Burnham:
>
> @epeter- <https://github.com/epeter-> I am unable to reproduce this 
> with 20150123T0810 (version 0.7.6.3881).
>
> My steps are:
> 1. Create definition with 3 number inputs, 1 list create and 1 list.sort
> 2. Populate the inputs, click the + 2 times in list create and hook 
> everything up
> 3. With the mouse select the list.create and list.sort nodes and 
> create a custom node
> 4. Double click it to open a new custom node pane
> 5. Rename the inputs and outputs from the right click menu
> 6. Click Run
> 7. Click on the Home workspace tab
> // no crash
> 8. Continue to change values, Run and switch back and forth between 
> the two panes
>
> Can you please provide us with exact steps? The definition contents 
> and/or steps may matter.
>
> Thanks!
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/DynamoDS/Dynamo/issues/3618#issuecomment-71377350>.
>



---
Diese E-Mail wurde von Avast Antivirus-Software auf Viren geprüft.
http://www.avast.com

**Comment by holyjewsus** [comment] 2015-01-25 19:14
I have noticed this intermittently as well, seems to occur when you have a custom node on the canvas that uses code blocks, but have not narrowed it down yet.

**Comment by epeter-** [comment] 2015-01-25 21:17
my guess was that it was caused by renaming input / output (changing 
v0....vx)

Am 25.01.2015 um 20:14 schrieb Michael Kirschner:
>
> I have noticed this intermittently as well, seems to occur when you 
> have a custom node on the canvas that uses code blocks, but have not 
> narrowed it down yet.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/DynamoDS/Dynamo/issues/3618#issuecomment-71386897>.
>



---
Diese E-Mail wurde von Avast Antivirus-Software auf Viren geprüft.
http://www.avast.com

**Comment by monikaprabhu** [comment] 2015-01-26 06:00
@epeter- I'm able to reproduce this - I think this crash is similar to Dynamo issue - https://github.com/DynamoDS/Dynamo/issues/3559.Which is tracked at MAGN-5869.I'll add the steps to reproduce this one to the same issue. Thanks Everyone

**Comment by ikeough** [comment] 2016-05-03 04:59
Internal issue is closed in 
https://github.com/DynamoDS/Dynamo/pull/3624. Please re-open if you're still seeing this in newer versions of Dynamo.

**Closed by ikeough** 2016-05-03 04:59 UTC
