### ISSUE TITLE
Crash after editing two python scripts (one in dyn and one in custom node dyf) - "Model not found"

### ISSUE THREAD

**Issue by tatlin** [DynamoDS/Dynamo#10592] opened 2020-04-23 14:45 UTC
If this issue is with Dynamo for Revit, please post your issue on the [Dynamo for Revit Issues page](https://github.com/DynamoDS/DynamoRevit/issues).

If this issue is **not** a bug report or improvement request, please check the [Dynamo forum](https://forum.dynamobim.com/), and start a thread there to discuss your issue.

## Dynamo version

2.3 running in Revit 2020

## Operating system

Windows 10

## What did you do? 

- I was editing two python scripts, one insides a dyf, one in the main dyn. 
- I left the modeless dialog up from the python node in the main dyn file, then started editing a custom node dyf, and a python script inside the dyf.
- I had the two modeless python windows up next to each other, to compare the two scripts. 
- i did not edit anything in the dyf, simply closed the inner python, switched back to the main dyn tab and tried to save the outer python. 
- Dynamo entered crash protection with this warning: 

UpdateModelValue: Model not found

   at Dynamo.Graph.Workspaces.WorkspaceModel.UpdateModelValue(IEnumerable`1 modelGuids, String propertyName, String value)
   at Dynamo.Models.DynamoModel.UpdateModelValueImpl(UpdateModelValueCommand command)
   at Dynamo.Models.DynamoModel.ExecuteCommand(RecordableCommand command)
   at PythonNodeModelsWpf.ScriptEditorWindow.UpdateScript(String scriptText)
   at PythonNodeModelsWpf.ScriptEditorWindow.OnSaveClicked(Object sender, RoutedEventArgs e)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.Controls.Primitives.ButtonBase.OnClick()
   at System.Windows.Controls.Button.OnClick()
   at System.Windows.Controls.Primitives.ButtonBase.OnMouseLeftButtonUp(MouseButtonEventArgs e)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.ReRaiseEventAs(DependencyObject sender, RoutedEventArgs args, RoutedEvent newEvent)
   at System.Windows.UIElement.OnMouseUpThunk(Object sender, MouseButtonEventArgs e)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.InputManager.ProcessInput(InputEventArgs input)
   at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
   at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

## What did you expect to see?

Not a crash

## What did you see instead?

crash protection and call stack above

**Comment by tatlin** [comment] 2020-04-23 14:55
Also note the backup file was corrupted - the dyn file saved as the latest backup was actually the custom node dyf instead. 

This caused me to lose about 30 min of work

**Comment by mjkkirschner** [comment] 2020-04-23 15:41
Hi @tatlin!

These should both be fixed now - 
https://github.com/DynamoDS/Dynamo/pull/10119
https://github.com/DynamoDS/Dynamo/pull/9988

**Comment by johnpierson** [comment] 2020-05-29 20:40
Duplicate of, #9479

**Closed** 2020-05-29 20:50 UTC
