### ISSUE TITLE
Need a node to export the geometry view

### ISSUE THREAD

**Issue by andydandy74** [DynamoDS/Dynamo#5427] opened 2015-10-04 05:55 UTC
It would be really useful to be able to export the current state of Dynamo's geometry view by means of a node. I am thinking of workflows that let the geometry iterate through a number of states, each time exporting an image. Lots of use cases for that, methinks.

**Comment by ksobon** [comment] 2015-10-07 01:54
me agrees

**Comment by alfarok** [comment] 2017-11-07 17:24
closing this as a duplicate of [4677](https://github.com/DynamoDS/Dynamo/issues/4677)

**Closed by alfarok** 2017-11-07 17:24 UTC
Labels: Improvement
