### ISSUE TITLE
Select Face crashing

### ISSUE THREAD

**Issue by frod083** [DynamoDS/Dynamo#6172] opened 2016-02-25 00:51 UTC
## Dynamo version

0.9 & 1.0
## Operating system

7
## What did you do?

There is a bug when I select a face in Revit and have the 'show revit background' option turned on.  It will come up with the 'Run Started' at the bottom but never complete if it's turned on - 'Run Completed' if it's turned off.  Not sure if its got to do with running 3 screens......
## What did you expect to see?

(Fill in here)
## What did you see instead?

(Fill in here)

**Comment by ikeough** [comment] 2016-05-01 15:58
@frod083 Can you post some screen shots here?

**Comment by alfarok** [comment] 2017-11-07 17:35
@frod083 I am unable to reproduce this in more recent Dynamo for Revit builds so I am closing the issue. 
 Please feel free to reopen if you are still experiencing similar behavior.

**Closed by alfarok** 2017-11-07 17:35 UTC
Labels: Bug, Graphics, Revit
