### ISSUE TITLE
Cannot enter text into Input or Code Block node in 0.9.1

### ISSUE THREAD

**Issue by brianringley** [DynamoDS/Dynamo#6199] opened 2016-03-02 18:30 UTC
## Dynamo version

0.9.1.4062
## Operating system

Windows 7
## What did you do?

Launch Revit 2016
Launch Dynamo 0.9.1
New > Custom Block
Added Input and Code Block node to graph
Attempted to add text - no text is added
## What did you expect to see?

Some text
## What did you see instead?

No text

**Comment by brianringley** [comment] 2016-03-02 19:23
Uninstalled all previous versions of Dynamo - did not help.

Issue occurs in both Revit 2015 and Revit 2016.

Issue does not occur in standalone Dynamo.

**Comment by brianringley** [comment] 2016-03-02 19:38
Tried uninstalling all versions of Dynamo, then reinstalling Dynamo 0.9.1 stable (0.9.1.4062) - did not help

**Comment by jnealb** [comment] 2016-03-02 19:41
@brianringley Can you please provide more detail on your exact steps? I am able to add Code Block Nodes to a Custom Node and populate the CBN with text, but I am not sure if that is your workflow.

**Comment by brianringley** [comment] 2016-03-02 19:50
@jnealb 
Launch Revit 2016
Launch Dynamo 0.9.1
New > Custom Block
Added Input and Code Block node to graph
Attempted to add text - no text is added

**Comment by jnealb** [comment] 2016-03-02 19:54
@brianringley "Attempted to add text - no text is added" can you please be specific: did you edit the CBN? Did you edit the Input node?

**Comment by brianringley** [comment] 2016-03-02 19:57
@jnealb I click in the text fields of either node and nothing happens

Normal behavior would be that a cursor would appear and I can start typing

If I double-click the canvas to initiate the code block I can type into it

This of course doesn't solve the input node issue within custom blocks

I've stripped out all my packages to no avail

I'm going to speak internally with IT here to reset my user profile so I can reinstall Revit and Dynamo with a clean slate

**Comment by brianringley** [comment] 2016-03-02 19:59
If I copy in an existing input or code block node with text into my current custom node document I can edit it.

I cannot edit a fresh input or code block node.

**Comment by jnealb** [comment] 2016-03-02 20:23
@brianringley I can not reproduce this

**Comment by ikeough** [comment] 2016-04-21 21:18
@jnealb Can we follow up with @brianringley? If we definitely can't reproduce, then let's close this.

**Comment by jnealb** [comment] 2016-04-21 21:27
@brianringley Are you still seeing this? Thanks for an update.

**Comment by brianringley** [comment] 2016-04-22 08:26
@ikeough @jnealb yes this is still an issue with Input and Code Block nodes in 0.9.2.

To use custom block Input nodes I either have to generate the custom block from a Dynamo graph (rather than file > custom block) or I have to copy and past an existing Input node pre-filled with text from an older file.

Code Block nodes seem to be behaving a bit differently - I can enter text into them if I begin typing immediately upon placing the node onto the canvas - otherwise I cannot enter text at all.

Thank you for your attention to this issue!
B

**Comment by brianringley** [comment] 2016-04-22 13:09
@ikeough @jnealb  [https://twitter.com/brianringley/status/723498665927688192](https://twitter.com/brianringley/status/723498665927688192)

**Comment by AndrewHeumann** [comment] 2016-04-22 14:54
I have had this issue intermittently as well. It does not occur in the standalone 0.92, but does in revit 2014 and 2015 (have not checked 2016). See screen capture:
https://www.dropbox.com/s/b1l1yfh761fsuc7/dynamo%20code%20block%20bug.mp4?dl=0

**Comment by mjkkirschner** [comment] 2016-04-22 14:55
hmm, are you guys on high dpi screens?

**Comment by AndrewHeumann** [comment] 2016-04-22 15:06
Nope - just normal res 1920x1200 dell monitors

**Comment by ikeough** [comment] 2016-04-22 16:09
@brianringley @AndrewHeumann Do both of you have any kind of mouse presentation capture software installed? Like the kind that makes your mouse clicks flash or highlight when you screen capture?

**Comment by brianringley** [comment] 2016-04-22 17:18
Yes camtasia

**Comment by AndrewHeumann** [comment] 2016-04-22 18:33
although I only had it running to record the issue - issue occurs even when camtasia is not running at all.

**Comment by smangarole** [comment] 2017-06-26 14:48
@brianringley @AndrewHeumann - Is this still an issue with the latest version of Dynamo?

**Closed** 2017-06-26 15:07 UTC
Labels: Bug, Can't Reproduce, Major, Revit
