### ISSUE TITLE
Slow Search response

### ISSUE THREAD

**Issue by dbaldacchino** [DynamoDS/Dynamo#4047] opened 2015-03-19 19:00 UTC
I have been noticing a big difference in the Search response with Dynamo on Windows 7 (normal) vs. on Windows 8.1 (slow). Is this a known problem? What would cause the Search to feel sluggish and not very responsive? In Windows 7, the list starts refining itself as you type, whereas on Window 8.1 you start entering letters and you don't even see the text at first, then it suddenly starts responding; not a very good user experience.

**Comment by pboyer** [comment] 2015-03-20 19:24
@elayabharath @Benglin This looks important!

**Comment by epeter-** [comment] 2015-03-20 20:32
+ 1 
since before search was lame, but since the change to the graphical menu its sometimes 30 secs till a result shows up

**Comment by dbaldacchino** [comment] 2015-03-20 20:54
I initially thought it was because of the graphical UI, but I'm noticing the above on the non-graphical stable release 0.7.5.3566.

**Comment by epeter-** [comment] 2015-03-20 20:58
i  absolutely agree. same here. but graphical interface made it worse

**Comment by kronz** [comment] 2015-03-20 21:24
anything you folks can say about your particular setups?  System specs?  Graphics cards?  This is not reproducing on a couple of our machines at the office, so trying to see what you have in common

**Comment by epeter-** [comment] 2015-03-20 22:14
![system](https://cloud.githubusercontent.com/assets/6928491/6761754/9210cd7e-cf56-11e4-8481-8b4b4c6d30ba.png)
graphics = 
![nvida](https://cloud.githubusercontent.com/assets/6928491/6761778/cad6b3c6-cf56-11e4-825b-e73d37128901.png)

**Comment by dbaldacchino** [comment] 2015-03-20 22:22
Hi Zac, I'll send you the output of my msinfo32.exe from my laptop.

**Comment by pboyer** [comment] 2015-03-21 02:29
Which packages installed? We need to reproduce exactly what you have in
search.

**Comment by dbaldacchino** [comment] 2015-03-21 02:55
It's slow without any packages but just in case, I have Clockwork and Ampersand.

Sincerely, Dave
(Sent from my Android device)

**Comment by epeter-** [comment] 2015-03-21 08:58
all packages available (at least most of them).... btw reminds of still 
unsolved conflict dynamo - rhynamo (Point.By.....) which is misinterpreted
regards peter

Am 21.03.2015 um 03:29 schrieb Peter Boyer:
> Which packages installed? We need to reproduce exactly what you have in
> search.
>
> On Fri, Mar 20, 2015, 6:22 PM Dave Baldacchino <notifications@github.com>
> wrote:
>
> > Hi Zac, I'll send you the output of my msinfo32.exe from my laptop.
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/DynamoDS/Dynamo/issues/4047#issuecomment-84169271>.
> >
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/DynamoDS/Dynamo/issues/4047#issuecomment-84221505>.
>



---
Diese E-Mail wurde von Avast Antivirus-Software auf Viren geprüft.
http://www.avast.com

**Comment by ikeough** [comment] 2015-03-21 18:44
@dbaldacchino @epeter- Are you both running Dynamo on top of Revit 2015 when the problem occurs?

**Comment by dbaldacchino** [comment] 2015-03-21 18:55
No, Revit 2014 is what I've been using mainly. But it does the same in 2015 and stand-alone.

Sincerely, Dave
(Sent from my Android device)

**Comment by pboyer** [comment] 2015-03-21 19:21
@ikeough This smells of a binding issue to me.

**Comment by epeter-** [comment] 2015-03-21 19:22
solely revit 2015.
btw dynamo in 2016 seems to be an empty shell

Am 21.03.2015 um 19:44 schrieb Ian Keough:
>
> @dbaldacchino <https://github.com/dbaldacchino> @epeter- 
> <https://github.com/epeter-> Are you both running Dynamo on top of 
> Revit 2015 when the problem occurs?
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/DynamoDS/Dynamo/issues/4047#issuecomment-84417697>.
>



---
Diese E-Mail wurde von Avast Antivirus-Software auf Viren geprüft.
http://www.avast.com

**Comment by kronz** [comment] 2015-03-23 14:33
@jnealb do you have a Win8 setup we can check this against?

**Comment by Benglin** [comment] 2015-03-31 04:49
@aosyatnik has been working on [improving the performance](https://github.com/DynamoDS/Dynamo/pull/4127) this week, we believe this will address some start-up time delay and probably, to a lesser extent, search speed. We don't currently have any numbers for this yet until the work is finalized.

**Comment by ParametricMonkey** [comment] 2015-04-01 22:01
I'm using the 0.8 candidate release. The release has been stable so far. However, I am experiencing slow searches. Running windows 7 and Dynamo within Revit. Only Ideate Bimlink & explorer and sefaira installed as plug-ins

**Comment by pboyer** [comment] 2015-04-01 23:27
Windows 8.1?

**Comment by ParametricMonkey** [comment] 2015-04-01 23:30
windows 7

**Comment by Benglin** [comment] 2015-04-02 04:41
The [performance improvement changes](https://github.com/DynamoDS/Dynamo/pull/4127) have been merged into `master` branch. If you don't mind, you can give the latest daily build a try and see if it improves things for you. Like I said, this improves the start-up time more than search, so it will be interesting to know how this turns out for you. Thanks in advance, @ParametricMonkey!

**Comment by dbaldacchino** [comment] 2015-04-03 14:33
The latest build DynamoInstall0.8.1.20150402T2034.exe is not working at all on Windows 8.1 in standalone mode. Search lag is still the same.

**Comment by jnealb** [comment] 2015-04-03 14:48
@dbaldacchino Does it load? Does it give errors? Does it freeze/hang?

**Comment by dbaldacchino** [comment] 2015-04-03 15:04
@jnealb it actually doesn't do anything. DynamoSandbox.exe doesn't even show up in Task Manager. The Add-In works as usual in Revit 2015. I did restart the machine after installing but the standalone version still doesn't load.

**Comment by dbaldacchino** [comment] 2015-06-01 15:37
Latest build works in Sandbox and within Revit 2014 & 2015 (have not tested 2016 yet). Search response is still slow; works good on a desktop with Windows 7. Could this be something to do with the fact that the laptop uses two graphic processors for different situations? It uses the on-board Intel graphics for normal operation and supposedly switches to the Nvidia graphics for graphic-intensive applications. Could it be it's trying to run on the Intel hardware and not switching to Nvidia when in Dynamo? Does it even matter?

**Comment by ikeough** [comment] 2015-06-01 17:14
Search responsiveness should not be tied to display adapter. But...can you try ensuring that your machine is NOT in power saving mode and see if that affects search speed? Some of those power settings cripple disk access (although search should be in memory).

**Comment by holyjewsus** [comment] 2015-06-01 17:15
@dbaldacchino is this a parallels VM running windows 8?

**Comment by pboyer** [comment] 2015-06-01 17:28
@ikeough Under the hood (in the render thread), WPF depends on DirectX.
Still, I would be surprised if that was the core of this issue.

@dbaldacchino, I'm curious what kind of output you see if you attach
DebugView:

https://technet.microsoft.com/en-us/sysinternals/bb896647.aspx




On Mon, Jun 1, 2015 at 10:15 AM, Michael Kirschner <notifications@github.com

**Comment by dbaldacchino** [comment] 2015-06-01 18:01
@ikeough It was in Balanced mode and plugged in. I changed to Performance: no change observed.
@holyjewsus No, native windows machine (M3800 laptop), no virtualization.
@pboyer Downloaded and ran it, but it's not logging any info. when I type anything in the search. Should it?

**Comment by jnealb** [comment] 2015-07-20 21:44
@dbaldacchino We made a fix in the latest daily build that may be related to the slow search that you reported. Can you give us an update?

**Comment by dbaldacchino** [comment] 2015-07-21 00:13
Hi @jnealb , it seems to have improved on Windows 8.1 from previous versions, although still a bit slower than Windows 7, but not as bad as it used to be. Just for some more context, the main difference between the desktop (Win 7) and my laptop (Win 8.1) is that the laptop has onboard graphics AND Nvidia hardware so it switches between the two depending on the task. The desktop uses the Nvidia hardware at all times. Anyway, on both systems the new search in the right-click menu is faster than the "permanent" search box and behavior is consistent under both OSes and hardware configurations.

**Comment by jnealb** [comment] 2015-07-22 14:00
Closing. Thanks Dave!

**Closed by jnealb** 2015-07-22 14:00 UTC

**Comment by jnealb** [comment] 2017-04-21 13:53
We have a report of this from Håvard Vasshaug with Dynamo 1.3 and would like to know if others have seen the issue (again)? Thanks.

**Comment by andydandy74** [comment] 2017-04-21 18:54
https://forum.dynamobim.com/t/search-in-dynamo-revit-is-painfully-slow/11029
