### ISSUE TITLE
GetItemAtIndex and Replication guide

### ISSUE THREAD

**Issue by vykrum** [DynamoDS/Dynamo#5004] opened 2015-07-27 14:36 UTC
Ver: 0.8.2.2073
Tried to expand on a code example provided by @holyjewsus  at #4938 and ran into an error, not the result I expected.
The screen grab below should help explain the reason I find the error to be inconsistent.

![20150727-2](https://cloud.githubusercontent.com/assets/5621624/8908624/c579ee1c-349a-11e5-82f3-4415461e99f5.jpg)

**Comment by holyjewsus** [comment] 2015-07-27 14:55
I think you need to replicate over your second argument as well, try <2> after the parentheses

**Comment by vykrum** [comment] 2015-07-27 16:43
@holyjewsus your suggestion works, but there still seems to be a problem - works if both statements are in the same code block. Fails otherwise.

![20150727-4](https://cloud.githubusercontent.com/assets/5621624/8911864/9bedd8d0-34ac-11e5-8ee3-b6598792e439.jpg)

![20150727-5](https://cloud.githubusercontent.com/assets/5621624/8911868/a2167fa0-34ac-11e5-91c7-3cdc305dc5d4.jpg)

**Comment by holyjewsus** [comment] 2015-07-27 16:45
@vykrum that looks like a bug to me, but can you try one more thing, try wrapping your list {0,1} in a parentheses  before replicating, sorry I cannot test currently.

**Comment by vykrum** [comment] 2015-07-27 16:46
@holyjewsus Already tried it. Similar results when wrapped in parentheses

**Comment by holyjewsus** [comment] 2015-07-27 16:48
@vykrum thanks for the test case, will track internally

**Comment by vykrum** [comment] 2015-07-27 16:53
Just realized something. If you reopen the file with the two separate code blocks, it works fine.
If the first replication guide is <1> and you delete the second one and Run, it throws up an error.
The error continues to show up even after reintroducing the second replication guide.

Reopening the file seems to sort it out.

**Comment by holyjewsus** [comment] 2015-07-27 16:54
@vykrum  yes, I've found the same inconsistencies when trying to demo this functionality, seems similar to the function redefinition issues you have pointed out.

**Comment by vykrum** [comment] 2015-07-27 17:02
@holyjewsus  This would be a good alternative to Transpose, if it works consistently. 
Thanks for introducing this possibility with your example.

**Comment by holyjewsus** [comment] 2015-08-03 13:21
tracked as MAGN 8047

**Comment by ikeough** [comment] 2016-05-03 04:40
Internal bug is marked as can't reproduce. Please re-open if this is still an issue with the latest version of Dynamo.

**Closed by ikeough** 2016-05-03 04:40 UTC
Labels: Bug, Can't Reproduce
