### ISSUE TITLE
Crash Report - 20150730

### ISSUE THREAD

**Issue by vykrum** [DynamoDS/Dynamo#5022] opened 2015-07-30 18:24 UTC
Version: 0.8.2.2085
OS: Win7

1.Run the below definition (It works)
2.Push the top number slider back to a reduced value and Run (It works)
3.Push the slider back to the old value and Run (Crash)

![20150730-2](https://cloud.githubusercontent.com/assets/5621624/8991420/1ce3ce8e-3716-11e5-9305-0cf392972b0e.jpg)

**Comment by monikaprabhu** [comment] 2015-08-18 06:09
@vykrum - could you please try this on latest build and check if its reproducible ?I could not reproduce this with latest daily build -  We have fixed an issue that has similar steps as above, but was generating some warnings. So it would be great if you can retest and let us know. Thanks.

**Comment by vykrum** [comment] 2015-08-18 09:01
@monikaprabhu Tried with 0.8.3.2250 on Windows 10. Seems to work fine.
However, I don't have any background graphics (in general), as reported earlier.

**Comment by johnpierson** [comment] 2018-11-29 16:51
Closing as this issue is for an outdated version of Dynamo. If this persists in 2.0.x for you, please feel free to reopen and update accordingly.

**Closed by johnpierson** 2018-11-29 16:51 UTC
Labels: 0.x, crash, engine, priority
