### ISSUE TITLE
Clear custom node breaks parent file (in 6.3)

### ISSUE THREAD

**Issue by TimWaldock** [DynamoDS/Dynamo#1529] opened 2014-04-20 22:32 UTC
This is a workflow (misunderstanding) issue that caused data loss then a crash:
1. Create a custom node from selection (4 inputs 1 output)
2. Noticed that one of four input connectors was missing
3. Right-click to edit the custom node
4. could not return to main file by clicking on tab
5. Tried to close custom node by File Clear (instead of just clicking the cross on the tab)
6. So, it keeps node open but clears content.  This may be as designed but its an easy user workflow mistake to make - it needs to be more robust to prevent this.
7. Finally suceeded in getting back to the main dynamo file.  All connectors have gone, custom node is reduced to just a title (still didn't realise I had cleared it)
8. Tried to close out without saving by File Exit;  mistakenly said Yes to save (Duh!)
9.  Crashed out of Dynamo

**Comment by ikeough** [comment] 2016-04-27 04:53
@TimWaldock The internal issue was closed as unable to reproduce. I apologize for the delayed response.

Closing as out of date. If this is still an error in more recent builds, please re-open.

**Closed by ikeough** 2016-04-27 04:53 UTC
Labels: Can't Reproduce
