### ISSUE TITLE
BUG report from Dynamo 2.13.1.3887

### ISSUE THREAD

**Issue by atis-s** [DynamoDS/Dynamo#13387] opened 2022-10-09 09:32 UTC
# Issue Description
All groups and node order are LOST on reopen! 
Everything is clumped together!!
![image](https://user-images.githubusercontent.com/22381084/194749179-289ed947-d14b-42de-a736-1a6a6c2902b9.png)

## Dynamo version
Dynamo: `2.13.1.3887`

## Operating system
OS: `Microsoft Windows NT 10.0.19044.0`

## What did you do?
Closed and opened the file.
Closed and opened dynamo

## What did you expect to see?
Node groups

## What did you see instead?
Pile of nodes

## What packages or external references (if any) were used?
![image](https://user-images.githubusercontent.com/22381084/194749226-4ded747e-0ddc-4b9d-9502-8c4107e10e13.png)

## Stack Trace
```
(From the Dynamo crash window select 'Details' -> 'Copy' and paste here)
```

---
CLR: `4.0.30319.42000`

**Comment by QilongTang** [comment] 2022-10-12 15:58
@atis-s Would you share the file with us?

**Comment by atis-s** [comment] 2022-10-13 18:33
Sorry, I cannot replicate the issue. Maybe it was because I was uninstalling Data-shapes package, then reopened file before the removal was complete. After the Revit restart everything works fine.

**Comment by QilongTang** [comment] 2022-10-13 19:20
@atis-s Gotcha. I am going to close it for now until we find reproducible steps. There is a similar report on forum but the cause might be totally different there.

**Closed by QilongTang** 2022-10-13 19:20 UTC
