### ISSUE TITLE
Bug: Sheet.ByNameNumberTitleBlockAndView(s) failing to work with "EnginneringPlan" view types

### ISSUE THREAD

**Issue by dimven** [DynamoDS/Dynamo#4252] opened 2015-04-16 03:55 UTC
Hello,

As stated above the two nodes fail specifically and only with structural plans. They work as expected with floor plans, sections, elevations, etc.
![2015-04-16_11-32-58](https://cloud.githubusercontent.com/assets/7148394/7173642/767682e8-e42d-11e4-86ac-b356f28c07bf.png)

![2015-04-16_11-36-47](https://cloud.githubusercontent.com/assets/7148394/7173644/7fd462c4-e42d-11e4-83b5-781fc2957eeb.png)

![2015-04-16_11-33-25](https://cloud.githubusercontent.com/assets/7148394/7173648/834edf56-e42d-11e4-9ac1-61829a0229f7.png)

Furthermore the "Views" node has been a bit of a mess for the last few releases. It fails to display a proper list of views. It repeats the UI views list 2 - 4 times and then on top of that, it seems to add all the views once more using their types?

![2015-04-16_11-39-35](https://cloud.githubusercontent.com/assets/7148394/7173785/8792a38e-e42f-11e4-902c-3b5d780c5492.png)

**Comment by andydandy74** [comment] 2015-04-16 05:21
That last part is a duplicate of #3345 (which is a **really** annoying bug on large projects BTW)

**Comment by dimven** [comment] 2015-06-06 12:17
Another node that doe not work with structural plans(EngineeringPlan view type) is the Sheet.Views

**Closed** 2015-11-05 10:16 UTC
