### ISSUE TITLE
Sliders won't update when switching from automatic to manual mode

### ISSUE THREAD

**Issue by rverweij** [DynamoDS/Dynamo#5198] opened 2015-08-28 06:53 UTC
When switching from automatic mode to manual mode, both the integer and number slider don’t seem to update to the value they had when leaving automatic mode, they will update to any other value except that one. 
For instance I have a number slider min=0, max=3, step=1, in automatic mode I set the value to “2” I then switch to manual mode, change the value to something else (no problem) change back to “2” and it won’t update.

![slider issue](https://cloud.githubusercontent.com/assets/14011484/9540746/3e293234-4d62-11e5-9c58-c9c4d4416b76.png)

**Comment by ke-yu** [comment] 2015-09-04 05:40
hi @rverweij , which version of Dynamo you are using? I'm not able to reproduce it with the latest build.

**Comment by rverweij** [comment] 2015-09-04 11:22
Just after reporting this here, I switched to Dynamo 0.8.2.2392, I use it in Revit 2015. I think it was the one of the last versions of 0.7 when I noticed this. The problem however still excist in the 0.8.2.2392 version, although now I do get an error message: 

Exception of type 'ProtoCore.Exceptions.CompilerInternalException' was thrown.

   at ProtoCore.Utils.Validity.Assert(Boolean cond)
   at ProtoScript.Runners.ChangeSetApplier.ApplyChangeSetForceExecute(ChangeSetData changeSet)
   at ProtoScript.Runners.LiveRunner.SynchronizeInternal(GraphSyncData syncData)
   at ProtoScript.Runners.LiveRunner.UpdateGraph(GraphSyncData syncData)
   at Dynamo.Core.Threading.AsyncTask.Execute()

Make sure you use the slider in automatic mode first, then switch to manual mode (and remember the slider position upon switching) change the slider position and click run, the slider will update correctly, then change the slider position back to the position which it had upon switching, click run again and you will get an error.

**Comment by ke-yu** [comment] 2015-09-05 16:05
@rverweij I'm still not able to reproduce. :-( but your crash report would be helpful to identify the problem. 
@monikaprabhu could you verify if it is reproducible?

**Comment by ikeough** [comment] 2016-05-04 21:45
We're closing this issue as it cannot be reproduced on more recent builds of Dynamo. Please re-open if you're still experiencing this problem, or have an example which reproduces the problem.

**Closed by ikeough** 2016-05-04 21:45 UTC
Labels: Bug, Waiting for feedback
