### ISSUE TITLE
Math.Abs error

### ISSUE THREAD

**Issue by vykrum** [DynamoDS/Dynamo#6778] opened 2016-06-23 16:01 UTC
## Dynamo version
1.0.1.1733

## Operating system
Windows 10

## What did you do? 
Incorrectly changed some variable names in a code block, which created a cyclic dependency. An error regarding the same comes up.

## What did you expect to see?
On rectifying the issue, I'd expected the error message to disappear. Instead, another message appears.
However on reopening the file, this error doesn't appear and the file works as expected.

## What did you see instead?
![error20160623-1](https://cloud.githubusercontent.com/assets/5621624/16310230/5f8c6694-3989-11e6-99a4-e6ede54b235c.png)

**Comment by ke-yu** [comment] 2016-06-24 03:44
hi @vykrum , what are values for `a` and `b`?

**Comment by vykrum** [comment] 2016-06-24 04:32
@ke-yu 
a= {4100,4100,4100,100,-1600};
b={0,4500};

However, I think the error is triggered when a variable name is repeated.

**Comment by ke-yu** [comment] 2016-06-24 06:08
cannot reproduce with this input :-(

**Comment by vykrum** [comment] 2016-06-24 06:34
Don't seem to be able to do so myself, either.
Will post steps, if and when I manage to.

**Comment by ikeough** [comment] 2016-06-29 16:45
Closing for now. Please re-open if you get a reproducible example.

**Closed by ikeough** 2016-06-29 16:45 UTC
Labels: Design Script
