### ISSUE TITLE
Middle mouse scrolling on node preview box freeze, and finally crash Dynamo.

### ISSUE THREAD

**Issue by kidasse** [DynamoDS/Dynamo#6570] opened 2016-05-03 13:29 UTC
## Dynamo version

Dynamo 1.0.0.1180
## Operating system

Windows 7
## What did you do?
1. Position the mouse pointer over the preview box below a node who contain one.
2. Scrolling only two notch on the whell in the up direction (a few more in the down) 
   with the middle mouse button.
   (see attached image.) 

![dynamo interface bug](https://cloud.githubusercontent.com/assets/19168660/14984560/9b5159a0-1143-11e6-9c1b-5032cd2af6e7.jpg)
## What did you expect to see?

Nothing
## What did you see instead?

Dynamo freeze and finally crash. 
no matter how many times I repeated the operation, Dynamo inevitably crash 
and this on several different computer.

**Comment by ikeough** [comment] 2016-05-03 18:34
@kidasse Can you please provide the contents of the message box that this shown when Dynamo crashes?

**Comment by kidasse** [comment] 2016-05-04 17:11
The content of the message box is:

La valeur ne peut pas être null.
Nom du paramètre : element

   à System.Windows.Media.VisualTreeHelper.GetParent(DependencyObject reference)
   à System.Windows.Controls.VirtualizingStackPanel.FindScrollOffset(Visual v)
   à System.Windows.Controls.VirtualizingStackPanel.OnAnchorOperation(Boolean isAnchorOperationPending)
   à System.Windows.Controls.VirtualizingStackPanel.SetAnchorInformation(Boolean isHorizontalOffset)
   à System.Windows.Controls.VirtualizingStackPanel.<>c__DisplayClassb.<InitializeViewport>b__7()
   à System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   à MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(Object source, Delegate method, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by jnealb** [comment] 2016-05-04 17:26
@kidasse @ikeough This does not crash here with a FR VM running Win10 - can you also provide details for your mouse and mouse driver? Also, if possible, can you temporarily set your Locale to United States in the Control Panel and see it still occurs? And finally, which version of Revit are you running on?

**Comment by tayday01** [comment] 2016-05-04 22:58
This is also happening to me. scrolling in a watch box.

Value cannot be null.
Parameter name: element

   at System.Windows.Media.VisualTreeHelper.GetParent(DependencyObject reference)
   at System.Windows.Controls.VirtualizingStackPanel.FindScrollOffset(Visual v)
   at System.Windows.Controls.VirtualizingStackPanel.OnAnchorOperation(Boolean isAnchorOperationPending)
   at System.Windows.Controls.VirtualizingStackPanel.SetAnchorInformation(Boolean isHorizontalOffset)
   at System.Windows.Controls.VirtualizingStackPanel.<AnchoredInvalidateMeasure>b__3()
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(Object source, Delegate method, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by mjkkirschner** [comment] 2016-05-04 22:59
@tayday01 are you using revit in another language from english?

**Comment by tayday01** [comment] 2016-05-04 22:59
No just english

**Comment by tayday01** [comment] 2016-05-04 23:04
Crashes revit 2014 2015 and 2016  running dynamo:

2016-04-29T03:18:16.000Z        82793685       DynamoInstall1.0.0.exe

**Comment by tayday01** [comment] 2016-05-05 00:11
also my list isn't null it has a long list of things, and it can be a list of anything. 
![crash](https://cloud.githubusercontent.com/assets/19196457/15032982/40cd0a46-121b-11e6-9fc2-573be8235328.jpg)

**Comment by tayday01** [comment] 2016-05-05 00:15
even this crashed it, just from scrolling

![crash2](https://cloud.githubusercontent.com/assets/19196457/15033034/ad2769a2-121b-11e6-8ffc-f05ecfe34e34.JPG)

**Comment by jnealb** [comment] 2016-05-06 15:40
@kidasse Can you please run the Dxdiag utility and send me its output as a file? neal.burnham@autodesk.com. Thanks.

**Comment by ikeough** [comment] 2016-05-06 16:02
@jnealb The stack track points to an exception in WPF. Specifically, the virtualizing panel used in the watch node. Google says:
http://connect.microsoft.com/VisualStudio/feedbackdetail/view/973860/argumentnullexception-in-virtualizingstackpanel

**Comment by jnealb** [comment] 2016-05-06 17:18
@ikeough Thanks @kidasse One more question: what was your upgrade\installation process to Dynamo 1.0, specifically what prior versions did you have installed, if any?

**Comment by jnealb** [comment] 2016-05-12 13:43
@kidasse Can you please disconnect your PS2 mouse and hook up a USB one and see if the issue persists? Thanks.

**Comment by kidasse** [comment] 2016-05-13 10:54
Hi,
One of the computers on which I tested has a usb mouse and the problem was
the same.

2016-05-12 15:43 GMT+02:00 Neal Burnham <notifications@github.com>:

**Comment by jnealb** [comment] 2016-05-13 13:25
@kidasse Is it possible for us to remote into your machine?

**Comment by kidasse** [comment] 2016-05-17 11:28
Hi,
I'm sorry @jnealb , but it's not possible because it's the office machine and external access  is unauthorized.

**Comment by jnealb** [comment] 2016-05-18 00:46
Hey @kidasse we do not quit that easily! Re-open.

**Comment by kidasse** [comment] 2016-05-20 17:59
Hi @jnealb,
I'm still here, but during my last post I clicked accidentally on the button "Close and comment".
Is that issue always open, and if not, how can i re-open it? 
Anyway i don't know how to help you more than that.
what do you suggest to go further in solving the problem?

**Comment by jnealb** [comment] 2016-05-24 20:10
@kidasse Can you send me a complete listing of your Programs and Features from the Control Panel?

**Comment by tayday01** [comment] 2016-06-08 15:32
Any luck with this? it is still plaguing me

**Comment by jnealb** [comment] 2016-06-08 15:35
@kidasse No, can you please send us your list of Programs and Features from the Control Panel?

**Comment by tayday01** [comment] 2016-08-11 16:18
Can this be re-opened?

**Comment by sharadkjaiswal** [comment] 2016-08-11 16:43
@tayday01 Are you able to reproduce this issue on the latest Dynamo 1.1?

**Comment by sharadkjaiswal** [comment] 2016-08-11 16:50
We are investigating this issue with tracking id MAGN-10542

**Comment by tayday01** [comment] 2016-08-11 17:50
Yes, Dynamo Version 1.1.0.2065, Revit 2015. I can try to produce an error report, although since it completely crashes everything sometimes the error report does not appear.

**Comment by smangarole** [comment] 2017-07-27 19:59
@kidasse @tayday01 I was not able to reproduce this issue with the latest Dynamo. Closing this issue.
Thanks.

**Closed by smangarole** 2017-07-27 19:59 UTC
Labels: Blocker, Bug, UI

**Comment by lxmfly123** [comment] 2018-03-09 10:49
I still have this issue in my windows 7.

**Comment by QilongTang** [comment] 2018-03-09 13:07
@smangarole What's the environment and Dynamo version you were using? 1.X?

**Comment by mjkkirschner** [comment] 2018-03-13 14:31
unfortunately this appears to be a bug in microsoft wpf framework code and appears fixed in .net 4.5.2 - we have not upgraded to target this framework version yet, though if you update your .net framework installed version you may find that the bug is fixed at runtime. I am not sure though.
