### ISSUE TITLE
Convex Hull

### ISSUE THREAD

**Issue by ekatzenstein** [DynamoDS/Dynamo#5194] opened 2015-08-27 21:46 UTC
This node is not working.  Is there a scheduled update?

**Comment by ikeough** [comment] 2015-08-27 22:14
The functionality is working in the daily builds:

![image](https://cloud.githubusercontent.com/assets/1139788/9534431/34a3de3e-4ccd-11e5-94d2-4e2f9725f702.png)

It's possible that a regression introduced before the release of 0.8.2 is causing this behavior. We've since [fixed that regression](https://github.com/DynamoDS/Dynamo/pull/5057), but the fix won't make it in until 0.8.3.

**Comment by ekatzenstein** [comment] 2015-08-27 22:19
I think the issue is that the convex hull is defaulting to be a 3D convex hull, even with planar points.  How about an overload? Planar points calculate 2D convex hull:

![2015-08-27_18-18-26](https://cloud.githubusercontent.com/assets/6820526/9534668/2bb6314e-4ce8-11e5-8ae7-ae753b94d380.png)

**Comment by andydandy74** [comment] 2015-08-29 06:42
Fwiw there's a 2D convex hull node in pkg Clockwork...

**Comment by ikeough** [comment] 2015-09-09 16:44
@ekatzenstein Yes, the 3D convex hull will not perform well with all planar points. You would need to have a 2D convex hull algorithm.

Can we close this issue?

**Comment by ekatzenstein** [comment] 2015-09-09 17:08
@andydandy74 thanks for letting me know!  I'll take a look.
@ikeough regarding convex hull in general, the output should be a polysurface (or set of polygons), rather than a set of lines.  These are conceptual topics rather than technical ones, so I'm fine with closing the issue.

**Closed** 2016-04-21 21:48 UTC
