### ISSUE TITLE
3D background preview goes away when I rename a node

### ISSUE THREAD

**Issue by ricardo7cordas** [DynamoDS/Dynamo#6948] opened 2016-07-27 18:36 UTC
## Dynamo version

1.1.0.2065
## Operating system

Windows 10 Pro
## What did you do?

When I rename a node and Dynamo runs, 3D Background is disappearing. Only when I resize the canvas is that it appears again. This is happening since the 0.9.2 version. Now with version 1.1 has just happened with the SandBox
## What did you expect to see?

That 3D background remains
## What did you see instead?

Blanck 3D background
![2016-07-27_15-16-27](https://cloud.githubusercontent.com/assets/14896455/17187503/e57c6614-540f-11e6-9aae-ca192d2824c7.gif)

**Comment by sharadkjaiswal** [comment] 2016-07-29 08:55
@jnealb, @monikaprabhu can we reproduce this consistently?

**Comment by ricardo7cordas** [comment] 2016-07-29 12:13
Yes. Every time I rename a node that happens. Only in Sandbox.

**Comment by ke-yu** [comment] 2016-08-02 06:18
I can't reproduce it, but I do notice that in some cases background preview was gone.

**Comment by ricardo7cordas** [comment] 2016-08-03 12:58
Seems like related to my VGA Port and Video Card. When I unplug and after re-plug the secondary monitor, Dynamo works fine. I try a lot of ways to solve that, but unsuccessfully.

**Comment by ricardo7cordas** [comment] 2016-08-03 13:01
When I disable NVIDEA driver, Dynamo works fine too. But Revit don't work. Anyway, it's a very boring bug.

**Comment by johnpierson** [comment] 2018-12-14 14:18
Closing as this issue is for an outdated version of Dynamo. If this persists in 2.0.x for you, please feel free to reopen and update accordingly.

**Closed by johnpierson** 2018-12-14 14:18 UTC
Labels: 1.x, needs more info
