### ISSUE TITLE
Tutorial won't start

### ISSUE THREAD

**Issue by hansbalerude** [DynamoDS/Dynamo#6851] opened 2016-07-07 09:10 UTC
If this issue is with Dynamo for Revit, please post your issue on the [Dynamo for Revit Issues page](https://github.com/DynamoDS/DynamoRevit/issues).

If this issue is **not** a bug report or improvement request, please check the [Dynamo forum](https://forum.dynamobim.com/), and start a thread there to discuss your issue.
## Dynamo version

1.0.0.1180
## Operating system

Win.7
## What did you do?

Start tutorial file from help-menu
## What did you expect to see?

Open tutorial.script
## What did you see instead?

Sad face smirking at me, telling me something went wrong. Bad puppy - bad puppy.

**Comment by ke-yu** [comment] 2016-07-13 00:10
@hansbalerude any more information? Did Dynamo crash?

**Comment by smangarole** [comment] 2017-06-19 19:03
Cannot reproduce in Dynamo Studio 1.3.0. Closing.

**Closed by smangarole** 2017-06-19 19:03 UTC
Labels: Bug, Waiting for feedback
