### ISSUE TITLE
If i take a look to a list in any function Revit and Dynamo stop working 

### ISSUE THREAD

**Issue by samykbs** [DynamoDS/Dynamo#6684] opened 2016-06-02 04:12 UTC
If this issue is with Dynamo for Revit, please post your issue on the [Dynamo for Revit Issues page](https://github.com/DynamoDS/DynamoRevit/issues).

If this issue is **not** a bug report or improvement request, please check the [Dynamo forum](https://forum.dynamobim.com/), and start a thread there to discuss your issue.
## Dynamo version 1.0

(Which version of Dynamo are you using? Go to Help > About if you're not sure.)
## Operating system

 Windows 7
## What did you do?

the software gets stuck 
## What did you expect to see?

The list of the function
## What did you see instead?

A few fragment from the list

**Comment by ke-yu** [comment] 2016-07-12 09:36
@samykbs please let me know if this is still reproducible or not. If the crash is still there, could you provide more details about what operations you did?

**Comment by smangarole** [comment] 2017-06-19 18:55
The issue has been waiting for feedback for almost a year. Closing due to this reason. Please reopen if this issue resurfaces.

**Closed by smangarole** 2017-06-19 18:55 UTC
Labels: Waiting for feedback
