### ISSUE TITLE
Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by GMcDowellJr** [DynamoDS/Dynamo#7703] opened 2017-03-10 22:47 UTC
If this issue is with Dynamo for Revit, please post your issue on the [Dynamo for Revit Issues page](https://github.com/DynamoDS/DynamoRevit/issues).

If this issue is **not** a bug report or improvement request, please check the [Dynamo forum](https://forum.dynamobim.com/), and start a thread there to discuss your issue.

## Dynamo version

1.2

## Operating system

Windows 7 Pro

## What did you do? 

Tried to run a graph designed to find and count all the tags, generic annotations, and text used in views on sheets and report them to a CSV file using UI++ to select the existing CSV.

## What did you expect to see?

Nothing but a crash. It takes a very long time to run through Dynamo and eats up most of my RAM. When I run through Dyno it uses significantly fewer resources.

## What did you see instead?

Object reference not set to an instance of an object.

   at ProtoCore.DSASM.Heap.RecursiveMark(StackValue root)
   at ProtoCore.DSASM.Heap.SingleStep(Boolean forceGC)
   at ProtoCore.DSASM.Executive.POP_helper(Instruction instruction, Int32& blockId, Int32& dimensions)
   at ProtoCore.DSASM.Executive.POP_Handler(Instruction instruction)
   at ProtoCore.DSASM.Executive.Execute(Int32 exeblock, Int32 entry, Language language)
   at ProtoCore.DSASM.Executive.Execute(Int32 exeblock, Int32 entry, List`1 breakpoints, Language language)
   at ProtoCore.DSASM.Interpreter.Run(Int32 codeblock, Int32 entry, Language lang, List`1 breakpoints)
   at ProtoCore.Lang.JILFunctionEndPoint.Execute(Context c, List`1 formalParameters, StackFrame stackFrame, RuntimeCore runtimeCore)
   at ProtoCore.CallSite.ExecWithZeroRI(List`1 functionEndPoint, Context c, List`1 formalParameters, StackFrame stackFrame, RuntimeCore runtimeCore, FunctionGroup funcGroup, SingleRunTraceData previousTraceData, SingleRunTraceData newTraceData)
   at ProtoCore.CallSite.Execute(List`1 functionEndPoint, Context c, List`1 formalParameters, List`1 replicationInstructions, StackFrame stackFrame, RuntimeCore runtimeCore, FunctionGroup funcGroup)
   at ProtoCore.CallSite.DispatchNew(Context context, List`1 arguments, List`1 partialReplicationGuides, DominantListStructure domintListStructure, StackFrame stackFrame, RuntimeCore runtimeCore)
   at ProtoCore.Lang.FunctionPointerEvaluator.Evaluate(List`1 args, StackFrame stackFrame)
   at ProtoCore.Lang.ArrayUtilsForBuiltIns.Evaluate(StackValue function, StackValue parameters, StackValue unpackParams, Interpreter runtime, StackFrame stackFrame)
   at ProtoCore.Lang.BuiltInFunctionEndPoint.Execute(Context c, List`1 formalParameters, StackFrame stackFrame, RuntimeCore runtimeCore)
   at ProtoCore.CallSite.ExecWithZeroRI(List`1 functionEndPoint, Context c, List`1 formalParameters, StackFrame stackFrame, RuntimeCore runtimeCore, FunctionGroup funcGroup, SingleRunTraceData previousTraceData, SingleRunTraceData newTraceData)
   at ProtoCore.CallSite.Execute(List`1 functionEndPoint, Context c, List`1 formalParameters, List`1 replicationInstructions, StackFrame stackFrame, RuntimeCore runtimeCore, FunctionGroup funcGroup)
   at ProtoCore.CallSite.DispatchNew(Context context, List`1 arguments, List`1 partialReplicationGuides, DominantListStructure domintListStructure, StackFrame stackFrame, RuntimeCore runtimeCore)
   at ProtoCore.CallSite.JILDispatch(List`1 arguments, List`1 replicationGuides, DominantListStructure domintListStructure, StackFrame stackFrame, RuntimeCore runtimeCore, Context context)
   at ProtoCore.DSASM.Executive.Callr(Int32 blockDeclId, Int32 functionIndex, Int32 classIndex, Boolean& explicitCall, Boolean isDynamicCall, Boolean hasDebugInfo)
   at ProtoCore.DSASM.Executive.CALLR_Handler(Instruction instruction)
   at ProtoCore.DSASM.Executive.Execute(Int32 exeblock, Int32 entry, Language language)
   at ProtoCore.DSASM.Executive.Execute(Int32 exeblock, Int32 entry, List`1 breakpoints, Language language)
   at ProtoCore.DSASM.Interpreter.Run(Int32 codeblock, Int32 entry, Language lang, List`1 breakpoints)
   at ProtoCore.Lang.JILFunctionEndPoint.Execute(Context c, List`1 formalParameters, StackFrame stackFrame, RuntimeCore runtimeCore)
   at ProtoCore.CallSite.ExecWithZeroRI(List`1 functionEndPoint, Context c, List`1 formalParameters, StackFrame stackFrame, RuntimeCore runtimeCore, FunctionGroup funcGroup, SingleRunTraceData previousTraceData, SingleRunTraceData newTraceData)
   at ProtoCore.CallSite.Execute(List`1 functionEndPoint, Context c, List`1 formalParameters, List`1 replicationInstructions, StackFrame stackFrame, RuntimeCore runtimeCore, FunctionGroup funcGroup)
   at ProtoCore.CallSite.DispatchNew(Context context, List`1 arguments, List`1 partialReplicationGuides, DominantListStructure domintListStructure, StackFrame stackFrame, RuntimeCore runtimeCore)
   at ProtoCore.Lang.FunctionPointerEvaluator.Evaluate(List`1 args, StackFrame stackFrame)
   at ProtoCore.Lang.ArrayUtilsForBuiltIns.Evaluate(StackValue function, StackValue parameters, StackValue unpackParams, Interpreter runtime, StackFrame stackFrame)
   at ProtoCore.Lang.BuiltInFunctionEndPoint.Execute(Context c, List`1 formalParameters, StackFrame stackFrame, RuntimeCore runtimeCore)
   at ProtoCore.CallSite.ExecWithZeroRI(List`1 functionEndPoint, Context c, List`1 formalParameters, StackFrame stackFrame, RuntimeCore runtimeCore, FunctionGroup funcGroup, SingleRunTraceData previousTraceData, SingleRunTraceData newTraceData)
   at ProtoCore.CallSite.Execute(List`1 functionEndPoint, Context c, List`1 formalParameters, List`1 replicationInstructions, StackFrame stackFrame, RuntimeCore runtimeCore, FunctionGroup funcGroup)
   at ProtoCore.CallSite.DispatchNew(Context context, List`1 arguments, List`1 partialReplicationGuides, DominantListStructure domintListStructure, StackFrame stackFrame, RuntimeCore runtimeCore)
   at ProtoCore.CallSite.JILDispatch(List`1 arguments, List`1 replicationGuides, DominantListStructure domintListStructure, StackFrame stackFrame, RuntimeCore runtimeCore, Context context)
   at ProtoCore.DSASM.Executive.Callr(Int32 blockDeclId, Int32 functionIndex, Int32 classIndex, Boolean& explicitCall, Boolean isDynamicCall, Boolean hasDebugInfo)
   at ProtoCore.DSASM.Executive.CALLR_Handler(Instruction instruction)
   at ProtoCore.DSASM.Executive.Execute(Int32 exeblock, Int32 entry, Language language)
   at ProtoCore.DSASM.Executive.Execute(Int32 exeblock, Int32 entry, List`1 breakpoints, Language language)
   at ProtoCore.DSASM.Executive.BounceUsingExecutive(Executive executive, Int32 exeblock, Int32 entry, StackFrame stackFrame, Int32 locals, Boolean fepRun, Executive exec, List`1 breakpoints)
   at ProtoScript.Runners.ProtoScriptRunner.ExecuteLive(Core core, RuntimeCore runtimeCore)
   at ProtoScript.Runners.LiveRunner.Execute(Boolean isCodeCompiled)
   at ProtoScript.Runners.LiveRunner.CompileAndExecute(List`1 astList)
   at ProtoScript.Runners.LiveRunner.CompileAndExecuteForDeltaExecution(List`1 astList)
   at ProtoScript.Runners.LiveRunner.SynchronizeInternal(GraphSyncData syncData)
   at ProtoScript.Runners.LiveRunner.UpdateGraph(GraphSyncData syncData)
   at Dynamo.Scheduler.UpdateGraphAsyncTask.HandleTaskExecutionCore()
   at Dynamo.Scheduler.AsyncTask.Execute()

**Comment by sixtysecondrevit** [comment] 2017-03-18 17:06
@GMcDowellJr, quick question. On the nodes for the  tags and text, do you have the background preview turned on? (Right Click on node > Disable geometry preview)

**Comment by GMcDowellJr** [comment] 2017-03-18 23:44
I did. For no good reason other than it's the default to have the preview on. Next time I get back to it I'll turn off all the previews (nothing to see in a preview anyway) and report back.


On Mar 18, 2017, 10:06 AM -0700, John <notifications@github.com>, wrote:

@GMcDowellJr<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_GMcDowellJr&d=DQMCaQ&c=euGZstcaTDllvimEN8b7jXrwqOf-v5A_CdpgnVfiiMM&r=O8vZipjtHO8UGKJfqEUaGVEUiWkT3JHNnVsrft9ZWio&m=q_sv-HqC_DsqyZCJs1WJwHxGMFoACbFEMmQKpZvHqB4&s=-VjZ4Qqv9qdSGLvrlSyHDHVqEN9fZ0atpPXzoESpA40&e=>, quick question. On the nodes for the tags and text, do you have the background preview turned on? (Right Click on node > Disable geometry preview)

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_DynamoDS_Dynamo_issues_7703-23issuecomment-2D287559807&d=DQMCaQ&c=euGZstcaTDllvimEN8b7jXrwqOf-v5A_CdpgnVfiiMM&r=O8vZipjtHO8UGKJfqEUaGVEUiWkT3JHNnVsrft9ZWio&m=q_sv-HqC_DsqyZCJs1WJwHxGMFoACbFEMmQKpZvHqB4&s=50b8Uik5f8it46I08D6OvBLKE_aZmS6h1giSlMGx8tc&e=>, or mute the thread<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AG-2D6ZekycQULFo-5FHTiN88xW3-2DbWRtsDoks5rnA8OgaJpZM4MZ9BT&d=DQMCaQ&c=euGZstcaTDllvimEN8b7jXrwqOf-v5A_CdpgnVfiiMM&r=O8vZipjtHO8UGKJfqEUaGVEUiWkT3JHNnVsrft9ZWio&m=q_sv-HqC_DsqyZCJs1WJwHxGMFoACbFEMmQKpZvHqB4&s=NwdBbp8_Gpw0m2dlgOLZewjFvWQfPAJVs3Z_9oIrd6I&e=>.




________________________________

This email has been scanned for spam and viruses by Proofpoint Essentials. Click here<https://us1.proofpointessentials.com/index01.php?mod_id=11&mod_option=logitem&mail_id=1489856785-7hL7F0-QqRcf&r_address=greg.mcdowell%40gouldevans.com&report=1> to report this email as spam.

**Comment by sixtysecondrevit** [comment] 2017-03-19 22:19
Cool, let us know if it helps. I noticed crashes since Dynamo 1.2.0 because the team added the ability to see the tags and text notes text in the background preview. If there are too many, it severely degrades performance. 
![image](https://cloud.githubusercontent.com/assets/15744724/24085340/dc9a64ba-0cbf-11e7-91d8-20bf2bbe5cf6.png)

**Comment by Racel** [comment] 2017-03-20 16:08
@sixtysecondrevit - Are you requesting a setting to turn off just text notes and tags?  Would it not be possible to just hide the preview for the specific tag or text nodes to improve performance? 

In general, I think adding a setting is a good idea, but I think that just adding it for tags/text notes brings into question why there aren't similar settings for other types of geometry. Right now, I don't think we have the bandwidth to introduce a feature that will allow users to globally set what types of geometry are shown in the background preview or not. In the future, this is definitely something we can look into, but in the short-term I am not sure if it will make it into the backlog as I would like to put a bit more thought into this that can be scalable for the future.

**Comment by GMcDowellJr** [comment] 2017-03-20 16:12
I think it would be better to default to no preview. So often I end up tuning off the preview for all the nodes in a graph and only enabling  them for specific outputs. I don’t need, for example, every XYX point in a sequence of operations, only the last one. Or perhaps, some nodes default on, others default off.

**Comment by sixtysecondrevit** [comment] 2017-03-20 16:22
@Racel I am not sure if it is necessary to allow this for all geometry, but a filter could be useful. I was mainly referencing the fact that the tags / text notes seem to cause a crash if the user forgets to disallow preview. Often times tags/ text notes can be 10s of thousands of items and it's easy to forget. :) I am curious if this mitigated @GMcDowellJr's problem though?

**Comment by Racel** [comment] 2017-03-20 16:27
@sixtysecondrevit - I see what you mean. This is a tricky problem... Well, let me ask you a different question that might lead to a different solution. Do you think we need the actual text visualization in the background preview of Dynamo? If not, maybe we can just add a simplified placeholder that doesn't require so much geoemtry to be rendered or just not render them at all in Dynamo.

**Comment by sixtysecondrevit** [comment] 2017-03-20 17:06
I'm not sure if removing is the answer. I would actually more access to them in the future. :) I think the preview is pretty amazing because it shows the curves of whatever font style you use! This could be amazing to convert custom fonts to filled regions for company logos and whatnot, (i fwe had access to the curves).
![image](https://cloud.githubusercontent.com/assets/15744724/24111800/3fb69b2a-0d5d-11e7-987c-e33ff3c40564.png)

**Comment by mjkkirschner** [comment] 2017-03-20 17:08
@Racel I think the solution is something like this:

turn off preview rendering of text notes, - instead use add element.geometry or textNote.Curves as a function to create these curves when desired.

**Comment by sixtysecondrevit** [comment] 2017-03-20 17:09
That sounds amazing.

**Comment by GMcDowellJr** [comment] 2017-03-20 17:21
@sixtysecondrevit - I'ts hit or miss. It crashed several times running it in Dyanmo. But when I ran it outside of Dynamo (through the Dyno Browser, for example) it worked although it did generate it's own error (that I never see in Dynamo).

![image](https://cloud.githubusercontent.com/assets/7322213/24111958/542f53c4-0d55-11e7-8bbf-65ef83c24e0b.png)

Turning off the preview DID save my RAM though!

One other thing that might be causing the issue. I'm running UI.MultipleInputForm ++ to specify an output path. If I freeze the node it runs through to completion. If the node is unfrozen, the graph crashes. 

BTW - Even with the preview on I never saw the text in the preview. Isn't there something about the preview not displaying if there's too much to show?

**Comment by Racel** [comment] 2017-03-20 17:48
@mjkkirschner - I wonder if something like that introduces more confusion into our visibility paradigms. Are you suggesting that we do this for all geometry? If we render some geometry but not others, it may be difficult for the user to figure out which objects they need to explicitly render...

I am worried about doing "one-of" things for specific types of nodes and not others. I think we should try and come up with a solution that can be consistent across all revit objects.

**Comment by mjkkirschner** [comment] 2017-03-20 17:48
well - text notes are not a geometry type. This is the strange one off.

**Comment by Racel** [comment] 2017-03-20 18:35
@mjkkirschner - Got it. We shouldn't be rendering these by default at all. Not sure why they are showing up in the background preview by default in the first place, then. @sixtysecondrevit or @GMcDowellJr would you mind filing a separate github issue for the fix? And assigning to me?

**Comment by mjkkirschner** [comment] 2017-03-20 18:58
They're showing up as @kronz and I thought it would be cool 😉 , and Max already had implemented it.

**Comment by Racel** [comment] 2017-03-20 19:16
ahhh....its so hard to be cool :smirk:

**Comment by jnealb** [comment] 2017-03-20 20:25
From MAGN-9085: "...This reproduces 100% and is related to the 9.0 and 9.1 change of having the Revit Background Preview turned ON by default." @mjkkirschner @Racel the background preview default ON, whether Revit or Dynamo's, should be re-designed for 2.0, as again and again we debug down reports of pathology to that root cause...Is that an uncool comment?

**Comment by ksobon** [comment] 2017-05-30 03:01
@jnealb sooooo uncool. :-) Actually I agree with @mjkkirschner here as the issue is really caused by all of the extra gymnastics that you guys did to get the text notes rendered in the background. I am not sure it was necessary. Perhaps there is a better way to do that, or we can do some extra error catching. 

I think preview should be on. We can kill it for multiple nodes at once by box selection and right click actions. It's all good that way.

**Comment by sixtysecondrevit** [comment] 2017-05-30 03:03
I would still love a node to access the curves from text elements. :)

**Comment by LukeyJohnson** [comment] 2017-08-21 12:19
I'm running Dynamo 1.2.1 on Revit 2015. With large lists and a big list.map operation, I face this same bug / dynamo crash. Here are the details:
`Object reference not set to an instance of an object.

   at ProtoCore.DSASM.Mirror.ExecutionMirror.GetStringValue(StackValue val, Heap heap, Int32 langblock, Int32 maxArraySize, Int32 maxOutputDepth, Boolean forPrint)
   at ProtoCore.DSASM.Mirror.ExecutionMirror.GetArrayTrace(StackValue svArray, Heap heap, Int32 langblock, HashSet`1 pointers, Boolean forPrint)
   at ProtoCore.DSASM.Mirror.ExecutionMirror.GetStringValue(StackValue val, Heap heap, Int32 langblock, Int32 maxArraySize, Int32 maxOutputDepth, Boolean forPrint)
   at ProtoCore.Utils.StringUtils.ConvertToString(StackValue sv, RuntimeCore runtimeCore, RuntimeMemory rmem)
   at ProtoCore.Lang.BuiltInFunctionEndPoint.Execute(Context c, List`1 formalParameters, StackFrame stackFrame, RuntimeCore runtimeCore)
   at ProtoCore.CallSite.ExecWithZeroRI(List`1 functionEndPoint, Context c, List`1 formalParameters, StackFrame stackFrame, RuntimeCore runtimeCore, FunctionGroup funcGroup, SingleRunTraceData previousTraceData, SingleRunTraceData newTraceData)
   at ProtoCore.CallSite.Execute(List`1 functionEndPoint, Context c, List`1 formalParameters, List`1 replicationInstructions, StackFrame stackFrame, RuntimeCore runtimeCore, FunctionGroup funcGroup)
   at ProtoCore.CallSite.DispatchNew(Context context, List`1 arguments, List`1 partialReplicationGuides, DominantListStructure domintListStructure, StackFrame stackFrame, RuntimeCore runtimeCore)
   at ProtoCore.DSASM.Executive.Callr(Int32 blockDeclId, Int32 functionIndex, Int32 classIndex, Boolean& explicitCall, Boolean isDynamicCall, Boolean hasDebugInfo)
   at ProtoCore.DSASM.Executive.CALLR_Handler(Instruction instruction)
   at ProtoCore.DSASM.Executive.Execute(Int32 exeblock, Int32 entry, Language language)
   at ProtoCore.DSASM.Executive.Execute(Int32 exeblock, Int32 entry, List`1 breakpoints, Language language)
   at ProtoCore.DSASM.Interpreter.Run(Int32 codeblock, Int32 entry, Language lang, List`1 breakpoints)
   at ProtoCore.Lang.JILFunctionEndPoint.Execute(Context c, List`1 formalParameters, StackFrame stackFrame, RuntimeCore runtimeCore)
   at ProtoCore.CallSite.ExecWithZeroRI(List`1 functionEndPoint, Context c, List`1 formalParameters, StackFrame stackFrame, RuntimeCore runtimeCore, FunctionGroup funcGroup, SingleRunTraceData previousTraceData, SingleRunTraceData newTraceData)
   at ProtoCore.CallSite.Execute(List`1 functionEndPoint, Context c, List`1 formalParameters, List`1 replicationInstructions, StackFrame stackFrame, RuntimeCore runtimeCore, FunctionGroup funcGroup)
   at ProtoCore.CallSite.DispatchNew(Context context, List`1 arguments, List`1 partialReplicationGuides, DominantListStructure domintListStructure, StackFrame stackFrame, RuntimeCore runtimeCore)
   at ProtoCore.Lang.FunctionPointerEvaluator.Evaluate(List`1 args, StackFrame stackFrame)
   at ProtoCore.Lang.ArrayUtilsForBuiltIns.Evaluate(StackValue function, StackValue parameters, StackValue unpackParams, Interpreter runtime, StackFrame stackFrame)
   at ProtoCore.Lang.BuiltInFunctionEndPoint.Execute(Context c, List`1 formalParameters, StackFrame stackFrame, RuntimeCore runtimeCore)
   at ProtoCore.CallSite.ExecWithZeroRI(List`1 functionEndPoint, Context c, List`1 formalParameters, StackFrame stackFrame, RuntimeCore runtimeCore, FunctionGroup funcGroup, SingleRunTraceData previousTraceData, SingleRunTraceData newTraceData)
   at ProtoCore.CallSite.Execute(List`1 functionEndPoint, Context c, List`1 formalParameters, List`1 replicationInstructions, StackFrame stackFrame, RuntimeCore runtimeCore, FunctionGroup funcGroup)
   at ProtoCore.CallSite.DispatchNew(Context context, List`1 arguments, List`1 partialReplicationGuides, DominantListStructure domintListStructure, StackFrame stackFrame, RuntimeCore runtimeCore)
   at ProtoCore.DSASM.Executive.Callr(Int32 blockDeclId, Int32 functionIndex, Int32 classIndex, Boolean& explicitCall, Boolean isDynamicCall, Boolean hasDebugInfo)
   at ProtoCore.DSASM.Executive.CALLR_Handler(Instruction instruction)
   at ProtoCore.DSASM.Executive.Execute(Int32 exeblock, Int32 entry, Language language)
   at ProtoCore.DSASM.Executive.Execute(Int32 exeblock, Int32 entry, List`1 breakpoints, Language language)
   at ProtoCore.DSASM.Executive.BounceUsingExecutive(Executive executive, Int32 exeblock, Int32 entry, StackFrame stackFrame, Int32 locals, Boolean fepRun, Executive exec, List`1 breakpoints)
   at ProtoScript.Runners.ProtoScriptRunner.ExecuteLive(Core core, RuntimeCore runtimeCore)
   at ProtoScript.Runners.LiveRunner.Execute(Boolean isCodeCompiled)
   at ProtoScript.Runners.LiveRunner.ApplyUpdate()
   at ProtoScript.Runners.LiveRunner.CompileAndExecuteForDeltaExecution(List`1 astList)
   at ProtoScript.Runners.LiveRunner.SynchronizeInternal(GraphSyncData syncData)
   at ProtoScript.Runners.LiveRunner.UpdateGraph(GraphSyncData syncData)
   at Dynamo.Scheduler.UpdateGraphAsyncTask.HandleTaskExecutionCore()
   at Dynamo.Scheduler.AsyncTask.Execute()`

**Comment by LukeyJohnson** [comment] 2017-08-21 12:21
I tried switching off some of the Previews, but I'm still seeing the bug, only with long lists (like about 3000 items or more). Once it hits some memory or performance limit, it seems to crash.

**Comment by dimven** [comment] 2017-08-22 12:28
I've experienced this too and actually reported it here:
https://github.com/DynamoDS/Dynamo/issues/7703

**Comment by Racel** [comment] 2017-08-25 13:37
As this is a Revit issue. Closing this task and linking it to [DynamoDS/DynamoRevit#1697](https://github.com/DynamoDS/DynamoRevit/issues/1697)

**Closed by Racel** 2017-08-25 13:37 UTC
