### ISSUE TITLE
Crash Report - 20160407

### ISSUE THREAD

**Issue by vykrum** [DynamoDS/Dynamo#6393] opened 2016-04-07 17:42 UTC
## Dynamo version

1.0.0.692
## Operating system

Windows 10
## What did you do?

Was trying to understand ScopeIf nodes and put two of them on a blank canvas and then added two code blocks to generate number ranges.
## What did you expect to see?

Didn't know what to expect. 
## What did you see instead?

First got a cyclic dependency error and on deleting the ScopeIf nodes ... a crash

Object reference not set to an instance of an object.

   at Dynamo.UI.Controls.PreviewControl.<>c__DisplayClassc.<RefreshExpandedDisplay>b__b(AsyncTask m)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at DynamoSandbox.Program.MakeStandaloneAndRun(String commandFilePath, DynamoViewModel& viewModel)
   at DynamoSandbox.Program.Main(String[] args)

**Comment by kronz** [comment] 2016-04-07 18:40
Thanks @vykrum .
You are adventurous.  The ScopeIf node is really best suited for doing some very specialized work inside of Custom nodes.  Check our my Fractal Tree node on the package manager.  We are going to make some adjustments to this in Dynamo 1.1, both in terms of functionality and documentation.  
fyi @ke-yu

**Comment by kronz** [comment] 2016-04-07 18:41
http://adsk-oss.myjetbrains.com/youtrack/issue/MAGN-9639

**Comment by jnealb** [comment] 2016-04-07 19:47
@kronz @ke-yu Could not reproduce - note that this stack is the well-known PB crash one, perhaps this is an edge case that still remains (MAGN-9750 etc)?

**Comment by smangarole** [comment] 2017-06-26 15:15
We are making language changes and looking at new alternatives to ScopeIf. Also, we are unable to reproduce this issue with the latest version of Dynamo. Closing for now. Please open a new issue if you can reproduce with Dynamo 1.3.0.

**Closed by smangarole** 2017-06-26 15:15 UTC
Labels: Blocker, Can't Reproduce, UI
