### ISSUE TITLE
BASICS FAILS: "IF" statement crops list.

### ISSUE THREAD

**Issue by petrkralik** [DynamoDS/Dynamo#6258] opened 2016-03-14 15:57 UTC
## Dynamo version

0.9.1.4054
## Operating system

Win8.1
## What did you do?

When you try to pass a list through "IF" statement it's trimmed to length of the shorten one.
In this example case is expected the "IF" passes whole list "A" with 4 rows. Only 2 rows were given instead because the "B" list has two rows (Has tried also with none and different number of rows).
![bug](https://cloud.githubusercontent.com/assets/17831717/13750059/31c0cb58-ea04-11e5-837c-0130cf0d7f7a.png)

Petr

**Comment by andydandy74** [comment] 2016-03-14 17:18
Yes, definitely very annoying.
As a workaround, you can use a code block like so:
```
seq[0] = list_true;
seq[1] = list_false;
seq[test ? 0 : 1];
```

**Comment by mjkkirschner** [comment] 2016-03-14 17:19
@Racel we have this tracked correct?
@kronz

**Comment by andydandy74** [comment] 2016-03-14 17:23
See discussion here: #4464

**Comment by mjkkirschner** [comment] 2016-03-14 17:25
@andydandy74 it's all coming back to me now...

**Comment by Racel** [comment] 2016-03-14 17:26
@mjkkirschner - We were tracking this, but after discussion with the team, this is not a bug but the intended behavior of the node. The "IF" node functions more of an "if iterator" than a true imperative if statement. For the behavior that @andydandy74 and @petrkralik are looking for, they should use "ScopeIf" or an imperative code block. 

This is very confusing from the user perspective. I think that we definitely need to fix this node and let people understand what is going on with it. I am thinking we should change "If" --> "If Iterator" and "ScopeIf" --> "If" or something similar. More help text would also be useful.

**Comment by Racel** [comment] 2016-03-14 17:27
The behavior was changed after 0.8.0, so the node functions differently in 0.8.0 and newer versions...

**Comment by kronz** [comment] 2016-03-14 17:28
it is my understanding that it replicates on all nodes AS THOUGH SET TO SHORTEST.  So this makea a little more sense with these attached examples, especially when looking at what the results are when LONGEST is applied to a formula node and the "short" branch of the conditional is passes through.  These changes were also made to allow predictable behavior when using single boolean inputs or a list of booleans. 
![2016-02-23_2240](https://cloud.githubusercontent.com/assets/3456818/13753233/84c04d5e-e9e8-11e5-846c-de4bb23c0235.png)

**Comment by Racel** [comment] 2016-03-14 17:59
@petrkralik @andydandy74 - Using "ScopeIf" with the first example:

![image](https://cloud.githubusercontent.com/assets/2551261/13754321/ed300e52-e9ec-11e5-8eae-6664957f439b.png)

**Comment by petrkralik** [comment] 2016-03-15 07:42
Thank all of you for releveant'n quick responses and clear examples . Petr

**Comment by andydandy74** [comment] 2016-03-18 10:37
This may not be the case in later versions, but in Dynamo 0.9.0 ```ScopeIf``` does not play well in larger graphs causing most of the nodes to return ```null```, hence my workaround. I never investigated this in-depth, but I stumbled across it today again.

**Comment by Racel** [comment] 2016-03-18 12:00
hi @andydandy74 - You are right that ScopeIf acts strangely, and it still does this in the 0.9.1 stable release.

@ke-yu has been looking into this and has found the following:

> When a node is connected to ScopeIF inputs and connected to another node at the same time, potentially there will be implicit cyclic dependency in different language blocks

The result is the null values you are seeing. The safest bet is to not connect any upstream node to both branches and to not connect it to any other node that is not the upstream node of ScopeIF node.

We are actively looking into it and you could see one or more of the following in future releases: better description/tooltips for the If node, a new If node that doesn't replicate, new lacing options on the If node...to name a few things we are thinking about.

**Comment by mjkkirschner** [comment] 2022-02-05 04:56
now that the new if node is merged I think this can be closed.
https://github.com/DynamoDS/Dynamo/pull/11728

**Closed by mjkkirschner** 2022-02-05 04:56 UTC
Labels: bug, Major, tracked
