### ISSUE TITLE
Code Block Error

### ISSUE THREAD

**Issue by BrettCTaylor** [DynamoDS/Dynamo#7248] opened 2016-10-05 23:52 UTC
## Dynamo version

1.2.0.2690
## Operating system

Windows 10
## What did you do?

When opening up a dynamo script written in version 1.1 I obtained an error with one of my code blocks. The code block was creating a folder path from two strings and was putting a backslash "\" between the two strings. 

Below is a simple test file that I created showing the problem. When I put the backslash as a string input as a variable I don't get an error.

The Error message is "Error: EOF Expected"

![image](https://cloud.githubusercontent.com/assets/18408513/19135719/2b2555b4-8baa-11e6-9e97-5513e9eac4af.png)

**Comment by dimven** [comment] 2016-10-06 00:55
This is kind of supposed to fail because backslash is an escape character in C languages and usually you ave to double it up. Unfortunately, I experienced a similar problem, where "\\" is failing (and it was working before). The only way I could feed in a backslash character was by using single quotes like so '\'

![dynamosandbox_2016-10-06_08-54-19](https://cloud.githubusercontent.com/assets/7148394/19136895/89efb7c2-8ba2-11e6-89dc-4c1bb6dbb02e.png)

**Comment by ke-yu** [comment] 2016-10-06 02:30
@samuelcwl is this a regression?

**Comment by ke-yu** [comment] 2016-10-10 02:50
@dimven @BrettCTaylor PR #7255 to fix the issue.

**Comment by riteshchandawar** [comment] 2017-01-17 04:12
As this has been fixed and already working, I am closing this issue.

**Closed by riteshchandawar** 2017-01-17 04:12 UTC
