### ISSUE TITLE
Copy nodes between graphs?

### ISSUE THREAD

**Issue by kehehee1** [DynamoDS/Dynamo#7517] opened 2017-01-17 09:42 UTC
## Dynamo version
2.0

## Operating system
Windows 7

## What did you expect to see?
It will be more convenient if Dynamo support copy nodes between graphs.

**Comment by josols** [comment] 2017-01-21 16:55
Ctrl+C, close graph, open new, ctrl+V? Works for me.

**Comment by riteshchandawar** [comment] 2017-01-23 06:30
@kehehee1 In which scenario you want to use this? Are you expecting copy from one session of Dynamo to another session of Dynamo? 

Right now you can copy from Custom Node Workspace to Home Workspace and vice-versa, also you can copy from current how workspace to the newly opened workspace (by closing current, as suggested by @josols ).

**Comment by ramramps** [comment] 2017-10-30 18:28
@kehehee1 Did you try the above steps? Please re-open if this is an issue. 
Also, please provide some steps to reproduce this issue.

**Closed by ramramps** 2017-10-30 18:28 UTC
