### ISSUE TITLE
Crash report from Dynamo 2.3.0.5885

### ISSUE THREAD

**Issue by LuisaCPBR** [DynamoDS/Dynamo#10641] opened 2020-05-12 12:55 UTC
# Issue Description
Please fill in the following information to help us reproduce the issue:

### What did you do?
I was trying to run a (very heavy) routine inside Dynamo, using my remote access.

### What did you expect to see?
I hoped it would take maybe a couple of minutes, but it would run

### What did you see instead?
Dynamo crashed :/

### What packages or external references (if any) were used?
Data-Shapes v.2019.2.42
archilab v.2020.23.10
Rhythm v.2020.2.13
Chynamo v.0.8.5
GeniusLoci v.2019.9.4
Clockwork v.2.3.0
Zebra v.2016.7.2
Orchid
   v. 203.1.2.7323
Modelical v.2.2.15
VZ (this one is made by me, uses basically OOTB nodes and are quite simple nodes)

### Stack Trace
```
Index was outside the bounds of the array.

   at ProtoCore.DSASM.Executive.GetProcedureNode(Int32 blockId, Int32 classIndex, Int32 functionIndex)
   at ProtoCore.DSASM.Executive.UpdateMethodDependencyGraph(Int32 entry, Int32 procIndex, Int32 classIndex)
   at ProtoCore.DSASM.Executive.SetupExecutive(Int32 exeblock, Int32 entry)
   at ProtoCore.DSASM.Executive.Execute(Int32 exeblock, Int32 entry, Language language)
   at ProtoCore.DSASM.Executive.Execute(Int32 exeblock, Int32 entry, List`1 breakpoints, Language language)
   at ProtoCore.DSASM.Executive.BounceUsingExecutive(Executive executive, Int32 exeblock, Int32 entry, StackFrame stackFrame, Int32 locals, Boolean fepRun, Executive exec, List`1 breakpoints)
   at ProtoScript.Runners.ProtoScriptRunner.ExecuteLive(Core core, RuntimeCore runtimeCore)
   at ProtoScript.Runners.LiveRunner.Execute(Boolean isCodeCompiled)
   at ProtoScript.Runners.LiveRunner.CompileAndExecute(List`1 astList)
   at ProtoScript.Runners.LiveRunner.CompileAndExecuteForDeltaExecution(List`1 astList)
   at ProtoScript.Runners.LiveRunner.SynchronizeInternal(GraphSyncData syncData)
   at ProtoScript.Runners.LiveRunner.UpdateGraph(GraphSyncData syncData)
   at Dynamo.Scheduler.UpdateGraphAsyncTask.HandleTaskExecutionCore()
   at Dynamo.Scheduler.AsyncTask.Execute()
```

---
OS: `Microsoft Windows NT 10.0.18362.0`
CLR: `4.0.30319.42000`
Dynamo: `2.3.0.5885`

**Comment by Amoursol** [comment] 2020-05-15 18:06
Hello @LuisaCPBR - Would it be possible for you to attach the DYN, or a mock-up of the kind of thing you are trying to achieve? (i.e the 'Very heavy' routine). This will help us get to the bottom of the crash report faster 😊

**Comment by LuisaCPBR** [comment] 2020-05-18 18:11
Hello @Amoursol Yes, Here it goes
![bug](https://user-images.githubusercontent.com/60219049/82245695-d2e9ef00-9919-11ea-98f4-64fe0580ecff.png)

**Comment by LuisaCPBR** [comment] 2020-05-18 18:13
(It says "We dont support that file type when I try to attach .dyn")

**Comment by Amoursol** [comment] 2020-05-18 20:11
@LuisaCPBR - Can you try **zipping** the Dynamo file and uploading 😊 ?

**Comment by LuisaCPBR** [comment] 2020-05-19 15:35
It's not accepting my .rar (I just have the program to compress at .rar, it doesn't make .zip). Could you give me a mail or so?

**Comment by Amoursol** [comment] 2020-05-19 15:54
Hello @LuisaCPBR - Apologies for the trouble! Please send on to sol.amour@autodesk.com

**Comment by LuisaCPBR** [comment] 2020-05-21 09:01
No problem, just sent ;)

**Comment by aparajit-pratap** [comment] 2022-02-03 05:00
@LuisaCPBR, unfortunately, we have been unable to reproduce the crash. We might need more information from you in order to reproduce it. Would you be able to share the Revit project file as well? Also, could you share the following packages as these are not available on the Dynamo package manager:
1. Danimo
2. VZ

Thank you!

**Comment by aparajit-pratap** [comment] 2022-02-03 17:22
@LuisaCPBR I got a hold of the revit file from the team and was still unable to reproduce the crash but I got this error from a Rhythm node:
![image](https://user-images.githubusercontent.com/5710686/152394910-e8418360-91a7-4413-95a2-384228009dea.png)

Perhaps @johnpierson would know what could be wrong with the node or graph. Due to the error, the node returns all null values and so we cannot debug the graph further beyond this point.

**Comment by aparajit-pratap** [comment] 2022-02-03 17:23
Btw, I'm testing this on Dynamo version 2.10.1.

**Comment by aparajit-pratap** [comment] 2022-02-04 14:33
@LuisaCPBR let us know if you can provide these packages to us: Danimo, VZ. Also, if you have suggestions on how to make the graph run - see my question above. If not, we will close this issue as not reproducible. Thanks.

**Comment by LuisaCPBR** [comment] 2022-02-04 17:25
Hello @aparajit-pratap and @johnpierson and sorry for the late answer

I’m afraid we will have to close as not reproducible: the “VZ” package was the package of the company I worked for at that time, and If I’m not mistaken It have never published to open use, so I no longer have it

thanks for the effort thought! :)

**Closed** 2022-02-07 01:11 UTC
Labels: crash, tracked
