### ISSUE TITLE
select model element(s) not working in 0.7.6

### ISSUE THREAD

**Issue by epeter-** [DynamoDS/Dynamo#3727] opened 2015-02-10 14:04 UTC

**Comment by rlwade86** [comment] 2015-02-11 19:26
I am having the same issue

**Comment by jnealb** [comment] 2015-02-11 19:32
@epeter- @rlwade86 Which version of Revit are you running? Can you provide a dyn? Thanks.

**Comment by rlwade86** [comment] 2015-02-11 19:35
I tested it on both 2014 and 2015.  The dyn I was using was from a previous build.  One that Zack helped me write.

Robert L. Wade, AIA, NCARB, LEED
ASSOCIATE PRINCIPAL

POPULOUS
300 Wyandotte | Suite 200
Kansas City, Missouri 64105 | USA
Main: +1 816 221 1500 | Fax: +1 816 221 1578
Direct: +1 816 329 4425
Cell: +1 816 916 3867
robert.wade@populous.com<mailto:robert.wade@populous.com>
www.populous.com<http://www.populous.com/>

**Comment by jnealb** [comment] 2015-02-11 19:41
@rlwade86 Thanks, will follow up with Zack.

**Comment by rlwade86** [comment] 2015-02-11 19:41
The new build looks pretty cool!


Robert L. Wade, AIA, NCARB, LEED
ASSOCIATE PRINCIPAL

POPULOUS
300 Wyandotte | Suite 200
Kansas City, Missouri 64105 | USA
Main: +1 816 221 1500 | Fax: +1 816 221 1578
Direct: +1 816 329 4425
Cell: +1 816 916 3867
robert.wade@populous.com<mailto:robert.wade@populous.com>
www.populous.com<http://www.populous.com/>

**Comment by kronz** [comment] 2015-02-11 22:40
@epeter- @rlwade86  can you say a little more about what you are seeing? 
- Are the Select buttons not working or not available in the UI?
- Is there an error showing in the canvas?
- Is there an error in the console (like startup of Dynamo)?
- are there any other nodes that are missing
can you say if there is anything particular about your workstations or Revit installations?  
Unusual addins?

**Comment by rlwade86** [comment] 2015-02-11 22:46
·         They are not available in the UI

·         No error showing

·         No

·         I didn’t see any other nodes that are missing but I didn’t test it too much.

·         Workstation is a typical Dell Laptop 4800

·         I have the 2015 Design Suite installed

·         Lots of addins.  I am testing optional rendering engines right now.  Lumion, Twin Motion, Octane and Indigo



Robert L. Wade, AIA, NCARB, LEED
ASSOCIATE PRINCIPAL

POPULOUS
300 Wyandotte | Suite 200
Kansas City, Missouri 64105 | USA
Main: +1 816 221 1500 | Fax: +1 816 221 1578
Direct: +1 816 329 4425
Cell: +1 816 916 3867
robert.wade@populous.com<mailto:robert.wade@populous.com>
www.populous.com<http://www.populous.com/>

**Comment by epeter-** [comment] 2015-02-12 07:08
buttons will not activate. meaning no selection possible

Am 11.02.2015 um 23:41 schrieb Zach Kron:
>
> @epeter- <https://github.com/epeter-> @rlwade86 
> <https://github.com/rlwade86> can you say a little more about what you 
> are seeing?
>
>   * Are the Select buttons not working or not available in the UI?
>   * Is there an error showing in the canvas?
>   * Is there an error in the console (like startup of Dynamo)?
>   * are there any other nodes that are missing can you say if there is
>     anything particular about your workstations or Revit installations?
>     Unusual addins?
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/DynamoDS/Dynamo/issues/3727#issuecomment-73980810>.
>



---
Diese E-Mail wurde von Avast Antivirus-Software auf Viren geprüft.
http://www.avast.com

**Comment by jnealb** [comment] 2015-02-12 16:23
@epeter- @rlwade86 Can we ask you to uninstall Dynamo from the Control Panel and delete the Dynamo 0.7 folder from Program Files? Then re-install and try Select Model Element again? We are unable to reproduce this on our end, and we want to debug it. Also, have you made any changes to your Revit installs recently?

**Comment by rlwade86** [comment] 2015-02-12 18:47
That was the first thing I did.  I uninstalled and everything and searched my entire C: drive for all Dynamo files and deleted them.  Then rebooted and reinstalled and same the result.  The only thing that I did not do was go into the registry and clear things out there.

I haven’t made any changes to the revit install.  I don’t think I.T. has either.

Robert L. Wade, AIA, NCARB, LEED
ASSOCIATE PRINCIPAL

POPULOUS
300 Wyandotte | Suite 200
Kansas City, Missouri 64105 | USA
Main: +1 816 221 1500 | Fax: +1 816 221 1578
Direct: +1 816 329 4425
Cell: +1 816 916 3867
robert.wade@populous.com<mailto:robert.wade@populous.com>
www.populous.com<http://www.populous.com/>

**Comment by jnealb** [comment] 2015-02-12 19:47
@rlwade86 @epeter- Can you send me the Revit_2015 and Revit_2014 folders (zipped) that are installed under the Dynamo 0.7 folder? My email is neal.burnham@autodesk.com.

**Comment by rlwade86** [comment] 2015-02-12 19:52
The entire folders?

Robert L. Wade, AIA, NCARB, LEED
ASSOCIATE PRINCIPAL

POPULOUS
300 Wyandotte | Suite 200
Kansas City, Missouri 64105 | USA
Main: +1 816 221 1500 | Fax: +1 816 221 1578
Direct: +1 816 329 4425
Cell: +1 816 916 3867
robert.wade@populous.com<mailto:robert.wade@populous.com>
www.populous.com<http://www.populous.com/>

**Comment by jnealb** [comment] 2015-02-12 20:15
@rlwade86 Yes

**Comment by epeter-** [comment] 2015-02-12 20:28
guys, i tried to install every build of dynamo after 20141222. every 
install since then had a non working select model(s) node.
even removing all directories containing dynamo files wouldn't solve the 
problem.
right now i am back to 2014 12 22 build
(even last nights build produces the same error)
regards

Am 12.02.2015 um 17:23 schrieb Neal Burnham:
>
> @epeter- <https://github.com/epeter-> @rlwade86 
> <https://github.com/rlwade86> Can we ask you to uninstall Dynamo from 
> the Control Panel and delete the Dynamo 0.7 folder from Program Files? 
> Then re-install and try Select Model Element again? We are unable to 
> reproduce this on our end, and we want to debug it. Also, have you 
> made any changes to your Revit installs recently?
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/DynamoDS/Dynamo/issues/3727#issuecomment-74100619>.
>



---
Diese E-Mail wurde von Avast Antivirus-Software auf Viren geprüft.
http://www.avast.com

**Comment by rlwade86** [comment] 2015-02-12 21:57
I had to roll it back to get some work done.  Do you want me reinstall it.

Robert L. Wade, AIA, NCARB, LEED
ASSOCIATE PRINCIPAL

POPULOUS
300 Wyandotte | Suite 200
Kansas City, Missouri 64105 | USA
Main: +1 816 221 1500 | Fax: +1 816 221 1578
Direct: +1 816 329 4425
Cell: +1 816 916 3867
robert.wade@populous.com<mailto:robert.wade@populous.com>
www.populous.com<http://www.populous.com/>

**Comment by jnealb** [comment] 2015-02-13 05:58
@rlwade86 So it works with 7.5 from 20141222? Yes, re-install the latest 7.6 please (remove the Dynamo 0.7 folder first) and send me the Revit folders.

**Comment by epeter-** [comment] 2015-02-15 09:44
fully removed the older build, reinstalled; noc change in behaviour. model element(s) are non functional

**Comment by jnealb** [comment] 2015-02-15 21:03
@epeter- Can you confirm that is was working with 7.5? Thanks.

**Comment by epeter-** [comment] 2015-02-16 08:21
definitely. still running dailybuild from 20141222T21xx
regards peter

Am 15.02.2015 um 22:03 schrieb Neal Burnham:
>
> @epeter- <https://github.com/epeter-> Can you confirm that is was 
> working with 7.5? Thanks.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/DynamoDS/Dynamo/issues/3727#issuecomment-74436858>.
>



---
Diese E-Mail wurde von Avast Antivirus-Software auf Viren geprüft.
http://www.avast.com

**Comment by rlwade86** [comment] 2015-02-16 15:48
Yes it is.

Robert L. Wade, AIA, NCARB, LEED
ASSOCIATE PRINCIPAL

POPULOUS
300 Wyandotte | Suite 200
Kansas City, Missouri 64105 | USA
Main: +1 816 221 1500 | Fax: +1 816 221 1578
Direct: +1 816 329 4425
Cell: +1 816 916 3867
robert.wade@populous.com<mailto:robert.wade@populous.com>
www.populous.com<http://www.populous.com/>

**Comment by jnealb** [comment] 2015-02-17 15:47
@epeter- @rlwade86 @RodRecker @kronz @ikeough We can reproduce this with French Windows and Dynamo 7.6. Thanks for your help.

**Comment by rlwade86** [comment] 2015-02-17 19:11
Is there a fix for it or should I go back to 7.5 for now?

Robert L. Wade, AIA, NCARB, LEED
ASSOCIATE PRINCIPAL

POPULOUS
300 Wyandotte | Suite 200
Kansas City, Missouri 64105 | USA
Main: +1 816 221 1500 | Fax: +1 816 221 1578
Direct: +1 816 329 4425
Cell: +1 816 916 3867
robert.wade@populous.com<mailto:robert.wade@populous.com>
www.populous.com<http://www.populous.com/>

**Comment by RodRecker** [comment] 2015-02-17 19:23
I asked for fast action on this one because we want as many people as possible testing on the daily builds.

Ian just submitted a fix for review. Once it is merged, a new build should be ready in a few hours following our test automation.

So I would expect that by tomorrow we should have a build that contains the fix.

**Comment by RodRecker** [comment] 2015-02-18 00:06
Build is posted now - please give the latest daily a try.
http://dyn-builds-data.s3-us-west-2.amazonaws.com/DynamoInstall0.7.6.20150217T1558.exe

**Comment by rlwade86** [comment] 2015-02-18 16:27
It works now!  For some reason I get an error when I install it that says it cannot rename a file.  I had to uninstall / delete all files and then install it to get it to work.

Thanks for the help,

It looks great!

Robert L. Wade, AIA, NCARB, LEED
ASSOCIATE PRINCIPAL

POPULOUS
300 Wyandotte | Suite 200
Kansas City, Missouri 64105 | USA
Main: +1 816 221 1500 | Fax: +1 816 221 1578
Direct: +1 816 329 4425
Cell: +1 816 916 3867
robert.wade@populous.com<mailto:robert.wade@populous.com>
www.populous.com<http://www.populous.com/>

**Comment by jnealb** [comment] 2015-02-18 16:44
@rlwade86 Thanks for the update - btw: are you running non-English Windows by any chance?

**Comment by rlwade86** [comment] 2015-02-18 16:49
no

Robert L. Wade, AIA, NCARB, LEED
ASSOCIATE PRINCIPAL

POPULOUS
300 Wyandotte | Suite 200
Kansas City, Missouri 64105 | USA
Main: +1 816 221 1500 | Fax: +1 816 221 1578
Direct: +1 816 329 4425
Cell: +1 816 916 3867
robert.wade@populous.com<mailto:robert.wade@populous.com>
www.populous.com<http://www.populous.com/>

**Comment by jnealb** [comment] 2015-02-18 18:23
@rlwade86 @RodRecker @ikeough Thanks for the information - one more question: is your Revit also English?

**Comment by rlwade86** [comment] 2015-02-18 19:57
Yes

Robert L. Wade, AIA, NCARB, LEED
ASSOCIATE PRINCIPAL

POPULOUS
300 Wyandotte | Suite 200
Kansas City, Missouri 64105 | USA
Main: +1 816 221 1500 | Fax: +1 816 221 1578
Direct: +1 816 329 4425
Cell: +1 816 916 3867
robert.wade@populous.com<mailto:robert.wade@populous.com>
www.populous.com<http://www.populous.com/>

**Comment by ksobon** [comment] 2017-05-30 00:50
@kronz I doubt this is still an issue. Can we ask for final feedback, wait a week and close?

**Comment by kronz** [comment] 2017-05-30 19:31
Closing.  If an issue like this shows up, it is likely from a different cause at this point and should get a new bug

**Closed by kronz** 2017-05-30 19:31 UTC
Labels: Bug, Revit
