### ISSUE TITLE
File Path node Causes Dynamo 1.0 to Crash in Revit 2015/16

### ISSUE THREAD

**Issue by archinate** [DynamoDS/Dynamo#6556] opened 2016-05-01 05:42 UTC
## Dynamo version

Dynamo -- Build 1.0.0.1180 on Revit 2016 and 2015

## Operating system

Windows 10

## What did you do? 

Placed File Path node on canvas > clicked browse > selected file

## What did you expect to see?

File to be selected in Dynamo node as usual.

## What did you see instead?

Dynamo crashes.

Object reference not set to an instance of an object.

   at DSCore.File.FilenameNodeViewCustomization.readFileButton_Click(Object sender, RoutedEventArgs e)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.Controls.Primitives.ButtonBase.OnClick()
   at System.Windows.Controls.Button.OnClick()
   at System.Windows.Controls.Primitives.ButtonBase.OnMouseLeftButtonUp(MouseButtonEventArgs e)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.ReRaiseEventAs(DependencyObject sender, RoutedEventArgs args, RoutedEvent newEvent)
   at System.Windows.UIElement.OnMouseUpThunk(Object sender, MouseButtonEventArgs e)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
   at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by archinate** [comment] 2016-05-01 05:55
The issue with the File Path node is happening in both 2015 and 2016.  2017 seems to work without issue.  DynamoSandbox.exe also works.

**Comment by kronz** [comment] 2016-05-01 14:09
@jnealb looks like the thing we were having a hard time reproducing.  
@archinate anything special about the situation or is it generic for anything using filepath in 2015 and 2016 Revit?

**Comment by archinate** [comment] 2016-05-01 14:16
Hey @kronz and @jnealb 
Nothing special about the setup. I even tested it with a new file with only the File Path component in both Revit 2015 and 2016. It also appears that the Directory tool has the same issue.

-Nate

**Comment by kronz** [comment] 2016-05-02 01:28
@jnealb can you try this out in Win 10?  I can't reproduce in Revit 2016 with Win 8.

**Comment by jnealb** [comment] 2016-05-02 12:47
@kronz Investigating

**Comment by archinate** [comment] 2016-05-02 13:40
@jnealb and @kronz I did a little more testing on a fresh machine that has similar configurations. Dynamo 1.0 ran as expected after a fresh install of Revit 2015/16.  

On the machine that was giving me trouble, I cleared out my addins folder and Dynamo 1.0 is now running!  I'm going to track down what addin might be giving Dynamo 1.0 some trouble. This also seems to related to #6565 since that is working after removing my addins.

**Comment by jnealb** [comment] 2016-05-02 13:44
@archinate Thanks for the debugging.

**Comment by archinate** [comment] 2016-05-02 15:22
@jnealb @kronz I think I found the addin that is causing the issue  It's a custom app that involves a Revit dockable interface and involves some web requests.It has no dependencies on Dynamo so it is strange that it causing an issue.  To my knowledge the addin did not conflict with Dynamo until this more recent version.  

Can I send along private link to you so you can see if you can reproduce?

-Nate

**Comment by kronz** [comment] 2016-05-02 16:03
@archinate yes please.  Thanks!

**Comment by jnealb** [comment] 2016-05-02 16:34
neal.burnham@autodesk.com

**Comment by archinate** [comment] 2016-05-02 17:03
@kronz @jnealb sent!

**Comment by kronz** [comment] 2016-05-02 17:42
thanks @archinate I installed your addin, but a) I don't see it showing up in the r2016 interface (should it just be a tool in the addin tab?) and b) no change to my filepath behavior.  Seems like maybe the installer didn't take?

**Comment by kronz** [comment] 2016-05-02 18:02
Some recent changes to how file path node works can be seen here:
https://github.com/DynamoDS/Dynamo/commit/fe2747501285c11f010767285ccfedd3724087fd
@sharadkjaiswal can offer any opinions on what @archinate is seeing?

**Comment by jnealb** [comment] 2016-05-02 19:09
@archinate @kronz We can reproduce this in-house: occurs with the Dynamo 1.0 Addin for Revit 2016 but not Revit 2017, and is unrelated to the aforementioned Trello Addin.

**Comment by kronz** [comment] 2016-05-02 19:43
@archinate @jnealb However, this is not 100% reproducable. It doesn' happen at all on my machine (win 8, r2016 and r2017 installed, Dynamo 0.8.2, 0.9.2, and 1.0 installed)

**Comment by archinate** [comment] 2016-05-03 02:14
@kronz hmm... did the installer throw any errors? It copies files to C:\Proving Ground\Trello and %appdata%\Autodesk\Revit\Addins\2016 for users

**Comment by archinate** [comment] 2016-05-03 02:19
@kronz and @jnealb regardless, for me it appears that removing this particular addin  causes the file path node to work AND it fixes the issue I was having with Publishing Versions (issue #6565)... but I have no idea why since everything lived in harmony before.

**Comment by sharadkjaiswal** [comment] 2016-05-03 03:24
I am not able to reproduce this on my Windows 10 setup. @jnealb, which are the addins, installed on the system? Can you please test the scenario by removing all the addin files from %appdata%\Autodesk\Revit\Addoms\2016?

**Comment by jnealb** [comment] 2016-05-03 12:11
@sharadkjaiswal You are correct - (my testing is on Win7) the ProvingGround.TrelloRevit.2016 Addin is implicated (I misspoke earlier): if I remove it from the Addin folder there is no issue. Uninstalling it from the Control Panel had not removed it from the Addin folder. When it is present in the Addin folder the crash occurs, as reported by Nathan. The Addin can be found at: http://provingground-trello.s3-website-us-east-1.amazonaws.com/ProvingGround.Trello.Installer.application.

**Comment by archinate** [comment] 2016-05-03 13:04
@jnealb Hey Neal, can you remove the add-in link? I shared it privately over e-mail because I didn't intend to have the installer/tool made available on a public forum since it is still a very early alpha. You may share internally among the Dynamo team if it helps with finding what may be causing the issue.

Thanks, -Nate

**Comment by sharadkjaiswal** [comment] 2016-05-04 02:20
@archinate there seems to be a version mismatch of RestSharp.dll. Dynamo uses version 105.2.3.0 whereas the trello plugin is using 104.4.0.0, this could be the reason of failure. Still investigating.

**Comment by ikeough** [comment] 2016-05-04 17:05
This is related to #6565. Nate's Trello plugin is getting loaded first, with an older version of RestSharp, then Dynamo tries to use that same version and you get a missing method exception. We will probably have to use the solution found by @mjkkirschner to strong name versions of RestSharp. Yuck.

**Comment by kronz** [comment] 2016-06-08 02:41
Fix is in with DynamoDS/DynamoRevit#988

**Closed by kronz** 2016-06-08 02:41 UTC
Labels: Blocker, Bug, UI
