### ISSUE TITLE
Dynamo Package Manager doesn't honour file folder structure when publishing versions

### ISSUE THREAD

**Issue by ThomasMahon** [DynamoDS/Dynamo#8223] opened 2017-10-02 09:46 UTC
## Dynamo version

v1.3.1

## Operating system

Win 10

## What did you do? 

Published a new version of BimorphNodes

## What did you expect to see?

My file structure honoured:
This is whats in my bin folder:
![image](https://user-images.githubusercontent.com/18601851/31071870-a0fc7f5e-a75d-11e7-85bf-b2e500ae51ee.png)

....and this is what is in my extra folder:
![image](https://user-images.githubusercontent.com/18601851/31071886-b11369ac-a75d-11e7-89fa-461ea4f4cac2.png)

## What did you see instead?

Once published however, my bin folder now looks like this:
![image](https://user-images.githubusercontent.com/18601851/31072049-50e5fbf2-a75e-11e7-96cc-6ed3a5c89980.png)

and my extra folder:
![image](https://user-images.githubusercontent.com/18601851/31072057-5b77d536-a75e-11e7-9391-15e9cece8f26.png)

Why is the Migrations XML moved to the extra folder when the primer states it must live in the root folder of the dll? 

Why is the BimorphNodes2018.dll copied to the bin folder?

It then leads to these warnings in Dynamo, if the package is used in earlier versions of Revit, which wouldn't (and shouldn't) appear if my file folder structure was honoured:
![image](https://user-images.githubusercontent.com/18601851/31072221-f946be44-a75e-11e7-9d86-107c036f1496.png)

**Comment by mjkkirschner** [comment] 2017-10-17 21:13
This seems like a bug. 
Have you been able to resolve it?

**Comment by ThomasMahon** [comment] 2017-10-18 09:18
Unfortunately not, I did attempt to publish again, ensuring the file structure was correct, but it once again screwed up the file locations in the same way!

**Comment by mjkkirschner** [comment] 2019-08-24 22:23
@QilongTang you were looking at this recently, can you record what you found?

**Comment by QilongTang** [comment] 2019-08-25 04:48
@mjkkirschner We should test this within team. What I looked at is that folder structure under `bin` folder will be preserved, but I did not test the combo case with something in `extra` folder

**Comment by ksobon** [comment] 2020-05-04 14:18
@QilongTang I just wanted to bump this again. I agree with @ThomasMahon that the folder structure is getting all screwed up when publishing the package. To re-create this, try and put some DLLs into the `extra` folder. When published they will be moved to `bin` location. That's not good. 

One workaround for that was to zip up DLLs in the extra folder, and then unzip them using a `ViewExtension` since these load before any ZeroTouch nodes get loaded. 

Ps. The use case here is the same as @ThomasMahon . Different versions of Revit would have their own DLLs, but in order for the correct one to get loaded, we need ability to keep them in the extra folder (prevents all of them from getting loaded automatically).

**Comment by Amoursol** [comment] 2023-03-10 18:18
@ThomasMahon This was tested internally and not reproducible in latest builds. Closing for now, but please do reopen if you are still experiencing this issue.

**Closed by Amoursol** 2023-03-10 18:18 UTC
Labels: bug, Package Manager
