### ISSUE TITLE
Searching of nodes in Dynamo 2.0.2 is very slow

### ISSUE THREAD

**Issue by dietervermeulen** [DynamoDS/Dynamo#9778] opened 2019-06-06 18:17 UTC
## What did you do? 
Searching for nodes in the library or in-canvas is very lagging, when typing the text. Almost unworkable.
After restarting Dynamo it works again for a while. Then it starts occuring again after some time.

## What did you expect to see?
Immediate response of what you type

## What did you see instead?
Delay of 5-10 seconds

List of installed packages:

![image](https://user-images.githubusercontent.com/12096185/59056245-129a0100-8898-11e9-90f6-b98ca7b3ed64.png)

**Comment by mjkkirschner** [comment] 2019-06-07 00:23
How long do you need to be using Dynamo before you can reproduce this?

**Comment by dietervermeulen** [comment] 2019-06-07 07:19
About 5-10 mins


Best regards,

Dieter Vermeulen, M.Sc. Str. Eng.
Technical Sales Specialist - AEC
Computational Design & Engineering

MOBILE +32 (0)471 45 27 38

Twitter<http://twitter.com/bim4struc>
LinkedIn<http://be.linkedin.com/in/dietervermeulen/>
Blog<http://revitbeyondbim.wordpress.com/>

[cid:image001.png@01D51D12.15D1DE70]

**Comment by mjkkirschner** [comment] 2019-08-31 01:13
@dimven - since it seems like you have seen this before - do you have any repro steps? We installed the same packages and repeated searches for ten minutes while timing them but did not see a slowdown.

Current hypothesis is that it's not search that gets slower but the entire application after a specific workflow, any insight?

**Comment by QilongTang** [comment] 2019-09-13 15:47
@Lazarica-t Is it slow right after you open DynamoRevit or you have opened it for a while?

**Comment by Lazarica-t** [comment] 2019-09-13 16:07
@QilongTang Right after opening Dynamo. Even tried with a system restart. Today was a real pain to work with dynamo.

Can it be Revit related? Like some weird add-ins.

**Comment by QilongTang** [comment] 2019-09-13 17:02
@Lazarica-t Our team has tested with latest Dynamo and a bunch of packages installed and could not reproduce. So we can't rule out the factor that is is related to other weird add-ins.. Can you post us what do you have locally as Revit addins to help us?

**Comment by Lazarica-t** [comment] 2019-09-13 17:27
@QilongTang Sure, no problem I will share my add-ins on Monday when I get back to the office and at my workstation.

**Comment by Lazarica-t** [comment] 2019-09-16 08:14
@QilongTang I think it might something to do with an add-in **pyRevit**. I've uninstalled it and Dynamo seams to be back to normal now, I'm not getting all those constant freezes now.

**Comment by QilongTang** [comment] 2019-09-16 14:03
@Lazarica-t Thanks for the info. FYI: @Amoursol @DynamoDS/dynamo

**Comment by arsenvs** [comment] 2019-09-30 05:58
Hi guys, we had the same problem and after uninstalling the Autodesk Point Layout add-in Dynamo started functioning properly again.

**Comment by arsenvs** [comment] 2019-12-26 12:20
Hi Guys, if you have Autodesk Desktop Connector running then you better disable or even better uninstall it. It causes all your system stall. Including Dynamo. The moment I got rid off the Desktop Connector my Dynamo started working like a charm.

**Comment by monsieurhannes** [comment] 2021-05-21 05:44
Thanks @arsenvs , that helped! 
(Revit 2020.2.4 - Dynamo 2.3.1.11830)

**Comment by mjkkirschner** [comment] 2022-02-05 04:52
I'm going to close this - (see 195 above)

**Closed by mjkkirschner** 2022-02-05 04:52 UTC
Labels: 2.x, needs investigation, tracked

**Comment by Lazarica-t** [comment] 2022-06-29 07:22
Seems like there are no improvements with the latter updates (Revit 2022 + Dynamo 2.12) and Desktop Connector is still causing issues! Extremely slow node search while Desktop Connector is opened..

**Comment by Amoursol** [comment] 2022-07-01 16:44
@Lazarica-t the "search" performance improvements, specifically, are in Dynamo 2.13. 

@mjkkirschner do you think we need to investigate why Desktop Connector in particular is a problem with Dynamo?

**Comment by Lazarica-t** [comment] 2022-07-14 09:13
> @Lazarica-t the "search" performance improvements, specifically, are in Dynamo 2.13.
Oh :( bummer .. 
Well, the search pretty snappy in 2.12 also.. but only with Desktop Connector closed :D
