### ISSUE TITLE
Sheet.ByNameNumberTitleBlockAndViews node problem

### ISSUE THREAD

**Issue by hienngocloveyou** [DynamoDS/Dynamo#4661] opened 2015-06-09 06:30 UTC
Hi everyone, i want to duplicate views and place on sheet. Everything is ok when i duplicate view, and then i place sheet on view with View.Sheet node, but i have problem with type of view is Structural plan view and schedule view. How i can place all view on sheet ?? May i use python code for it ?? This is my file dynamo, someone can check it for me, thanks for reading.
![image](https://cloud.githubusercontent.com/assets/12809072/8051871/ab8fed40-0eab-11e5-9d90-d3d38dbafbc6.png)

**Comment by hienngocloveyou** [comment] 2015-06-09 06:31
Someone can test Node Sheet.ByNameNumberTitleBlockAndViews and will see, i’m sure 100% it has problem with these view style (strutural paln view, schedule view)

**Comment by ksobon** [comment] 2017-05-30 00:16
This was most likely caused by the fact that at the time there was no support/wrappers for Structural Plan view and Schedule View. Since then this should have been resolved with new wrappers added to 1.3 version. cc: @kronz can we close this?

**Closed** 2017-05-30 19:20 UTC
Labels: Bug, Revit
