### ISSUE TITLE
Background preview not visible when preview is enabled AFTER graph execution

### ISSUE THREAD

**Issue by andydandy74** [DynamoDS/Dynamo#5771] opened 2015-11-29 14:16 UTC
Dynamo 0.9 (can't test this on daily builds currently, so this may have been fixed already)

**Steps to reproduce:**
- Run a graph that contains geometry with background preview disabled
- Enable background preview
- No geometry is displayed

**Expected behaviour**:
After enabling background preview the geometry should be visible if the graph has already been executed. This is a regression BTW - it definitely used to work in 0.7 (don't have 0.8 installed right now, so I can't say anything about that version).

**Workaround:**
a) Set graph to automatic and connect a `Watch 3D` node to any geometry node
b) Change an input parameter of the graph and re-run
c) Re-wire sth. and re-run

**Comment by monikaprabhu** [comment] 2015-12-04 09:25
@andydandy74 We have a bug tracking an similar  issue -Id is  MAGN-9140.

**Comment by mukhesh-studio4** [comment] 2016-11-29 07:30
Has anyone found a solution for this ? 

I have installed the latest build of dynamo for revit, Latest of the graphic drivers from Intel and AMD.

I can see the preview once I install the Intel Integrated graphic drivers, but once I install the AMD drivers, the background goes blank and even the watch 3D nodes show nothing. 

Kindly help with a solution.

**Comment by mukhesh-studio4** [comment] 2016-11-30 08:35
Hi Neal,

Yes I can give you remote access to my machine via teamviewer or any other software you suggest.

**Comment by jnealb** [comment] 2016-12-01 15:28
@mukhesh-studio4 Teamviewer works; next week?

**Comment by mukhesh-studio4** [comment] 2016-12-01 15:54
@jnealb Sure. I shall write you an email regarding the same.

**Comment by mukhesh-studio4** [comment] 2016-12-02 05:02
Here are the screenshots for the issue.

1) Without AMD Drivers
2)With AMD Updated Drivers

![without amd graphics](https://cloud.githubusercontent.com/assets/23580840/20823486/6397f332-b87a-11e6-887a-572bca9feddd.png)
![with amd updated drivers](https://cloud.githubusercontent.com/assets/23580840/20823487/643b7246-b87a-11e6-91d5-f95a52d732ff.png)

**Comment by mukhesh-studio4** [comment] 2016-12-09 04:59
Thanks Neal, 

I changed the AMD settings to Force power saving graphics and it worked.
The issue is resolved. 

![dynamo issue resolved](https://cloud.githubusercontent.com/assets/23580840/21038265/36a6fb90-bdfa-11e6-9d5f-450668750f2b.png)

**Comment by johnpierson** [comment] 2018-12-14 14:06
Closing as this issue is for an outdated version of Dynamo. If this persists in 2.0.x for you, please feel free to reopen and update accordingly.

**Closed by johnpierson** 2018-12-14 14:06 UTC
Labels: Graphics
