### ISSUE TITLE
Menu on top

### ISSUE THREAD

**Issue by vykrum** [DynamoDS/Dynamo#6810] opened 2016-06-29 17:12 UTC
## Dynamo version

1.0.1.1757
## Operating system

Windows 10
## What did you do?

Right clicked on the Dynamo canvas, the menu appeared
I then clicked some other window (outside Dynamo)
## What did you expect to see?

The new window replacing Dynamo on screen
## What did you see instead?

The Dynamo menu persists in the foreground
Need to get back to Dynamo to dismiss it.

![20160629-7](https://cloud.githubusercontent.com/assets/5621624/16461540/a505aff8-3e4a-11e6-9c51-ac5ce7d9bc64.png)

**Comment by ke-yu** [comment] 2016-07-12 09:32
@vykrum could you please let me know if it is still reproducible?

**Comment by vykrum** [comment] 2016-07-12 11:01
@ke-yu Seems to have been resolved. Thanks

**Comment by vykrum** [comment] 2016-07-13 07:27
Reproduceable in 1.1.0.1930

**Comment by samuelcwl** [comment] 2016-08-18 07:14
@vykrum , I tried reproducing it but could not get the same result. When you right-clicked on the workspace, was your Dynamo full-screen or resized? Was your other window behind the Dynamo window?

If you right-clicked on the workspace, and then clicked on your browser button in the taskbar, does the popup still remain?

**Comment by vykrum** [comment] 2016-08-18 12:43
@samuelcwl The issue persists in ver 1.1.0

> Dynamo full-screen or resized?
Both

> Was your other window behind the Dynamo window?
Yes

> If you right-clicked on the workspace, and then clicked on your browser button in the taskbar, does the popup still remain?
Yes

**Comment by samuelcwl** [comment] 2016-08-22 07:47
Hmm ok. When you use Alt-Tab to switch windows, does it persist?

**Comment by vykrum** [comment] 2016-08-23 05:17
> Hmm ok. When you use Alt-Tab to switch windows, does it persist?
@samuelcwl Yes it does.

**Comment by andydandy74** [comment] 2017-04-10 10:27
@samuelcwl - I still get this in 1.3  - any chance this is going to get fixed any time soon?

**Comment by smangarole** [comment] 2017-07-17 15:50
@vykrum @andydandy74 I am investigating this issue. We cannot reproduce this issue in latest master but I do see it in 1.3.0. The issue might have been fixed on master. I will send an update soon.

Thanks.

**Comment by jnealb** [comment] 2017-07-18 19:54
@vykrum @andydandy74 @smangarole This is fixed with D4R 2.0.0.5492.

**Closed by jnealb** 2017-07-18 19:54 UTC
Labels: UI

**Comment by andydandy74** [comment] 2017-07-19 04:17
@jnealb good to hear. Any chance we'll see a return of daily builds any time soon?
