### ISSUE TITLE
Dynamo 1.0.0 Point ByCoordinates Crash - Revit 2017

### ISSUE THREAD

**Issue by pho-github** [DynamoDS/Dynamo#6957] opened 2016-07-29 15:21 UTC
If this issue is with Dynamo for Revit, please post your issue on the [Dynamo for Revit Issues page](https://github.com/DynamoDS/DynamoRevit/issues).

If this issue is **not** a bug report or improvement request, please check the [Dynamo forum](https://forum.dynamobim.com/), and start a thread there to discuss your issue.

## Dynamo version
Dynamo 1.0.0.1180
(Which version of Dynamo are you using? Go to Help > About if you're not sure.)

## Operating system
Win10
(e.g. Windows 7, Windows 8.1, etc)

## What did you do? 
Dynamo Revit 2017 - Point - ByCoordinates - Crash immediately
(Fill in here)

## What did you expect to see?
It does not crash with v0.9.  Doing the same stuff in Dynamo Sandbox works fine in v1.0. 
(Fill in here)

## What did you see instead?

[DynamoCrash.pdf](https://github.com/DynamoDS/Dynamo/files/390836/DynamoCrash.pdf)

(Fill in here)

**Comment by jnealb** [comment] 2016-07-29 15:23
@pho-github Do you have any Packages installed? If so, which ones?

**Comment by pho-github** [comment] 2016-07-29 15:34
No packages.

**Comment by pho-github** [comment] 2016-07-29 16:01
Does anyone have this issue on Revit 2017 & Dynamo v1.0.0.  I want to make sure I'm not the only one who is seeing this.

**Comment by jnealb** [comment] 2016-07-29 16:07
I will check shortly

**Comment by jnealb** [comment] 2016-07-29 20:28
@pho-github This does not reproduce for me with DynamoRevit 1.0.0.1180 and Revit 2017 build 17.0.1008.0
20160627_0715(x64) - Point.ByCoordinates works as expected.

**Comment by pho-github** [comment] 2016-07-29 20:46
Thank you for the confirmation. I will have to find another system with fresh OS and fresh install of Revit to dig out the issue.

**Comment by jnealb** [comment] 2016-07-29 21:06
I was on Win7

**Comment by ke-yu** [comment] 2016-08-02 06:31
@pho-github As Dynamo 1.1 has been released, you may try Dynamo 1.1.

**Comment by pho-github** [comment] 2016-08-04 12:53
I found the issue. It didn't make sense but it's the fact.  Installing Alias Autostudio 2017 broke Revit 2017 / Dynamo (1.0 or higher) crash using Point ByCoordinate.  Uninstalling Alias Autostudio immediately restores the function.  To workaround the crash, change the mode from Automatic to Manual and Run it.  The attach is the screenshot of the error.  I don't see the relation with AutoStudio but it is what it is.  Can I get a confirmation and where do I get help to get this resolved?
![dynamo point error](https://cloud.githubusercontent.com/assets/20726991/17402298/89f7f742-5a20-11e6-9c37-3718c043f1fc.JPG)

**Comment by ke-yu** [comment] 2016-08-08 00:13
Is it related to ASM, @aparajit-pratap ?

**Comment by aparajit-pratap** [comment] 2016-08-08 04:28
I think this could be related to Alias 2017 having a version of ASM that conflicts with that of Revit2017. @jnealb @riteshchandawar can we install a version of Alias and try and reproduce the crash? The crash as such is due to the direct manipulation gizmo that appears as soon as you drop a `Point.ByCoordinates` node and if there is some ASM binary incompatibility due to which LibG is unable to load. This particular defect is already tracked here: http://adsk-oss.myjetbrains.com/youtrack/issue/MAGN-9588

**Comment by jnealb** [comment] 2016-08-08 13:37
@aparajit-pratap @ke-yu @pho-github On it.

**Comment by jnealb** [comment] 2016-08-11 20:11
@pho-github @aparajit-pratap This is tracked with MAGN-10546.

**Comment by aparajit-pratap** [comment] 2016-08-23 07:17
Fixed in https://github.com/DynamoDS/DynamoRevit/pull/1196

**Closed by aparajit-pratap** 2016-08-23 07:17 UTC
Labels: Bug, Critical
