### ISSUE TITLE
request the feature of setting; Force re-calculation mode

### ISSUE THREAD

**Issue by birdland007s** [DynamoDS/Dynamo#6759] opened 2016-06-20 11:02 UTC
## Dynamo version

Dynamo 1.0.0.1180
## Operating system

Windows 10 and 7

Dynamo node seems saves it's calculated result as a cache. And it prevents from re-running from same input.
But dynamo can't see an update of related application such as Revit so this cache mechanism sometimes acts on the dangerous side for system.
It would be better that there is a setting to run whole node every time.

Thank and regards,
Yoji Takahashi

**Comment by ke-yu** [comment] 2016-06-21 01:59
hi @birdland007s , actually there is an option to do that, though it doesn't execute all nodes *every time*. If the run mode is switched to Manual, you can force Dynamo to run all nodes through this menu item:

![untitled](https://cloud.githubusercontent.com/assets/2600379/16215650/9d828356-3796-11e6-8c83-5123d829519e.png)

**Comment by mjkkirschner** [comment] 2016-06-21 02:00
but you'll have to build from source and use sandbox to use this option I think?

**Comment by ikeough** [comment] 2016-06-21 02:43
This is by design. We enable third parties to create libraries which force re-execution. But it is not the preferred mode for execution. @birdland007s, can you give an example where you need to force a reexecution of a node?

**Comment by mjkkirschner** [comment] 2016-06-21 03:16
@ikeough I've got some 😜 

* interacting with an API that provides no events on document or element modification.
* when you have gotten into a strange state with an API that does provide events and do not wish to close and re-open Dynamo, but you want to be sure of the state that you are in.
* When your graph is dependent on a root node that is a random number but which will never re-execute because the live-runner cannot anticipate its need to re-execute. (run periodic is a bad solution here, though I guess a node author should dirty this kind of node somehow).
* when you are using a python node that does things like web requests internally or generates random numbers and should re-run.
* I'll think of some more.

**Comment by birdland007s** [comment] 2016-06-23 11:12
Thanks all and sorry for this late replay.
@ikeough, the node, which I want to re-execute eveytime, is Python Script.
The script reads Revit objects and gets their attributes.
The attributes is cooked after that following nodes.

I can understand this is by design, that is, it is difficult to always re-execute in the situation which Dynamo works together with unspecified apps. But I also think it is possible to implement re-execution mode as standard function on the limited condition and nodes. It is enough for me that re-executed nodes are only user specified node and Manual mode.

Best regards,
Yoji

**Comment by andydandy74** [comment] 2016-06-23 14:13
Also see #3273 & #4603

**Comment by ikeough** [comment] 2016-06-23 15:18
@mjkkirschner I believe we can add this through a method attribute. Something like [AlwaysReexecute]

**Comment by mjkkirschner** [comment] 2016-06-23 15:21
exactly what I was thinking!

**Comment by ikeough** [comment] 2016-06-23 16:11
@birdland007s We will need to do some design to provide a way for the python node to continually re-execute. I do not want to add continuous re-execution to the python node, by default because the python node gives you the power to write a script to do anything including long-running operations that you don't want to execute every time if you can avoid it.

The end result would be similar to some improvements to the python node requested in #3378, regarding using comments in the python node to trigger certain functionality.

**Comment by birdland007s** [comment] 2016-06-23 16:58
Agree with you and the list of #3378.
Thanks a lot.

**Comment by mostaphaRoudsari** [comment] 2016-06-23 19:59
@ikeough @mjkkirschner is it possible to hash the code inside the Python node and execute it if only there has been changes from the last run? Having it to always re-run is not going to be efficient.

**Comment by johnpierson** [comment] 2018-11-29 15:48
Closing this as it is referenced here https://github.com/DynamoDS/Dynamo/issues/4603

**Closed by johnpierson** 2018-11-29 15:48 UTC
