### ISSUE TITLE
Failure to intersect and project geometry when working in millimeters 

### ISSUE THREAD

**Issue by dimven** [DynamoDS/Dynamo#5233] opened 2015-09-04 06:12 UTC
Hello,
I've been meaning to report this earlier. Ever since version 0.8 Dynamo seems to dislike intersecting and projecting objects, when working with large unit sizes(like for example when your project is set up in millimeters).
Here are some examples of this:
![2015-09-04_14-10-22](https://cloud.githubusercontent.com/assets/7148394/9677600/9f5f4ee2-530e-11e5-8e6b-e65780b189c2.png)

I thought it could be due to FP errors. However notice that if I scale the geometry down(or change my units to meters inside Revti), the intersection performs as expected:
![2015-09-04_14-10-33](https://cloud.githubusercontent.com/assets/7148394/9677601/a5bf2bd6-530e-11e5-9f87-f2dd5fe27403.png)

@tatlin, @RodRecker 

This doesn't seem to be a limited case. Another user had a problem with this on the forums:
http://dynamobim.com/forums/topic/dynamo-intersection/

**Comment by josols** [comment] 2015-09-04 08:46
I would say using large coordinates is a general problem in Dynamo (as it has been in Revit for many years) Not only with projecting/intersecting, but with graphics as well.

**Comment by dimven** [comment] 2015-09-04 12:02
The above example is roughly about 200m x100m x 120m.

**Comment by ParametricMonkey** [comment] 2015-10-02 06:22
Yes I've also noticed this. I have a script which checks the intersection between a model curve and rooms. It use to work but now it says there are no intersections. I thought it might be due to a rounding error caused by having the project base point at a weird level. However, it happens even if you model at level 0.0. By changing the Revit units to meters it fixes the problem. But if you change it back to millimeters it fails. Definitely sounds like a Dynamo precision error.

**Comment by dimven** [comment] 2015-12-17 03:58
Hello,

Has anybody had a chance to look into this? Points are severely affected in some cases (surfaces), however curves work just fine. Here's a more detailed study on the stable 0.9 release:

![2015-12-17_11-56-15](https://cloud.githubusercontent.com/assets/7148394/11860909/5cb5f070-a4b5-11e5-80b1-c57d2d9ab31d.png)

**Comment by dimven** [comment] 2015-12-17 08:54
Another area where planes fail is when projecting at small angles relative to the plane. In the below example any vector hitting the surface at less than 30 degrees fails:
![2015-12-17_16-55-10](https://cloud.githubusercontent.com/assets/7148394/11865413/db0a990c-a4de-11e5-9048-2c0f3d12d684.png)

I am not sure if this points to a major problem with planes or to a minor one limited to the "Point.Project" node.

Looking forward to your feedback on this.

**Comment by aparajit-pratap** [comment] 2015-12-22 03:31
@dimven thanks for pointing out these issues. The geometric kernel used in Dynamo (and Revit) has known limitations when performing reliable modeling operations on models with large coordinate values (greater than 10,000 units (plus or minus) in X, Y, or Z). This therefore is a hard problem to fix not only in Dynamo but also in Revit. While addressing this at the kernel level is outside our scope, there may be some workarounds we can make in Dynamo (such as setting bounding boxes around models and scaling them down and then back up after performing the operation) to address them at least partially. We're tracking these issues as enhancements that we can work on going forward.

**Comment by ParametricMonkey** [comment] 2016-03-02 04:36
This really should not be categories as an 'enhancement'. It is a fundamental flaw that needs to be sorted out. Not having the ability to offset, intersect and get closest point,is a major problem. Many people use mm on their projects.

**Comment by dimven** [comment] 2016-10-25 13:50
Any idea when https://github.com/DynamoDS/Dynamo/pull/6991 will be merged?

**Comment by monikaprabhu** [comment] 2017-02-16 04:18
@dimven - 1.2.3.xxxx dailybuilds available on DynamoBIM(http://dynamobuilds.com/) includes the fix for   ASM scaling. All issues reported except for the rotating of planes is fixed in these builds. The rotating of planes is not related to ASM scaling , I'll track it as a separate issue. Please give it a try and if you can still reproduce let us know.

**Comment by dimven** [comment] 2017-02-16 05:24
Awesome, will have a look over the weekend.

**Closed** 2017-02-23 02:53 UTC
Labels: Geometry
