### ISSUE TITLE
Running automatic mode with an OOTB direct shape node will never stop running 

### ISSUE THREAD

**Issue by marcellosgamb** [DynamoDS/Dynamo#5606] opened 2015-10-26 19:13 UTC
Running automatic mode with an OOTB direct shape node will never stop running 
I am using the daily build of
DynamoInstall0.9.1.20151026T0056

**Comment by andydandy74** [comment] 2015-10-26 19:42
Most likely another case of #5385

**Comment by mjkkirschner** [comment] 2015-10-26 20:04
@marcellosgamb thanks for trying this functionality out. can you please attach or email your .dyn file? - or take a screen shot of the .dyn?

This is most likely a rebinding loop.

**Comment by mjkkirschner** [comment] 2015-10-26 20:05
@marcellosgamb also what version of revit are you on?

**Comment by marcellosgamb** [comment] 2015-11-06 09:22
i am only able to run direct shape on a manual run. not a automatic run and it will keep recreating new direct shapes every time I rerun the manual Dynamo graph!


[cid:71cfff13-fae2-44ec-8d06-1a07c36b1f85]
________________________________

**Comment by marcellosgamb** [comment] 2015-11-06 09:24
i am only running 9.1 daily 
![direct](https://cloud.githubusercontent.com/assets/6132497/10993640/18b5c090-8425-11e5-9db9-a8e0d129b31b.png)
able to run direct shape on a manual run. not a automatic run and it will keep recreating new direct shapes every time I rerun the manual Dynamo graph!

**Comment by mjkkirschner** [comment] 2015-11-06 15:19
@marcellosgamb what version of Revit are you running on?

**Comment by mjkkirschner** [comment] 2015-11-06 15:21
@marcellosgamb thanks for the graph, I will try to reproduce locally, is it possible to share the rvt file?

**Comment by mjkkirschner** [comment] 2015-11-06 15:45
@marcellosgamb I need to test more, but I think I see what is happening here. You are pulling the rooms out of a model and turning those into direct shapes, and then adding those direct shapes to the model as more rooms, a document modification event is occurring when creating and updating the direct shapes and this is causing the All Elements Of Category node to fire again, now pulling out even more rooms since we just added direct shapes with room category....  I'll look further but can you try changing the category of your direct shapes to something else?

**Comment by marcellosgamb** [comment] 2015-11-06 15:57
I will
Try it but look at the list I am only pulling the first 68 items out of the list

On Nov 6, 2015, at 7:45 AM, Michael Kirschner <notifications@github.com<mailto:notifications@github.com>> wrote:


@marcellosgamb<https://github.com/marcellosgamb> I need to test more, but I think I see what is happening here. You are pulling the rooms out of a model and turning those into direct shapes, and then adding those direct shapes to the model as more rooms, a document modification event is occurring when creating and updating the direct shapes and this is causing the All Elements Of Category node to fire again, now pulling out even more rooms since we just added direct shapes with room category.... I'll look further but can you try changing the category of your direct shapes to something else?

-

**Comment by marcellosgamb** [comment] 2015-11-06 16:21
i changed to a different category and removed the input of material and name so rooms is not influencing it in any way.. it sill continuously runs on automatic mode.
![stackingdiagramsquestion2](https://cloud.githubusercontent.com/assets/6132497/11002048/55e4c17a-845f-11e5-882f-41996b67f297.png)

**Comment by mjkkirschner** [comment] 2015-11-06 16:34
okay, thanks for trying this out. tracked as MAGN 9046 .

Without being able to get into the code right now, my feeling is that it's a similar issue, when the direct shape is created it triggers a document modification and perhaps the AllElementsOfCategory node requires the geometry and recreates the input geo... The direct shape node injects a tag into the input shape to make sure it doesn't update unnecessarily. MyGuess - The issue arrises because the element.Geometry is being re-created and no longer has that tag.

thanks again for this report and testing

**Comment by kronz** [comment] 2015-11-10 18:28
Hey Marcello,
Can you still create this problem?  I'm trying to repro, and the only situation where it breaks for me is if you are pulling out Rooms (or any category) and wrtiting Direct Shapes back to that same category.  In this case the bug is "creating an infinite loop creates an infinite loop", which is much less impressive than what you are describing :)

**Comment by ikeough** [comment] 2016-05-02 03:46
@mjkkirschner Closing because the internal defect is marked as closed.

**Closed by ikeough** 2016-05-02 03:46 UTC
