### ISSUE TITLE
Nodes being deleted automatically whenever open the script in Dynamo 2.04

### ISSUE THREAD

**Issue by moeyanung** [DynamoDS/Dynamo#11115] opened 2020-09-15 10:22 UTC
If this issue is with Dynamo for Revit, please post your issue on the [Dynamo for Revit Issues page](https://github.com/DynamoDS/DynamoRevit/issues).

If this issue is **not** a bug report or improvement request, please check the [Dynamo forum](https://forum.dynamobim.com/), and start a thread there to discuss your issue.

## Dynamo version - 2.04

(Which version of Dynamo are you using? Go to Help > About if you're not sure.)

## Operating system - window 10

(e.g. Windows 7, Windows 8.1, etc)

## What did you do? 

Some nodes from the script were deleted automatically whenever open the script in Dynamo 2.04.

## What did you expect to see?

(Fill in here)

## What did you see instead?

(Fill in here)

**Comment by Amoursol** [comment] 2020-09-18 20:35
Hello @moeyanung - Are you able to upload the .DYN file that this happens to so that we can test? And also a screenshot of what nodes are deleted please?

**Comment by moeyanung** [comment] 2020-09-21 07:19
Hi Amour,

it's the built-in selection nodes for category and types.
And also some connections. The issue is not related to the script and it
happens all the time when the script includes those nodes.

Thanks & Regards,
Moe

**Comment by mjkkirschner** [comment] 2020-12-08 04:18
Hi @moeyanung - I'm going to close this issue for now - please see the related issues and threads:
https://github.com/DynamoDS/Dynamo/issues/10617

usually this is caused by a conflicting package or addin and thats a good place to start debugging the issue.

**Comment by mjkkirschner** [comment] 2020-12-08 04:19
https://forum.dynamobim.com/t/nodes-disappearing-on-reopen/41632

**Closed by mjkkirschner** 2020-12-08 04:18 UTC
Labels: bug, needs more info
