### ISSUE TITLE
File Path Node - bad output when spaces exist

### ISSUE THREAD

**Issue by dbaldacchino** [DynamoDS/Dynamo#7429] opened 2016-12-15 19:19 UTC
If this issue is with Dynamo for Revit, please post your issue on the [Dynamo for Revit Issues page](https://github.com/DynamoDS/DynamoRevit/issues).

If this issue is **not** a bug report or improvement request, please check the [Dynamo forum](https://forum.dynamobim.com/), and start a thread there to discuss your issue.

## Dynamo version

1.2.1.3083

## Operating system

Windows 7 & Windows 10

## What did you do? 

Added a File Path and tried reading the data using the Excel.ReadFromFile node and noticed it couldn't find the file when there were spaces in the filename or somewhere along the path. Upon inspection, I see it's replacing spaces with %20, so as you can see below the current workaround is to replace them with spaces for this to work.

![filepath spaces issue](https://cloud.githubusercontent.com/assets/4656191/21238504/f7bf6b50-c2c8-11e6-8559-443a40ca1af0.png)

## What did you expect to see?

I expect the file path to retain spaces. The node itself shows the correct path at the bottom but this does not match the output.

## What did you see instead?

See above.

**Comment by mjkkirschner** [comment] 2016-12-15 19:20
@gregmarr I thought you had worked on this last. Did this regress?

**Comment by gregmarr** [comment] 2016-12-15 19:27
Nope, it just hasn't been released yet.  The fix was in core, which couldn't be updated with the studio release.

**Comment by mjkkirschner** [comment] 2016-12-15 19:29
hmm, this looks like it might be running in Revit, but not sure if that fix was released there either yet.

**Comment by dbaldacchino** [comment] 2016-12-15 19:44
My example is while running in Revit (I don't have Studio).

**Comment by mjkkirschner** [comment] 2016-12-15 19:45
@dbaldacchino thanks for reporting, this should be fixed and in the next release.

**Comment by dimven** [comment] 2016-12-16 02:06
A big +1 on this issue. I've been meaning to write about it but I can't seem to isolate the cause. It's been happening regularly ever since Dynamo 1.0 for me. (when the relative path capabilities were first introduced)
It affects both Studio and D4R.

The problem is that it's occurrence is pretty chaotic. Sometimes it happens, sometimes it doesn't. Some PCs seem to be more prone to it.

It looks like something breaks between the serialization/deserialization from XML of the path's string.

**Comment by gregmarr** [comment] 2016-12-16 02:24
> It's been happening regularly ever since Dynamo 1.0 for me. (when the relative path capabilities were first introduced)

Yes, the issue was in the relative path computation code.

If the dyn file has not yet been saved, then it doesn't have a path, and so no relative path can be computed.  Also, the relative path between the dyn file and the selected file must contain a space.  If the dyn file and the selected file are in the same directory, for example, then it will be fine.

**Comment by DanielHurtubise** [comment] 2016-12-19 06:50
It also happens in Studio. 
I moved the file back to C:/ then back to the initial folder and it ran fine
![image](https://cloud.githubusercontent.com/assets/4299930/21303603/be6bad38-c5bf-11e6-8184-8a5381ff3d6a.png)

**Comment by ksobon** [comment] 2017-06-12 12:57
@kronz this was fixed for 1.3 release. Can we close this issue?

**Comment by jnealb** [comment] 2017-06-12 14:01
Yes

**Closed by jnealb** 2017-06-12 14:01 UTC
