### ISSUE TITLE
Erro

### ISSUE THREAD

**Issue by LucianoSOliveira** [DynamoDS/Dynamo#6531] opened 2016-04-26 21:58 UTC
HRESULT: [0x8876086A], Module: [SharpDX.Direct3D9], ApiCode: [D3DERR_NOTAVAILABLE/NotAvailable], Message: Unknown

   em SharpDX.Result.CheckError()
   em SharpDX.Direct3D9.Direct3DEx.CreateDeviceEx(Int32 adapter, DeviceType deviceType, IntPtr hFocusWindow, Int32 behaviorFlags, PresentParameters[] presentationParametersRef, DisplayModeEx[] fullscreenDisplayModeRef, DeviceEx returnedDeviceInterfaceOut)
   em SharpDX.Direct3D9.DeviceEx..ctor(Direct3DEx direct3D, Int32 adapter, DeviceType deviceType, IntPtr controlHandle, CreateFlags createFlags, PresentParameters presentParameters)
   em HelixToolkit.Wpf.SharpDX.DX11ImageSource..ctor()
   em HelixToolkit.Wpf.SharpDX.DPFCanvas.StartD3D()
   em System.Windows.DependencyObject.OnPropertyChanged(DependencyPropertyChangedEventArgs e)
   em System.Windows.FrameworkElement.OnPropertyChanged(DependencyPropertyChangedEventArgs e)
   em System.Windows.DependencyObject.NotifyPropertyChange(DependencyPropertyChangedEventArgs args)
   em System.Windows.DependencyObject.UpdateEffectiveValue(EntryIndex entryIndex, DependencyProperty dp, PropertyMetadata metadata, EffectiveValueEntry oldEntry, EffectiveValueEntry& newEntry, Boolean coerceWithDeferredReference, Boolean coerceWithCurrentValue, OperationType operationType)
   em System.Windows.DependencyObject.SetValueCommon(DependencyProperty dp, Object value, PropertyMetadata metadata, Boolean coerceWithDeferredReference, Boolean coerceWithCurrentValue, OperationType operationType, Boolean isInternal)
   em System.Windows.DependencyObject.SetValue(DependencyProperty dp, Object value)
   em System.Windows.DependencyObject.OnPropertyChanged(DependencyPropertyChangedEventArgs e)
   em System.Windows.FrameworkElement.OnPropertyChanged(DependencyPropertyChangedEventArgs e)
   em System.Windows.DependencyObject.NotifyPropertyChange(DependencyPropertyChangedEventArgs args)
   em System.Windows.DependencyObject.UpdateEffectiveValue(EntryIndex entryIndex, DependencyProperty dp, PropertyMetadata metadata, EffectiveValueEntry oldEntry, EffectiveValueEntry& newEntry, Boolean coerceWithDeferredReference, Boolean coerceWithCurrentValue, OperationType operationType)
   em System.Windows.DependencyObject.InvalidateProperty(DependencyProperty dp, Boolean preserveCurrentValue)
   em System.Windows.Data.BindingExpressionBase.Invalidate(Boolean isASubPropertyChange)
   em System.Windows.Data.BindingExpression.TransferValue(Object newValue, Boolean isASubPropertyChange)
   em System.Windows.Data.BindingExpression.Activate(Object item)
   em System.Windows.Data.BindingExpression.AttachToContext(AttachAttempt attempt)
   em System.Windows.Data.BindingExpression.MS.Internal.Data.IDataBindEngineClient.AttachToContext(Boolean lastChance)
   em MS.Internal.Data.DataBindEngine.Task.Run(Boolean lastChance)
   em MS.Internal.Data.DataBindEngine.Run(Object arg)
   em MS.Internal.Data.DataBindEngine.OnLayoutUpdated(Object sender, EventArgs e)
   em System.Windows.ContextLayoutManager.fireLayoutUpdateEvent()
   em System.Windows.ContextLayoutManager.UpdateLayout()
   em System.Windows.ContextLayoutManager.UpdateLayoutCallback(Object arg)
   em System.Windows.Media.MediaContext.FireInvokeOnRenderCallbacks()
   em System.Windows.Media.MediaContext.RenderMessageHandlerCore(Object resizedCompositionTarget)
   em System.Windows.Media.MediaContext.RenderMessageHandler(Object resizedCompositionTarget)
   em System.Windows.Interop.HwndTarget.OnResize()
   em System.Windows.Interop.HwndTarget.HandleMessage(WindowMessage msg, IntPtr wparam, IntPtr lparam)
   em System.Windows.Interop.HwndSource.HwndTargetFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   em MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   em MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   em System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   em MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(Object source, Delegate method, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by aparajit-pratap** [comment] 2016-05-04 02:42
@LucianoSOliveira could you describe the steps you took to reproduce this error. This information will be useful to us in debugging this problem.

**Comment by smangarole** [comment] 2017-06-19 18:54
We have released a new version of Dynamo since this issue was opened. The issue has been waiting for feedback for almost a year. Closing due to these reasons. Please reopen if this issue resurfaces.

**Closed by smangarole** 2017-06-19 18:54 UTC
Labels: Bug, Graphics, Waiting for feedback
