### ISSUE TITLE
component search is unusably slow

### ISSUE THREAD

**Issue by AndrewHeumann** [DynamoDS/Dynamo#6630] opened 2016-05-16 14:59 UTC
If this issue is with Dynamo for Revit, please post your issue on the [Dynamo for Revit Issues page](https://github.com/DynamoDS/DynamoRevit/issues).

If this issue is **not** a bug report or improvement request, please check the [Dynamo forum](http://dynamobim.org/forums/forum/dyn/), and start a thread there to discuss your issue.
## Dynamo version

1.0
## Operating system

Windows 7
## What did you do?

type a query in right-click-canvas search.
## What did you expect to see?

search results, quickly
## What did you see instead?

spinny wheel for several seconds after each letter typed

**Comment by ikeough** [comment] 2016-05-16 16:05
This is related to #5270 and possibly #6132.

**Comment by ikeough** [comment] 2016-05-16 16:06
@jnealb Have we ever diagnosed this issue?

**Comment by jnealb** [comment] 2016-05-16 16:16
@ikeough Not conclusively, no. However some of the "slow search" reports did clear up after Windows Updates, and in one telling investigation Rod could repro it on his Surface, but when we installed Visual Studio on his machine to debug it, the issue cleared up! I will look back at our records on this; this is just a curbside.

**Comment by ikeough** [comment] 2016-05-16 16:35
#5270 Points to packages that, when loaded, cause this issue. Were we able to reproduce by doing an install of the same packages?

**Comment by AndrewHeumann** [comment] 2016-05-16 18:48
the other thing that seems to clear it up (although I seem to have to do it over and over again!) is uninstall and reinstall of dynamo (with "run as administrator" on the installer)

**Comment by AndrewHeumann** [comment] 2016-05-16 19:01
Incidentally, I was having this behavior with NO 3rd party packages installed. so not sure that's necessarily the culprit.

**Comment by mjkkirschner** [comment] 2016-05-16 19:01
@AndrewHeumann were you running on Revit?

**Comment by AndrewHeumann** [comment] 2016-05-16 19:23
Yes, running on revit

**Comment by AndrewHeumann** [comment] 2016-05-16 19:34
I did have the same issue previously with 0.92 standalone though if I'm not mistaken

**Comment by smangarole** [comment] 2017-07-27 19:55
@AndrewHeumann Since we are not able to reproduce this issue, closing it.

**Closed by smangarole** 2017-07-27 19:55 UTC
Labels: Bug, Major, UI
