### ISSUE TITLE
Workspace shifts after saving

### ISSUE THREAD

**Issue by epeter-** [DynamoDS/Dynamo#3604] opened 2015-01-22 16:22 UTC
1) save workspace
2) open workspace
- definition is shifted to the lower right corner of the screen (only partly visible)
before:
![before](https://cloud.githubusercontent.com/assets/6928491/5859512/15855536-a25b-11e4-8047-4dd0cf33c264.png)
that is what you see when opening the workspace:
![after1](https://cloud.githubusercontent.com/assets/6928491/5859516/200cc43a-a25b-11e4-8318-c50d0e4ea7af.png)
after pushing to the left:
![after2](https://cloud.githubusercontent.com/assets/6928491/5859521/2de898a4-a25b-11e4-9ffc-cfe785000ebb.png)

**Comment by sharadkjaiswal** [comment] 2015-01-23 03:36
@Benglin is this something similar to watch3D node issue??

**Comment by Benglin** [comment] 2015-01-23 03:40
No @sharadkjaiswal it is different, and it has something to do with [a recently discovered regression](http://adsk-oss.myjetbrains.com/youtrack/issue/MAGN-5745) that is being tracked internally. Will investigate and provide details when anything is found.

**Comment by ikeough** [comment] 2016-05-04 23:49
We're closing this issue because the internal issue tracking it has been closed. Please try again with a more recent build of Dynamo, and re-open this if the issue persists.

**Closed by ikeough** 2016-05-04 23:49 UTC
