### ISSUE TITLE
Search menu not working

### ISSUE THREAD

**Issue by SHKnudsen** [DynamoDS/Dynamo#8757] opened 2018-04-17 10:42 UTC
If this issue is with Dynamo for Revit, please post your issue on the [Dynamo for Revit Issues page](https://github.com/DynamoDS/DynamoRevit/issues).

If this issue is **not** a bug report or improvement request, please check the [Dynamo forum](https://forum.dynamobim.com/), and start a thread there to discuss your issue.

## Dynamo version

2.0.0

## Operating system

Windows 7

## What did you do? 

Installed Dynamo 2.0 from http://dynamobuilds.com/ 
Tried to search for nodes in the Node browser menu

## What did you expect to see?

Nodes matching the search word
Selected Nodes appearing in the canvas 

## What did you see instead?

searching has no effect, manually picking nodes from the menu has no effect either. Searching and placing nodes by right clicking the canvas works

![untitled](https://user-images.githubusercontent.com/13732445/38864614-8e5ea614-423b-11e8-8abe-6e6dd0659050.gif)
 
![untitled2](https://user-images.githubusercontent.com/13732445/38864806-25b29bce-423c-11e8-9e31-0c2373f95e4e.gif)

**Comment by Racel** [comment] 2018-04-17 13:28
@SHKnudsen- What versions of Revit are you seeing this in?

**Comment by mjkkirschner** [comment] 2018-04-17 14:00
This is an interesting one, the library is semi functional, but it seems events are not flowing between dynamo and the cef component.

**Comment by ramramps** [comment] 2018-04-18 11:59
@SHKnudsen Can you check the anti-virus installed on the machine where this is working?

**Comment by ramramps** [comment] 2018-04-18 12:49
@mjkkirschner did some research and looks like it's the McAfee.
Is it possible to uninstall and do some testing?

**Comment by Racel** [comment] 2018-04-18 15:39
Being tracked in https://jira.autodesk.com/browse/QNTM-4044

**Comment by SHKnudsen** [comment] 2018-04-19 11:44
I'm in contact with our IT department, need them to uninstall or disable, apparently that's a bigger deal than expected will keep you updated when there is progress.

**Comment by mjkkirschner** [comment] 2018-04-20 00:06
@SHKnudsen I'm not sure I can reproduce this locally without access to enterprise type deployments of these anti virus scanners, my attempts so far have failed. We should merge a potential fix soon, and will ask you to test a development build - would that be possible?

**Comment by SHKnudsen** [comment] 2018-04-20 09:58
@mjkkirschner Sure, just let me know what you need

**Comment by Racel** [comment] 2018-05-14 14:47
@SHKnudsen Just got the fix in the latest daily build on http://dynamobuilds.com/. Can you check it out and let us know if it works for you?

**Comment by SHKnudsen** [comment] 2018-05-15 13:46
@Racel tested the daily build, and everything seems to work now

**Comment by Racel** [comment] 2018-05-17 11:36
Thanks for checking @SHKnudsen! Closing this now. We should be releasing 2.0.1 soon.

**Closed by Racel** 2018-05-17 11:36 UTC
Labels: 2.0.1 Release, Fixed
