### ISSUE TITLE
codeblock and watch node weird behaviour

### ISSUE THREAD

**Issue by ilyamoto** [DynamoDS/Dynamo#7766] opened 2017-04-09 16:26 UTC
## Dynamo version
1.2.1.3083

## Operating system
Windows 10

## What did you do? 

After changing the code "<=" to "<"  or vice versa (see attached files), watch nodes become blank instead of showing data.
The only way to make them work again is to rewire output of the codeblock into watchnode.
Run was set to either Automatic or Manual

![01](https://cloud.githubusercontent.com/assets/27149619/24838949/5eeff68c-1d5a-11e7-84ef-61faf5481fe4.png)
[test.zip](https://github.com/DynamoDS/Dynamo/files/908349/test.zip)

**Comment by alfarok** [comment] 2017-10-30 17:16
This issue appears to be resolved in more recent builds.  Closing the issue due to the fact that I am unable to reproduce, but feel free to reopen if you encounter similar behavior on a newer build.

![image](https://user-images.githubusercontent.com/13341935/32184905-21cad640-bd74-11e7-87e7-ef8b79563b2b.png)

**Closed by alfarok** 2017-10-30 17:16 UTC
