### ISSUE TITLE
Crash when running 'CoreStrings.dyn' sample file

### ISSUE THREAD

**Issue by aesdaile** [DynamoDS/Dynamo#6369] opened 2016-04-05 00:59 UTC
## Dynamo version

0.9.2.4472

## Operating system

Win 7 Pro x64

## What did you do? 

Opened sample file 'CoreStrings.dyn', read some of the text about how it worked, hit RUN

## What did you expect to see?

the results of the examples

## What did you see instead?

Object reference not set to an instance of an object.

   at Dynamo.Controls.NodeView.OnNodeViewMouseMove(Object sender, MouseEventArgs e)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
   at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by kronz** [comment] 2016-04-05 02:10
@aesdaile This doesn't reproduce for me . . . does this happen any time you run the sample?  Is this running inside of Revit?  Which version?

**Comment by aesdaile** [comment] 2016-04-05 04:16
Revit Build: 16.0.490.0
20150714_1515(x64)
Service Pack 2

it seems to happen intermittently, after I have opened and closed other files in Dynamo.

**Comment by kronz** [comment] 2016-04-05 12:50
FYI @riteshchandawar @jnealb @monikaprabhu

**Comment by jnealb** [comment] 2016-04-05 13:30
@aesdaile Unable to reproduce with a few unit tests; will continue to investigate.

**Comment by ke-yu** [comment] 2016-04-06 15:03
I've sent a PR https://github.com/DynamoDS/Dynamo/pull/6381 to fix the crash.

**Comment by ikeough** [comment] 2016-04-21 16:27
@ke-yu Please remember to close the issue when the PR is merged. Thanks for the fix!

**Closed by ikeough** 2016-04-21 16:27 UTC
