### ISSUE TITLE
Point.ByCoordinates (X,Y,Z) inconsistent behaviour using cross product lacing

### ISSUE THREAD

**Issue by ThomasMahon** [DynamoDS/Dynamo#6528] opened 2016-04-26 16:01 UTC
## Dynamo version

0.9.2
## Operating system

Win 10
## What did you do?

Used a range with cross-product lacing to create an rectangular array of points in XY using the Point.ByCoordinates (X,Y,Z) node. No input for Z, so the nodes default Z value of 0 is used. This correctly returns a 2D list.

However, when I input a Z value (singleton), it returns a 3D list?
## What did you expect to see?

I expected to see the same data structure, i.e. a 2D list, elevated by the Z height I input. See images for examples.
## What did you see instead?

A 3D list instead of a 2D list.

![2d array](https://cloud.githubusercontent.com/assets/18601851/14825111/7e888456-0bd0-11e6-9413-38f67e3ea327.jpg)
![3d array](https://cloud.githubusercontent.com/assets/18601851/14825110/7e84e2b0-0bd0-11e6-9c97-17fe0dc0a447.jpg)

**Comment by kronz** [comment] 2016-05-03 02:09
@ke-yu any reason for this behavior?  
cc @Racel

**Comment by Racel** [comment] 2016-05-03 17:29
@kronz @ke-yu @ThomasMahon @mjkkirschner - This is not a regression. I believe the default value behavior seen in the first image is the incorrect behavior, and we should consider fixing it as a bug. The second image with the 3D list is the correct result of cross-product lacing that is applied by default to node inputs. To represent this with replication guides, the Point.ByCoordinates node automatically does the following: Point.ByCoordinates(x<1>,y<2>,z<3>).

@ThomasMahon - If you would like a 2D list, the way to do this would be to specify your own lacing using custom replication guides and to specify that it not replicate over the z-value. This would be: Point.ByCoordinates(x<1>,y<2>,z). See the image below.

![image](https://cloud.githubusercontent.com/assets/2551261/14992041/2cfad5c8-1132-11e6-90df-7f13c56ff9ae.png)

@ke-yu - It looks like default values are being treated differently than single value inputs. Is there a reason for this? If I provide a number input with the value of 0 into the node, the correct replication is applied. Let me know if we should file a bug for this, or if we need to discuss this in more detail.

**Comment by ThomasMahon** [comment] 2016-05-03 21:21
@Racel @ke-yu @kronz @ikeough @mjkkirschner why cant the be the default replication behaviour be @Racel example of the 'Desired result' - it makes way more sense and is infinitely more logical? i.e. index 0 of list 1 gets matched with index 0 of list 2 and so on. If list 1 is 1D and if list two is 2D then all member of its sublist gets matched with the corresponding member from list 1. If the third list is a single value, it doesn't replicate as its not a list. If list 3 is a list, it replicates too. Simple. 

Consider new users; the default replication behaviour (further convoluted due to the dark art of replication guides) is in my view, a minefield that needs to be improved.

**Comment by Racel** [comment] 2016-05-04 13:26
@ThomasMahon - I agree, replication guides are a minefield, but are super powerful. I also think that your idea does make sense. Here are a few concerns that I have, but would like to hear what @ke-yu and others on the team think about implementing your proposal:
- If we change the replication behavior, this could affect old graphs where users applied cross-product lacing. This could potentially break lots of graphs.
- If we say that a single item never replicates for cross product lacing, would this negatively affect other nodes in unpredictable ways?

**Comment by ke-yu** [comment] 2016-05-05 02:48
@ThomasMahon @Racel @ikeough @mjkkirschner it is a bug that replication guide is not applied to default parameter. 

Replication guide is used to do explicit iteration, even if no replication will happen. So once an argument has replication guide appended, say `x<1>`, function is guaranteed to replicate on `x`. If `x` is a single value, it will be promoted to a list so that it could be iterated. That's why `Point.ByCoordinates(x<1>, y<2>, z)` generates 2D list whileas `Point.ByCoordinates(x<1>, y<2>, z<3>)` generates 3D list. 

If we use cross product, replication guide should be applied to default value as well. It is a bug that it doesn't.

**Comment by ThomasMahon** [comment] 2016-05-06 13:05
@Racel @ikeough @mjkkirschner @ke-yu I thought I would share some ideas on the data matching techniques. 
 
Ultimately, it follows one simple rule: index [0] gets matched with index [0] starting with rank 1, then moves inwards. In the example I posted, this would result in the Z not replicating.

It seems to me that Dynamo default data matching logics does the reverse, working from the deepest rank, back out. As far as my understanding goes, single inputs - as @ke-yu describes - are therefore placed in lists to satisfy this behaviour. However, providing a single input which is placed in list by Dynamo, I think is unpredictable. 

# Single input to 1D list
![singleton to 1d](https://cloud.githubusercontent.com/assets/18601851/15073758/441cdcf2-1393-11e6-9573-71b95979c54a.jpg)

# 1D list to 1D list
![1d to 1d](https://cloud.githubusercontent.com/assets/18601851/15073755/44119ce8-1393-11e6-8049-061f25937d63.jpg)

# 1D list to 2D list
![1d to 2d](https://cloud.githubusercontent.com/assets/18601851/15073752/44115b20-1393-11e6-9d03-487809a1bcab.jpg)

# 2D list to 2D list
![2d to 2d](https://cloud.githubusercontent.com/assets/18601851/15073753/4411850a-1393-11e6-8368-e402a4511e21.jpg)

# 1D list to 3D list
![1d to 3d](https://cloud.githubusercontent.com/assets/18601851/15073756/4414e556-1393-11e6-9c4b-1e2492b6b3eb.jpg)

# 2D list to 3D list
![2d to 3d](https://cloud.githubusercontent.com/assets/18601851/15073754/44117f42-1393-11e6-9d65-7685882f48af.jpg)

**Comment by ke-yu** [comment] 2016-05-07 02:48
@ThomasMahon Replication (not replication guide, if no lacing is applied) processing always start from the outermost list, not from the innermost element. For example, 

```
def foo(x:string, list:var[])
{
    return = x + List.Length(list)
}
xs = {"foo", "bar"};
ys = {{1, 2, 3}, {5, 6, 7, 8}}
foo(xs, ys);
```
As the dimension of input is larger than the dimension of parameter that `foo()` expects, replication will happen here. But if it works as you said from the innermost element, replication will looks like
```
{   "foo",      "bar"}
    / | \       / | \
{ {1, 2, 3},  {4, 5, 6}}
```
So this process will return you `{{"foo1", "foo1", "foo1"}, ,{"bar1", "bar1", "bar1"}}`. (*note this was the old replication behavior! *)

But as replication actually is processed from outermost list (see PR https://github.com/DynamoDS/Dynamo/pull/6110):
```
{   "foo",      "bar"}
      |           | 
{ {1, 2, 3},  {4, 5, 6}}
```
This function call will return you `{"foo3", "bar4"}`.

But once you apply some lacing, *replication guides* are added to arguments, and replication guide will promote a single value to a list.

**Comment by smangarole** [comment] 2017-08-14 15:22
@ThomasMahon Is this still an issue with Dynamo 1.3, given the list@level functionality and other changes?
@Racel and @kronz  please note.

**Comment by ke-yu** [comment] 2017-08-18 06:03
@smangarole we haven't fixed this bug AFAIK.

**Comment by smangarole** [comment] 2017-08-21 15:12
@ke-yu Thanks for the input. @Racel Can you please confirm if this task is filed?

**Comment by Racel** [comment] 2017-10-02 20:57
@ke-yu - Did we address this in the list promotion task? I thought we did. Please close if we have resolved this.

**Comment by ke-yu** [comment] 2017-10-03 00:25
@Racel I believe this has been fixed.

**Comment by Racel** [comment] 2017-10-05 15:52
This has been addressed here: https://github.com/DynamoDS/Dynamo/pull/7773
Closing.

**Closed by Racel** 2017-10-05 15:52 UTC
Labels: Design Script, Improvement, UI
