### ISSUE TITLE
bug report:Excel.WriteToFile for 0.7.6

### ISSUE THREAD

**Issue by frybud** [DynamoDS/Dynamo#3504] opened 2015-01-06 09:19 UTC
i export a large list from revit,
 it show:
![dynamo_bug](https://cloud.githubusercontent.com/assets/10415442/5626532/e762f2ca-95c7-11e4-93d5-564b33875323.png)

i take dynamo back to 0.7.4, it wont show again.

**Comment by sharadkjaiswal** [comment] 2015-01-06 09:23
@aparajit-pratap PTAL, looks like a regression in Excel nodes.

**Comment by aparajit-pratap** [comment] 2015-01-07 05:51
@frybud could you give more details about the inputs that you're sending to the node. I'm unable to reproduce the issue for simple test cases. Thanks.

**Comment by ikeough** [comment] 2016-05-04 23:59
I'm closing this issue as we do not have enough detail to test it. Please re-open if you're still experiencing this problem and have an example which reproduces the problem.

**Closed by ikeough** 2016-05-04 23:59 UTC
