### ISSUE TITLE
Crash report from Dynamo 2.7.0.8546

### ISSUE THREAD

**Issue by vykrum** [DynamoDS/Dynamo#10660] opened 2020-05-15 16:54 UTC
# Issue Description
Please fill in the following information to help us reproduce the issue:

### What did you do?
Added GeometryColor.SurfaceColor and Ran

### What did you expect to see?
Colorful geometry

### What did you see instead?
Crash window

### What packages or external references (if any) were used?
Solar Analysis for Dynamo

### Stack Trace
```
HRESULT: [0x80070057], Module: [General], ApiCode: [E_INVALIDARG/Invalid Arguments], Message: The parameter is incorrect.


   at SharpDX.Result.CheckError()
   at SharpDX.Direct3D11.D3DX11.CreateShaderResourceViewFromMemory(Device deviceRef, IntPtr srcDataRef, PointerSize srcDataSize, Nullable`1 loadInfoRef, IntPtr pumpRef, ShaderResourceView& shaderResourceViewOut, Result& hResultRef)
   at SharpDX.Direct3D11.ShaderResourceView.FromMemory(Device device, Byte[] memory)
   at HelixToolkit.Wpf.SharpDX.MaterialGeometryModel3D.AttachMaterial()
   at Dynamo.Wpf.ViewModels.Watch3D.DynamoGeometryModel3D.Attach(IRenderHost host)
   at Dynamo.Controls.Watch3DView.ViewModelRequestAttachToSceneHandler(Model3D model3D)
   at Dynamo.Wpf.ViewModels.Watch3D.HelixWatch3DViewModel.OnRequestAttachToScene(Model3D model3D)
   at Dynamo.Wpf.ViewModels.Watch3D.HelixWatch3DViewModel.AttachAllGeometryModel3DToRenderHost()
   at Dynamo.Wpf.ViewModels.Watch3D.HelixWatch3DViewModel.AggregateRenderPackages(IEnumerable`1 packages)
   at Dynamo.Wpf.ViewModels.Watch3D.HelixWatch3DViewModel.GenerateViewGeometryFromRenderPackagesAndRequestUpdate(RenderPackageCache taskPackages)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at DynamoSandbox.DynamoCoreSetup.RunApplication(Application app)
```

---
OS: `Microsoft Windows NT 6.2.9200.0`
CLR: `4.0.30319.42000`
Dynamo: `2.7.0.8546`

**Comment by mjkkirschner** [comment] 2020-05-15 19:29
Thanks for this report.


@QilongTang we should try to repro this ASAP - seems to be using new build with updated helix - is that right @vykrum ?


If possible can you provide a .dyn, and provide some more info about your system?
windows 10?
what version of directX installed? 
GPU?

We've tested colored geometry using surfaces and color arrays with this updated helix version - but maybe not your exact case / hardware.

**Comment by vykrum** [comment] 2020-05-16 05:01
@mjkkirschner please find below the requested info
DynamoCoreRuntime_2.7.0.8546_20200504T1500
Windows 10 (Version 1909 OS Build 18363.836)
DirectX 12
No GPU
[SolarAnalysis-ArkNova.zip](https://github.com/DynamoDS/Dynamo/files/4637834/SolarAnalysis-ArkNova.zip)

**Comment by mjkkirschner** [comment] 2020-05-16 16:07
Does your system have an integrated gpu or something like intel iris graphics? 

Or do you have display adapter disabled in the device manager?

**Comment by vykrum** [comment] 2020-05-16 16:13
Integrated GPU

**Comment by mjkkirschner** [comment] 2020-05-17 00:32
thanks @vykrum it would be helpful to know which one? dxdiag app should give a bunch of information which will be useful like shader model support etc.

**Comment by vykrum** [comment] 2020-05-17 06:58
@mjkkirschner Hope the attached file provides the required information
[DxDiag.txt](https://github.com/DynamoDS/Dynamo/files/4639790/DxDiag.txt)

**Comment by mjkkirschner** [comment] 2020-05-17 16:13
Hi @vykrum - thanks, I took a look. While that card does not support dx 12 feature level, it should not matter - but 
I think the build you are on is actually still using the older version of the helix graphics toolkit.

Can you try with one of the latest daily builds if you get a chance?

**Comment by mjkkirschner** [comment] 2020-05-31 19:03
we could not reproduce this after trying for a while on different machines, none with this exact graphics card unfortunately though.

I'm going to close this for now, please reopen if you have time to test on the latest builds.

**Closed by mjkkirschner** 2020-05-31 19:03 UTC
Labels: Graphics, crash, priority
