### ISSUE TITLE
0.81xx daily builds nothing visible

### ISSUE THREAD

**Issue by epeter-** [DynamoDS/Dynamo#4189] opened 2015-04-07 10:46 UTC
workspace does not display geomtries(solids....)
076xxx working

**Comment by kronz** [comment] 2015-04-09 02:01
sounds like your stuff @ikeough

**Comment by ikeough** [comment] 2015-04-09 06:17
@epeter- Can you attach a screen shot? The new visualization work that we've been doing uses DirectX for hardware accelerated 3D. Are you using Dynamo over remote desktop or with virtualization like VMWare?

**Comment by epeter-** [comment] 2015-04-09 07:18
screenshot were an empty screen, so nothing to show.
am running dynamo in regular enviroment win 8.1

Am 09.04.2015 um 08:17 schrieb Ian Keough:
>
> @epeter- <https://github.com/epeter-> Can you attach a screen shot? 
> The new visualization work that we've been doing uses DirectX for 
> hardware accelerated 3D. Are you using Dynamo over remote desktop or 
> with virtualization like VMWare?
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/DynamoDS/Dynamo/issues/4189#issuecomment-91125625>.
>



---
Diese E-Mail wurde von Avast Antivirus-Software auf Viren geprüft.
http://www.avast.com

**Comment by ikeough** [comment] 2015-04-09 14:17
@epeter- Can you send us the log for a dynamo session? (<users>/AppData/Roaming/Dynamo/0.8/logs. This has a few log items at the beginning that state the graphics functionality for your system. The behavior you describe happens if hardware acceleration is not available on your system. Assuming that you are using a system built in the last few years, this should not be the case. That's why I ask about remote desktop and VMWare Fusion (or Parallels). These are environments where hardware acceleration is not available. In VMWare and Parallels you can enable it.

Thanks for the feedback!

**Comment by dbaldacchino** [comment] 2015-04-09 18:54
Dynamo 0.8.0 (stable release) does not work for me in sandbox/standalone mode in Windows 8.1. @epeter- : are you seeing the same thing? The previous stable build worked for me in sandbox/standalone mode.

**Comment by epeter-** [comment] 2015-04-10 07:05
@dave: i am not running dynamo in sandbox mode.
sry

Am 09.04.2015 um 20:54 schrieb Dave Baldacchino:
>
> Dynamo 0.8.0 (stable release) does not work for me in 
> sandbox/standalone mode in Windows 8.1. @epeter- 
> <https://github.com/epeter-> : are you seeing the same thing? The 
> previous stable build worked for me in sandbox/standalone mode.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/DynamoDS/Dynamo/issues/4189#issuecomment-91326961>.
>



---
Diese E-Mail wurde von Avast Antivirus-Software auf Viren geprüft.
http://www.avast.com

**Comment by RodRecker** [comment] 2015-04-10 16:20
The logs will help us get to the bottom of it.

**Comment by dbaldacchino** [comment] 2015-04-10 17:49
No logs are being produced when I try and launch sandbox.

@epeter- , could you try launching it out of curiosity to see if it works for you in Windows 8.1? Thanks.

**Comment by ikeough** [comment] 2015-04-27 16:55
@dbaldacchino We've just added an additional component to the installer which adds further DirectX support for Dynamo. Can you try a daily build and let us know if things are improved?

**Comment by dbaldacchino** [comment] 2015-04-27 16:56
Sure, will do. Thanks Ian!

**Comment by dbaldacchino** [comment] 2015-04-27 17:27
No dice Ian, still not launching in Sandbox mode. Tried as administrator and also set compatibility mode to Windows 7 just in case. Also no logs are being written when launching Sandbox 0.8.1. Note that 0.7.5 still launches with no issues on Windows 8.1.

**Comment by dbaldacchino** [comment] 2015-04-27 18:16
This build is actually crashing; not running at all.

![dynamoerror](https://cloud.githubusercontent.com/assets/4656191/7354185/02a9ed36-ecdf-11e4-89d9-aa102fa3e9e5.png)

Object reference not set to an instance of an object.

   at Dynamo.UI.Views.LibrarySearchView.OnTopResultTargetUpdated(Object sender, DataTransferEventArgs e)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.Data.BindingExpression.OnTargetUpdated(DependencyObject d, DependencyProperty dp)
   at System.Windows.Data.BindingExpression.TransferValue(Object newValue, Boolean isASubPropertyChange)
   at System.Windows.Data.BindingExpression.Activate(Object item)
   at System.Windows.Data.BindingExpression.AttachToContext(AttachAttempt attempt)
   at System.Windows.Data.BindingExpression.MS.Internal.Data.IDataBindEngineClient.AttachToContext(Boolean lastChance)
   at MS.Internal.Data.DataBindEngine.Task.Run(Boolean lastChance)
   at MS.Internal.Data.DataBindEngine.Run(Object arg)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(Object source, Delegate method, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by RodRecker** [comment] 2015-04-27 22:39
@dbaldacchino If it is not too much hassle, can you try uninstalling Dynamo 0.7.5 and reinstalling 0.8.1 and see if that runs? We have noticed that some users have had trouble getting these two to co-exist.

**Comment by dbaldacchino** [comment] 2015-04-28 14:33
Hi Rod, uninstalled all versions, then installed today's build. Still the same problem described above. DynamoSandbox.exe doesn't work either. I used Process Monitor when launching Sandbox.exe so if you need the captured logs to help troubleshoot, please get in touch and I can send them to you. The event shown for DynamoSandbox.exe is the following:

Event Class:	File System
Operation:	CloseFile
Result:	SUCCESS
Path:	C:\Program Files\Dynamo 0.8\CSharpAnalytics.WinForms.dll
TID:	3924
Duration:	0.0000094

Then there are a few of these calls and no more evens show up after that:

Event Class:	File System
Operation:	CloseFile
Result:	SUCCESS
Path:	C:\Windows\Prefetch\DYNAMOSANDBOX.EXE-BF00125F.pf
TID:	2844
Duration:	0.0004007

Thanks.

**Comment by jnealb** [comment] 2015-04-28 14:38
@dbaldacchino Hi dave, can you please try this:

1. Navigate to C:\Users\Dave's Account\AppData\Roaming\Analytics
2. Make a backup of the file in the folder
3. Delete it from the folder
4. Load Dynamo 8.1

Thanks, Neal

**Comment by dbaldacchino** [comment] 2015-04-28 14:54
Hi Neal,

Same exact crash and dialog as before.

Object reference not set to an instance of an object.

   at Dynamo.UI.Views.LibrarySearchView.OnTopResultTargetUpdated(Object sender, DataTransferEventArgs e)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.Data.BindingExpression.OnTargetUpdated(DependencyObject d, DependencyProperty dp)
   at System.Windows.Data.BindingExpression.TransferValue(Object newValue, Boolean isASubPropertyChange)
   at System.Windows.Data.BindingExpression.Activate(Object item)
   at System.Windows.Data.BindingExpression.AttachToContext(AttachAttempt attempt)
   at System.Windows.Data.BindingExpression.MS.Internal.Data.IDataBindEngineClient.AttachToContext(Boolean lastChance)
   at MS.Internal.Data.DataBindEngine.Task.Run(Boolean lastChance)
   at MS.Internal.Data.DataBindEngine.Run(Object arg)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(Object source, Delegate method, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by ikeough** [comment] 2015-04-29 03:10
http://sharpdx.org/forum/5-api-usage/1359-direct2d-effects-class-for-win7

**Comment by ikeough** [comment] 2015-04-29 04:10
@dbaldacchino @epeter- See my upate here: https://github.com/DynamoDS/Dynamo/issues/4211

**Comment by dbaldacchino** [comment] 2015-04-29 06:01
Thanks Ian. Renaming the dll worked. It appears the search has improved on Windows 8.1, although the first few letters still lag by quite a bit and then it gets faster. Sandbox still doesn't launch. I'll test again with tomorrow's build, thanks.

**Comment by dbaldacchino** [comment] 2015-04-29 16:36
Hi Ian, just installed DynamoInstall0.8.1.20150429T0438.exe but it still has the same problems as described above. Thanks.

**Comment by dbaldacchino** [comment] 2015-05-01 15:42
Haven't been able to verify as there were no new builds since the one above. Thanks.

**Comment by dbaldacchino** [comment] 2015-05-07 14:38
No improvement in DynamoInstall0.8.1.20150507T0035.exe.

**Comment by jnealb** [comment] 2015-05-14 13:32
@dbaldacchino @epeter- Can you please try with DynamoInstall0.8.1.20150513T0845? We think we may have fixed the issue.

**Comment by dbaldacchino** [comment] 2015-05-14 13:51
@jnealb Nope sorry :( Please see #4380

**Comment by jnealb** [comment] 2015-05-14 13:54
@dbaldacchino Are you getting the error msg or does the app never load?

**Comment by dbaldacchino** [comment] 2015-05-14 14:43
Here's the sequence on first run after install (cleaned out folders manually, analytics, etc.):

![1a](https://cloud.githubusercontent.com/assets/4656191/7633913/1d28e09a-fa1d-11e4-8684-280ce94ff332.png)

![1b](https://cloud.githubusercontent.com/assets/4656191/7633939/5208dbe4-fa1d-11e4-8296-5bc7e02480fe.png)

![1c](https://cloud.githubusercontent.com/assets/4656191/7633948/5cf97ad6-fa1d-11e4-84ac-34495d46dd54.png)

Here's the sequence on second run:

![2a](https://cloud.githubusercontent.com/assets/4656191/7633961/76a1d91a-fa1d-11e4-90ff-b77062bb86bf.png)

![2b](https://cloud.githubusercontent.com/assets/4656191/7633967/7c88ffca-fa1d-11e4-9324-254ec98371b5.png)

![2c](https://cloud.githubusercontent.com/assets/4656191/7633971/7fa8daa4-fa1d-11e4-8bfd-e5c6ff58000e.png)

Here's the sequence on third run:

![3a](https://cloud.githubusercontent.com/assets/4656191/7633985/8f088dd2-fa1d-11e4-9a09-8f1095eb3cd4.png)

![3b](https://cloud.githubusercontent.com/assets/4656191/7633988/92c61b10-fa1d-11e4-90e6-5667dc4a1f18.png)

![3c](https://cloud.githubusercontent.com/assets/4656191/7634001/9a92d6c6-fa1d-11e4-8d60-fcdd0de4d167.png)

![3d](https://cloud.githubusercontent.com/assets/4656191/7634006/9d711e66-fa1d-11e4-9383-7976d30a8a35.png)

I see that @ikeough has referenced this (looked it up and came across it): https://github.com/sharpdx/SharpDX/issues/468

**Comment by jnealb** [comment] 2015-05-14 14:51
@dbaldacchino @ikeough Thanks Dave, the ball never made it across the net!

**Comment by dbaldacchino** [comment] 2015-05-14 15:13
Yeah, but at least it's moved much further than previous builds! Sandbox wouldn't even try launching before. Now here's what I get when launching the add-in inside of Revit 2015:

![4a](https://cloud.githubusercontent.com/assets/4656191/7634607/b5e492bc-fa21-11e4-8701-e51b6e192ff9.png)

![4b](https://cloud.githubusercontent.com/assets/4656191/7634606/b5debc98-fa21-11e4-824d-d055a0ac8f77.png)

![4c](https://cloud.githubusercontent.com/assets/4656191/7634605/b5de3142-fa21-11e4-83eb-be7dde324a73.png)

The add-in button is then greyed out. In previous builds it even crashed Revit, so that's an improvement. I have to close and re-open to try again (same result).

**Comment by jnealb** [comment] 2015-05-14 15:21
@dbaldacchino Can you provide the Details?

**Comment by dbaldacchino** [comment] 2015-05-14 15:27
Object reference not set to an instance of an object.

   at Dynamo.UI.Views.LibrarySearchView.OnTopResultTargetUpdated(Object sender, DataTransferEventArgs e)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.Data.BindingExpression.OnTargetUpdated(DependencyObject d, DependencyProperty dp)
   at System.Windows.Data.BindingExpression.TransferValue(Object newValue, Boolean isASubPropertyChange)
   at System.Windows.Data.BindingExpression.Activate(Object item)
   at System.Windows.Data.BindingExpression.AttachToContext(AttachAttempt attempt)
   at System.Windows.Data.BindingExpression.MS.Internal.Data.IDataBindEngineClient.AttachToContext(Boolean lastChance)
   at MS.Internal.Data.DataBindEngine.Task.Run(Boolean lastChance)
   at MS.Internal.Data.DataBindEngine.Run(Object arg)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(Object source, Delegate method, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by dbaldacchino** [comment] 2015-05-14 15:50
Not running in Windows 7 either (both sandbox and add-in).

**Comment by dbaldacchino** [comment] 2015-05-15 14:25
Tried the 05/14 build, still no change. Out of curiosity I search my drive on the Windows 8.1 system for d3dcompiler*.dll and found the following:

"C:\Program Files\Autodesk\DWG TrueView 2015 - English\D3DCompiler_46.dll"
"C:\Program Files\Autodesk\Navisworks 2015 64 bit Exporter Plug-ins\d3dcompiler_46.dll"
"C:\Program Files\Autodesk\Navisworks Manage 2015\d3dcompiler_46.dll"
"C:\Program Files\Autodesk\Navisworks Manage 2015\Loaders\Inv\Inventor Server\Bin\d3dcompiler_46.dll"
"C:\Program Files\Autodesk\Navisworks Manage 2015\Loaders\Rx\d3dcompiler_46.dll"
"C:\Program Files\Common Files\Autodesk Shared\Navisworks\2015\ActiveX Redistributable\d3dcompiler_46.dll"
"C:\Program Files\Autodesk\DWG TrueView 2015 - English\AcWebBrowser\d3dcompiler_46.dll"
"C:\Program Files\Autodesk\DWG TrueView 2015 - English\AcWebBrowser\d3dcompiler_43.dll"
"C:\Windows\SysWOW64\D3DCompiler_41.dll"
"C:\Windows\System32\D3DCompiler_43.dll"
"C:\Windows\SysWOW64\D3DCompiler_43.dll"
"C:\Program Files (x86)\Google\Chrome\Application\42.0.2311.152\d3dcompiler_47.dll"
"C:\Program Files (x86)\Google\Chrome\Application\42.0.2311.135\d3dcompiler_47.dll"
"C:\Windows\WinSxS\x86_microsoft-windows-directx-d3dcompiler_31bf3856ad364e35_6.3.9600.17415_none_7e3e79b737706a8a\D3DCompiler_47.dll"
"C:\Windows\WinSxS\amd64_microsoft-windows-directx-d3dcompiler_31bf3856ad364e35_6.3.9600.17415_none_da5d153aefcddbc0\D3DCompiler_47.dll"
"C:\Users\david.baldacchino\AppData\Roaming\Dropbox\bin\D3DCompiler_43.dll"
"C:\Windows\SysWOW64\D3DCompiler_47.dll"
"C:\Windows\WinSxS\x86_microsoft-windows-directx-d3dcompiler_31bf3856ad364e35_6.3.9600.17672_none_7dfa9d1d37a3c079\D3DCompiler_47.dll"
"C:\Windows\System32\D3DCompiler_47.dll"
"C:\Windows\WinSxS\amd64_microsoft-windows-directx-d3dcompiler_31bf3856ad364e35_6.3.9600.17672_none_da1938a0f00131af\D3DCompiler_47.dll"
"C:\Windows\WinSxS\x86_microsoft-windows-directx-d3dcompiler_31bf3856ad364e35_6.3.9600.16384_none_7df1dedb37a9fe02\D3DCompiler_47.dll"
"C:\Windows\WinSxS\amd64_microsoft-windows-directx-d3dcompiler_31bf3856ad364e35_6.3.9600.16384_none_da107a5ef0076f38\D3DCompiler_47.dll"
"C:\Program Files (x86)\Windows Live\Photo Gallery\D3DCOMPILER_46.dll"
"C:\Program Files\Autodesk\Revit 2015\d3dcompiler_46.dll"
"C:\Program Files\Autodesk\Navisworks Manage 2015\NOW64\d3dcompiler_46.dll"

**Comment by ikeough** [comment] 2015-05-20 19:18
@epeter- and @dbaldacchino We believe we've fixed the direct x exceptions with https://github.com/DynamoDS/Dynamo/pull/4498. Can you both please test with the daily builds and confirm?

**Comment by dbaldacchino** [comment] 2015-05-20 19:31
Thanks Ian, once I see a new build I'll test and report back.

**Comment by dbaldacchino** [comment] 2015-05-21 13:57
Sandbox is running! Upon first launch it stopped running and locked up like usual (feeling of dismay), but upon running a second time, it opened without a hitch. I can confirm it is running in Revit 2015 as well. BTW I like how the axes are colored to help with orienting oneself in the background. Thanks!

**Comment by RodRecker** [comment] 2015-05-21 14:43
@dbaldacchino Thank you David for your persistence and patience on this one!

**Comment by ikeough** [comment] 2015-05-21 14:50
@dbaldacchino Excellent. If the stall continues on startup, let us know. I'm closing this one for now.

**Closed by ikeough** 2015-05-21 14:50 UTC
Labels: Graphics
