### ISSUE TITLE
Can't place nodes immediately after opening graph, "running started" from Dynamo 2.2.1.5175

### ISSUE THREAD

**Issue by ariccb** [DynamoDS/Dynamo#10118] opened 2019-11-06 23:01 UTC
# Issue Description
Please fill in the following information to help us reproduce the issue:
When i open a graph, or even make a new graph, i can search for nodes, but not place any. Automatic is chosen already, and it says "running started"
### What did you do?
I'm trying to figure out how to reinstall Dynamo for Revit 2020 and can't find anything. 

### What did you expect to see?
I expected to be able to place nodes, and to be able to change from automatic to manual mode
### What did you see instead?
locked mode changer, and unable to place any nodes from either right click search, or from library search.

### What packages or external references (if any) were used?
n/a - error is from opening new graph 

### Stack Trace
```
(From the Dynamo crash window select 'Details' -> 'Copy' and paste here)
```

---
OS: `Microsoft Windows NT 10.0.15063.0`
CLR: `4.0.30319.42000`
Dynamo: `2.2.1.5175`

**Comment by QilongTang** [comment] 2019-11-06 23:03
hi @ariccb , can you describe in what case you need to reinstall Dynamo in Revit 2020? Dynamo should come with it and be updated with Revit patches, you can always reinstall Revit to achieve that but that may be an overkill.

**Comment by ariccb** [comment] 2019-11-06 23:05
@QilongTang  I've tried closing and reopening dynamo within revit to 'reset' dynamo, but the same issue keeps happening. I'll try closing out of everything and doing a computer reset to see if anything changes. I'll report back.

**Comment by QilongTang** [comment] 2019-11-06 23:09
@ariccb It also seems the graph you are opening is set to **AutoRun** mode, that sometimes cause trouble in Revit context. A workaround could be that you turn it back to **Manual** mode and run it when you are ready. You can do that by opening the dyn with text editor and edit this
```Json
"RunType": "Automatic",
```
Update to 
```Json
"RunType": "Manual",
```

**Comment by ariccb** [comment] 2019-11-06 23:23
@QilongTang Just tried that, and it didn't solve anything. It took ages to open the graph for some reason, i thought i froze for a sec. Then it opened, and "manual" was selected and no more "running started" was shown. Tried to insert some nodes, but still having the same issue, where it won't place any in the workspace. I'm not able to switch from graph to 3d view either, and none of the tabs work (file, edit, view, packages, settings, help, !) I'm only able to search from library right now, scrolling through the list works, but that's about it. I've attached the graph to see if that's the problem, but i think it's my installation. 
[rjcCopyOpeningsFromLink_2.0.dyn.zip](https://github.com/DynamoDS/Dynamo/files/3817144/rjcCopyOpeningsFromLink_2.0.dyn.zip)

**Comment by ariccb** [comment] 2019-11-06 23:24
@QilongTang strangely, when i close the graph so that the Dynamo "home landing page" is visible, the tabs (home, edit, view etc.) work. Only when i have a .dyn file open is it having issues. It also seems like it's running very slowly.

**Comment by ariccb** [comment] 2019-11-06 23:26
I just tried opening an existing .dyn file, and it's clearly broken - none of the nodes showed up, but all of the splines connecting them are there. 
![Broken_Dynamo_1](https://user-images.githubusercontent.com/48956351/68346773-3913d080-00b2-11ea-8637-17e39c9af67b.png)

**Comment by QilongTang** [comment] 2019-11-06 23:35
@ariccb Our team has been fighting this issue for weeks. I feel sorry for your case but you are actually not the only guy seeing the nodes missing. I am almost sure some strange things on either another Revit addin disturbing Dynamo or some load time issue with all the packages on our end.

Would you do me a favor if you can, remove all other revit addins and see if this still reproduces? 
FYI: @zeusongit this is the bug you are working on, please watch this thread.

**Comment by ariccb** [comment] 2019-11-06 23:36
What's the best way to 'remove all other revit addins'? Can i save the files in another folder to re-add them later? (i just spent the greater part of a day finding and installing them, moving from revit 2019 to 2020. )

**Comment by mjkkirschner** [comment] 2019-11-06 23:39
a list of the addins would be very useful for us as well to try to reproduce this.

@zeusongit also please take note of the packages shown in the image above.

**Comment by QilongTang** [comment] 2019-11-06 23:43
@ariccb Would you follow this link: https://knowledge.autodesk.com/support/revit-products/learn-explore/caas/sfdcarticles/sfdcarticles/How-to-Disable-Add-Ins-for-Revit-Products.html

**Comment by ariccb** [comment] 2019-11-06 23:44
![List_of_Addins_Broken_Dynamo_2](https://user-images.githubusercontent.com/48956351/68347497-5c3f7f80-00b4-11ea-91ee-e122712f30e9.png)
![List_of_Addins2_Broken_Dynamo_2](https://user-images.githubusercontent.com/48956351/68347583-a9bbec80-00b4-11ea-8835-8bb574a2991e.png)
![List_of_Addins3_Broken_Dynamo_2](https://user-images.githubusercontent.com/48956351/68347605-bd675300-00b4-11ea-9e25-b6c7cbc88db3.png)

**Comment by ariccb** [comment] 2019-11-06 23:46
![List_of_Addins4_Broken_Dynamo_2](https://user-images.githubusercontent.com/48956351/68347674-f8698680-00b4-11ea-921d-95cde27995e2.png)

**Comment by ariccb** [comment] 2019-11-06 23:50
Ok it's definitely an issue with one of the addins in my first photo, (i'll post it below again for easy reference), because after moving the addin files to a temporarily disable them, my dynamo is working swimmingly again. 
![List_of_Addins_Broken_Dynamo_2](https://user-images.githubusercontent.com/48956351/68347853-7332a180-00b5-11ea-806d-f7cee1a82a1e.png)

**Comment by ariccb** [comment] 2019-11-06 23:51
Here is my dynamo graph now, same one as before that was just showing the splines. 
![Broken_Dynamo_2](https://user-images.githubusercontent.com/48956351/68347915-aaa14e00-00b5-11ea-910f-827e001aea02.png)

**Comment by QilongTang** [comment] 2019-11-06 23:55
@ariccb Glad for you! We have other reports saying similar thing, some other addin may cause conflicts with Dynamo and Dynamo will be completely non useful in that case.. To unblock you, hopefully you can enable what you need to continue your daily work. If you end up narrowing it down, let us know so we can contract the add in author and figure out ways. Thank you for reaching out to us, much appreciated!

**Comment by ariccb** [comment] 2019-11-07 00:04
@QilongTang i just tried adding the .addin files one by one back into the ProgramData>Autodesk>Revit>Addins>2020 folder, and none of them caused my Dynamo to stop working. I'll have to test this more if the problem rears it's head again
Thanks for the help, anywho!

**Comment by ariccb** [comment] 2019-11-15 14:09
@QilongTang I think i might have narrowed down which Add-in might be messing up my Dynamo working. I believe it's the Tools4BIM dock, provided by AGACAD. We use their Wood+ Wall software, and when i have the folder "Tools4BimDock.bundle" as well as the "SmartRevitDock.addin" file in the Revit 2020 addins folder it seems to break functionality while using Dynamo.

**Comment by QilongTang** [comment] 2019-11-15 16:22
@ariccb Thank you so much for narrowing it down. A good step forward. FYI: @mjkkirschner @smangarole

**Comment by mjkkirschner** [comment] 2019-11-15 22:14
hmm - 

![Screen Shot 2019-11-15 at 5 10 08 PM](https://user-images.githubusercontent.com/508936/68979209-e8dff100-07ca-11ea-988e-5823975002f3.png)


when this addin is not loaded - Dynamo's version of `system.windows.interactivity`(2.0) - is loaded AFTER archilab's version (3.0) - 

when this addin is installed the order is reversed - I've examined this addin and it also ships a 2.x version of `system.windows.interactivity` - oddly, Revit's 3.x version (which is also ships) 🤷‍♂ - is never loaded EVER. (that I can find - I clicked a lot of buttons)....

I will continue investigating - but I can definitely reproduce it now. FYI @zeusongit

**Comment by mjkkirschner** [comment] 2019-11-15 22:32
after removing archilab:

![Screen Shot 2019-11-15 at 5 28 15 PM](https://user-images.githubusercontent.com/508936/68980052-54c35900-07cd-11ea-94df-3cf252969f92.png)

now only dynamo's `system.windows.interactivity.dll` is loaded - it's still loaded early by the other addin - I'm assuming because our assembly resolve handler is loaded first or some such...

### Hypothesis:
 this bug occurs when any addin (or anything else) causes an older version of `system.windows.interactivity` to be loaded first into the process - and then a newer (major version difference) version is loaded later. This is a bit unintuitive, I would have though the opposite order would cause issues.

... thinking of solutions.

**Comment by mjkkirschner** [comment] 2019-11-15 23:07
![Screen Shot 2019-11-15 at 6 03 16 PM](https://user-images.githubusercontent.com/508936/68981681-4166bc80-07d2-11ea-9817-6a1ccd00b094.png)

I tried recompiling Dynamo against the Revit supplied 3.x version of windows.interactivty - this works - and since archilab references the same version it the already loaded assembly is referenced.

likely the 3 best fixes are:

* get rid of this dependency, we use it in one small place and can likely figure something else out.
* consult with Revit team to add an assembly bind redirect for this assembly to Revit's app config to always direct to their version.
* update our version to align with Revit's - they seem to be compatible as I had to make 0 changes in Dynamo except for recompiling.

I think the real issue here occurs when two of these versions are loaded in the same process and it causes some kind of type identity failures - I think parsing out exactly why loading one version over the other first is going to be very hard.

**Comment by QilongTang** [comment] 2019-11-16 00:13
@mjkkirschner I remember @zeusongit had shown me a change to preload `system.windows.interactivity` always from Revit in DynamoRevit, similar to how we address the bug for AvalonEdit. Seems that would be a good plus as well?

**Comment by mjkkirschner** [comment] 2019-11-16 20:17
@QilongTang that won't help - because this other addin is loading the dll before Dynamo does - since Dynamo requires pressing the Dynamo button to start.

**Comment by ariccb** [comment] 2019-11-21 17:10
I asked AGACAD for a solution to their addin causing the issue, and they sent this as a solution: 

"Could you try to rename or move this folder: C:\Users\%username%\AppData\Roaming\TOOLS 4 BIM\2020\Smart Browser Free
We suspect that this folder causing this issue." 

Changing the folder name seems to have resolved the problem for me.

**Comment by QilongTang** [comment] 2019-11-22 01:26
@ariccb Thanks so much! Did they mention any reason?

**Comment by ariccb** [comment] 2019-11-22 01:42
@QilongTang no, there was no explanation as to why that specific folder might be causing the problem. I'll ask.

**Comment by QilongTang** [comment] 2019-12-04 20:44
@ariccb Thank you for chasing so far in this problem. Your experience in this case will help other Reviter for sure. Enjoy Dynamo! I am closing this issue for now.

**Closed by QilongTang** 2019-12-04 20:44 UTC
Labels: 2.x, bug, tracked
