### ISSUE TITLE
Crash report from Dynamo 2.3.0.5885

### ISSUE THREAD

**Issue by ShashankBagane** [DynamoDS/Dynamo#12299] opened 2021-11-18 08:58 UTC
# Issue Description
Please fill in the following information to help us reproduce the issue:
Automate dimension between linked elements with reference to model line. 
### What did you do?
Trying to automate dimension through dynamo.

### What did you expect to see?
Output is null

### What did you see instead?
Dimension

### What packages or external references (if any) were used?
Genius Loci

### Stack Trace
```
(From the Dynamo crash window select 'Details' -> 'Copy' and paste here)
```
Unable to locate managed object for given dsObject.

   at ProtoFFI.CLRObjectMarshaler.CreateCLRObject(StackValue dsObject, Context context, Interpreter dsi, Type type)
   at ProtoFFI.CLRObjectMarshaler.UnMarshal(StackValue dsObject, Context context, Interpreter dsi, Type expectedCLRType)
   at ProtoFFI.DisposeFunctionPointer.Execute(Context c, Interpreter dsi, List`1 s)
   at ProtoCore.Lang.FFIFunctionEndPoint.Execute(Context c, List`1 formalParameters, StackFrame stackFrame, RuntimeCore runtimeCore)
   at ProtoCore.CallSite.ExecWithZeroRI(List`1 functionEndPoint, Context c, List`1 formalParameters, StackFrame stackFrame, RuntimeCore runtimeCore, SingleRunTraceData previousTraceData, SingleRunTraceData newTraceData, FunctionEndPoint finalFep)
   at ProtoCore.CallSite.Execute(List`1 functionEndPoint, Context c, List`1 formalParameters, List`1 replicationInstructions, StackFrame stackFrame, RuntimeCore runtimeCore)
   at ProtoCore.CallSite.DispatchNew(Context context, List`1 arguments, List`1 partialReplicationGuides, DominantListStructure domintListStructure, StackFrame stackFrame, RuntimeCore runtimeCore)
   at ProtoCore.DSASM.Executive.Callr(Int32 blockDeclId, Int32 functionIndex, Int32 classIndex, Boolean& explicitCall, Boolean isDynamicCall, Boolean hasDebugInfo)
   at ProtoCore.DSASM.Heap.GCDisposeObject(StackValue svPtr, Executive exe)
   at ProtoCore.DSASM.Heap.Sweep()
   at ProtoCore.DSASM.Heap.SingleStep(Boolean forceGC)
   at ProtoCore.DSASM.Heap.FullGC(IEnumerable`1 gcroots, Executive exe)
   at ProtoScript.Runners.LiveRunner.ApplyUpdate()
   at ProtoScript.Runners.LiveRunner.CompileAndExecuteForDeltaExecution(List`1 astList)
   at ProtoScript.Runners.LiveRunner.SynchronizeInternal(GraphSyncData syncData)
   at ProtoScript.Runners.LiveRunner.UpdateGraph(GraphSyncData syncData)
   at Dynamo.Scheduler.UpdateGraphAsyncTask.HandleTaskExecutionCore()
   at Dynamo.Scheduler.AsyncTask.Execute()
---
OS: `Microsoft Windows NT 10.0.19042.0`
CLR: `4.0.30319.42000`
Dynamo: `2.3.0.5885`

**Comment by denizmaral** [comment] 2022-05-23 14:49
I face also same problem..

**Comment by denizmaral** [comment] 2022-05-23 15:46
[GitHub_Crash.zip](https://github.com/DynamoDS/Dynamo/files/8756060/GitHub_Crash.zip)


If you run script for the first time, it will produce no error. After editing Python Node it will show that stupid error.

**Comment by denizmaral** [comment] 2022-05-23 16:28
I found the problem. In my case it was because of Clockwork Node ProjectParameter.ByCategory.

**Comment by aparajit-pratap** [comment] 2022-05-26 15:06
@denizmaral thanks for sharing the files, but I'm unable to reproduce the crash on editing the python node as you described. Also, I don't understand your comment about the `ProjectParameter.ByCategory` in clockwork. I couldn't find the node being used in the .dyn graph you shared. Would you like to email me directly at aparajit.pratap@autodesk.com so we could discuss this in some more detail?

**Comment by denizmaral** [comment] 2022-05-26 21:01
Hello @aparajit-pratap it's that node from Clockwork:
https://github.com/andydandy74/ClockworkForDynamo/blob/master/nodes/2.x/Document.ProjectParametersByCategory.dyf

Wenn you launch the skript, it works without problem. If you change anything in Python node and launch it again, it shows you that error.

**Comment by denizmaral** [comment] 2022-05-26 21:56
Update: it is because of Category.FromInput from Clockwork. It will get updated soon.

**Comment by aparajit-pratap** [comment] 2022-05-31 19:20
Unfortunately, I'm unable to reproduce the crash in 2.15. The graph doesn't seem to work correctly either but that seems to be an issue with individual nodes/graph. Closing for now. Happy to reopen if and when there is further information we can use to reproduce this in the future.

**Closed by aparajit-pratap** 2022-05-31 19:20 UTC
