### ISSUE TITLE
Group Titles: Words Not Wrapping as Expected

### ISSUE THREAD

**Issue by Amoursol** [DynamoDS/Dynamo#7388] opened 2016-12-02 12:09 UTC
If this issue is with Dynamo for Revit, please post your issue on the [Dynamo for Revit Issues page](https://github.com/DynamoDS/DynamoRevit/issues).

If this issue is **not** a bug report or improvement request, please check the [Dynamo forum](https://forum.dynamobim.com/), and start a thread there to discuss your issue.

## Dynamo version

1.2

## Operating system

Windows 10

## What did you do? 

Have a group with one single node in it, have written a rather extensive title and changed the font size so that some of the words would technically be larger than the space afforded by the singular node of which the group wraps.

![image](https://cloud.githubusercontent.com/assets/12857357/20833524/19b018ae-b888-11e6-92dc-c6ee08640557.png)

## What did you expect to see?

I expected the larger of the following values to dictate the size of the group:

Nodes OR longest word.

## What did you see instead?

The node dictates the size of the group, so that words are truncated and 'wrapped' down to the next line when they fall outside the bounds of this.

**Comment by andydandy74** [comment] 2016-12-02 17:18
Duplicate of #6097

**Comment by Amoursol** [comment] 2016-12-02 17:29
Closed as duplicate exists. Thanks Andreas.

**Closed** 2016-12-02 17:28 UTC
