### ISSUE TITLE
Element types TO All elements of type - French 

### ISSUE THREAD

**Issue by jmcouffin** [DynamoDS/Dynamo#8165] opened 2017-09-08 11:14 UTC
If this issue is with Dynamo for Revit, please post your issue on the [Dynamo for Revit Issues page](https://github.com/DynamoDS/DynamoRevit/issues).

If this issue is **not** a bug report or improvement request, please check the [Dynamo forum](https://forum.dynamobim.com/), and start a thread there to discuss your issue.

## Dynamo version

1.3.1
## Operating system

Win10

## What did you do? 

Run a graph from the nodes: Element Types (TextNote) -> All Elements of Type in a french revit

## What did you expect to see?

List all text notes in the projet

## What did you see instead?

Null - Operation failed

It is working when launching revit in english and running the same graph
![fr](https://user-images.githubusercontent.com/7872003/30209276-8ae9ac4c-9497-11e7-8843-6600fa551017.png)
![eng](https://user-images.githubusercontent.com/7872003/30209277-8aef183a-9497-11e7-9386-1fd6574d0435.png)

**Comment by andydandy74** [comment] 2017-09-11 09:42
Duplicate of https://github.com/DynamoDS/DynamoRevit/issues/1626
Please close this issue.
Also, in the future please post DynamoRevit-related issues in the DynamoRevit repo.

**Closed** 2017-09-11 09:43 UTC
