### ISSUE TITLE
Description error - IndexGroup.ByVertices

### ISSUE THREAD

**Issue by vykrum** [DynamoDS/Dynamo#7075] opened 2016-08-24 14:53 UTC
## Dynamo version

1.1.1.2346
## Operating system

Windows 10
## What did you see instead?

![issue-20160824-1](https://cloud.githubusercontent.com/assets/5621624/17935328/8a52d4e6-6a38-11e6-8d78-b7758a14e37d.png)

**Comment by mjkkirschner** [comment] 2016-08-24 14:57
@vykrum thanks for catching this.

**Comment by josols** [comment] 2016-10-31 12:22
Another thing: It does store four indices? I get random D values when I'm only feeding the node three indexlists?? 
![image](https://cloud.githubusercontent.com/assets/7080648/19854035/19c45fa0-9f6d-11e6-8104-e5bbdcb21f5c.png)

**Comment by aparajit-pratap** [comment] 2018-05-17 15:42
Duplicate of https://github.com/DynamoDS/Dynamo/issues/8710

**Closed** 2018-11-29 15:51 UTC
