### ISSUE TITLE
Dynamo crashes - open definition or saving/exit edit custom node

### ISSUE THREAD

**Issue by tothom** [DynamoDS/Dynamo#5218] opened 2015-09-02 10:38 UTC
Hi

Dynamo crashes when exiting the edit custom node window if I edit the custom node from within a definition. If I open the custom node without opening a definition first it also crashes if I have done changes to the custom node.

Dynamo also crashes if I close a definition and open second one. Upon opening the second it crashes.

It only applies to some custom nodes and definitions. I have a definition I can send if somebody wants it. The custom node "Element.Location" from Clockwork crashes as described above.

Tell me if you need more information.

Thanks,
Thomas

**Comment by tothom** [comment] 2015-09-03 07:44
Hi
I'm tried on Dynamo 8.1, 8.2 and 0.8.3.20150901T1250 on Revit 2015 UR8. It crashes the same way all the time.
I think it is related to groups.
When ungrouping all groups and then run the definition once, the crashes are gone, and I can open and close the files as normal.
Thomas

**Comment by jnealb** [comment] 2015-09-03 15:14
@tothom Are you running in a localized version of Windows and Revit (not English)?

**Comment by monikaprabhu** [comment] 2015-09-04 05:42
@tothom - if its specific nodes then you can upload somewhere and send us the link - may be upload in the package manager ?

**Comment by tothom** [comment] 2015-09-04 07:40
@jnealb Both Revit and Windows are in the english language, but the system locale is no;Norwegain.

**Comment by tothom** [comment] 2015-09-04 07:48
Hi
I don't think it's related to custom nodes. I think it is related to groups.
Crash report:
Object reference not set to an instance of an object.

   at Dynamo.Views.WorkspaceView.OnMouseMove(Object sender, MouseEventArgs e)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
   at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(Object source, Delegate method, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by tothom** [comment] 2015-09-04 07:57
Hi
This recreates the crash on my computer:
1. New definition
2. Place a node in the definition
3. Group the node
4. Save definition
5. Close definition
6. Open definition again... crash...

It does not matter which node I create. If I don't group the node there is no crash. If I group the node and then ungroup Dynamo still crashes upon reopening the definition.

Thomas

**Comment by jnealb** [comment] 2015-09-10 20:04
@tothom We have a working theory of what is going on and are tracking it with MAGN-8387.

**Comment by ikeough** [comment] 2016-05-03 05:02
Internal issue has been marked as can't reproduce. Please re-open if you're still seeing this in newer builds.

**Closed by ikeough** 2016-05-03 05:02 UTC
Labels: Can't Reproduce
