### ISSUE TITLE
Replication in Range Node.

### ISSUE THREAD

**Issue by JacobSmall** [DynamoDS/Dynamo#9974] opened 2019-09-12 03:00 UTC
## Dynamo version

2.1

## Operating system

Windows 10

## What did you do? 

Attempted to use cross product lacing to build series of ranges - say count from 0..2 to 4..5.

## What did you expect to see?

[[[0,1,2,3,4],[1,2,3,4],[2,3,4]],[[0,1,2,3,4,5],[1,2,3,4,5],[2,3,4,5]]]

## What did you see instead?

Shortest lacing by default, in all cases. [[0,1,2,3,4],[1,2,3,4,5]]. List levels also have no impact, almost as if replication wasn't implemented. Unclear why this would be needed, but if the intent is to not have replication then the interface for it should be removed as it is with List.Create and If nodes (the often documented issues there may be related). Issue persists as far back as 0.9.1. Sequence node may have a similar issue.

**Comment by QilongTang** [comment] 2019-09-12 05:01
@JacobSmall I believe it is indeed not implemented for Range node. @saintentropy has reported similar issues before. FYI: @mjkkirschner @Amoursol

**Comment by mjkkirschner** [comment] 2019-09-25 02:40
@aparajit-pratap has filed this internally, it's not as easy to fix as we thought as range expressions don't seem to handle replication - 
there are a few solutions I think that Aparajit suggested

* range expressions in the VM should natively handle replication
* range node should replicate and create multiple function calls which create multiple range expressions
* remove lacing option from range node.

**Comment by aparajit-pratap** [comment] 2019-09-25 14:06
In the case of the 'If' node, which compiles to an inline conditional statement, replication guides are supported natively in the language, which is why it is easy to enable lacing on the `If` node, which is not the case with the `Range` node unfortunately. It will require additional language support. Task has been created for tracking.

**Comment by Amoursol** [comment] 2023-07-07 18:27
Duplicate of https://github.com/DynamoDS/Dynamo/issues/11684

**Closed by Amoursol** 2023-07-07 18:27 UTC
Labels: Improvement, 2.x, tracked
