### ISSUE TITLE
Custom node demo HelloNodeModel can't load

### ISSUE THREAD

**Issue by kehehee1** [DynamoDS/Dynamo#7513] opened 2017-01-16 07:57 UTC
## Dynamo version
2.0

## Operating system
Windows 7

## What did you do? 
I download a custom node demo from [here](https://github.com/teocomi/HelloDynamo), I put the HelloNodeModel.dll in the nodes folder of Dynamo.

## What did you expect to see?
Dynamo load the dll.

## What did you see instead?
Dynamo throws the Exception as follows:

Could not load types.
System.Reflection.ReflectionTypeLoadException:
Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more information.
   at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
   at System.Reflection.Assembly.GetTypes()
   at Dynamo.Models.NodeModelAssemblyLoader.LoadNodesFromAssembly(Assembly assembly, String context, List`1 nodeModels, List`1 migrationTypes) in c:\Users\sgb\Downloads\Dynamo-master\src\DynamoCore\Core\NodeModelAssemblyLoader.cs:line 225
Dll Load Exception:
System.TypeLoadException: GenericArguments[0], 'HelloDynamo.HelloNodeModel.HelloGui', on 'Dynamo.Wpf.INodeViewCustomization`1[T]' violates the constraint of type parameter 'T'.
Duplicate migration type registered for SunPathDirection
Dynamo will use the package manager server at : https://www.dynamopackages.com
DynamoPackageManager (id: FCABC211-D56B-4109-AF18-F434DFE48139) extension is added
Backup files timer is started with an interval of 60000 milliseconds
RENDER : Rendering Tier: 2
RENDER : Pixel Shader 3 Supported: True
RENDER : Pixel Shader 4 Supported: False
RENDER : Software Effect Rendering Supported: True
RENDER : Maximum hardware texture size: 8192,8192
DynamoManipulationExtension (id: 58B0496A-E3F8-43D9-86D2-94823D1D0F98) view extension is added
PackageManager (id: 4b6f94ba-3248-4311-8ac4-fd7f660abbfb) view extension is added
NotificationsExtension (id: ef6cd025-514f-44cd-b6b1-69d9f5cce004) view extension is added
Welcome to Dynamo!
00:00:00.6840346 elapsed for loading Dynamo main window.
There was an error while finding node view customizations for HelloNodeModel, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null. Contact the author of this assembly for more information.
Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more information.

**Comment by alfarok** [comment] 2017-10-30 17:20
@kehehee1  I believe this is due to API changes in Dynamo 2.0.  The current samples are built against 1.3 so you need to be running Core 1.3 to load them properly as opposed to a source build or daily build.  We do have a task around updating the samples to support Core 2.0 which will be completed before the official release.

**Comment by mjkkirschner** [comment] 2017-10-30 17:27
@kehehee1 please note we do not maintain these samples, we maintain the DynamoSamples at:
https://github.com/DynamoDS/DynamoSamples

If you wish to use these you should report this error to the author.

**Comment by alfarok** [comment] 2017-10-30 17:31
oops @mjkkirschner is correct but the cause should be the same.  You will experience the same issue when building/loading the dynamo samples which include NodeModel examples.  I am going to close this issue since it is referring to an outside repo and we are currently tracking dynamo samples update.

**Closed by alfarok** 2017-10-30 17:31 UTC

**Comment by jnealb** [comment] 2017-10-30 17:37
The task for updating DynamoSamples is QNTM-2145.
