### ISSUE TITLE
Dynamo crashes with the error "Object reference not set to an instance of an object"

### ISSUE THREAD

**Issue by sanosji** [DynamoDS/Dynamo#5838] opened 2015-12-13 19:26 UTC
Object reference not set to an instance of an object.

   at Dynamo.UI.Views.LibrarySearchView.OnTopResultTargetUpdated(Object sender, DataTransferEventArgs e)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.Data.BindingExpression.OnTargetUpdated(DependencyObject d, DependencyProperty dp)
   at System.Windows.Data.BindingExpression.TransferValue(Object newValue, Boolean isASubPropertyChange)
   at System.Windows.Data.BindingExpression.Activate(Object item)
   at System.Windows.Data.BindingExpression.AttachToContext(AttachAttempt attempt)
   at System.Windows.Data.BindingExpression.MS.Internal.Data.IDataBindEngineClient.AttachToContext(Boolean lastChance)
   at MS.Internal.Data.DataBindEngine.Task.Run(Boolean lastChance)
   at MS.Internal.Data.DataBindEngine.Run(Object arg)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(Object source, Delegate method, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by aparajit-pratap** [comment] 2015-12-14 03:08
@sanosji could you describe the actions you were performing in Dynamo to reproduce this crash. A screenshot will be helpful. Thanks.

**Comment by smangarole** [comment] 2017-06-19 18:51
We have released a new version of Dynamo since this issue was opened. The issue has been waiting for feedback for almost a year. Closing due to these reasons. Please reopen if this issue resurfaces.

**Closed by smangarole** 2017-06-19 18:51 UTC
Labels: Blocker, Bug, Waiting for feedback
