### ISSUE TITLE
element.GetParameterValueByName error with Area elements

### ISSUE THREAD

**Issue by JamesEMooreAIA** [DynamoDS/Dynamo#4308] opened 2015-04-22 19:24 UTC
![2015-04-22_dynamo0 8_element_getparametervaluebyname](https://cloud.githubusercontent.com/assets/12073368/7283148/2484277a-e8fa-11e4-8412-0596032a4d40.png)

Routine worked in Dynamo 7.5.  Pulls areas of all objects of "Areas" category in Revit.  Same set of nodes works without error when pulling objects categorized as "Rooms".

**Comment by dbaldacchino** [comment] 2015-04-27 17:01
Hi James, I'm seeing some related issues as well (see #4310 ). I just started a new graphy in 0.8 so I'm not sure this worked properly before.

**Comment by ksobon** [comment] 2017-05-30 00:44
@JamesEMooreAIA @dbaldacchino This was caused by the fact that Areas were not handled before. Now (Dynamo 1.3) they should be fine: 

![image](https://cloud.githubusercontent.com/assets/529781/26564507/9407709e-44af-11e7-8f78-8fbe0af092e4.png)

cc: @kronz can we close this?

**Comment by dbaldacchino** [comment] 2017-05-30 15:28
I am now able to retrieve the Area parameter value from an Area object.

**Comment by jnealb** [comment] 2017-05-30 15:30
@dbaldacchino Can we close this?

**Comment by dbaldacchino** [comment] 2017-05-30 15:31
Looks like it, thanks @jnealb & @ksobon

**Closed** 2017-05-30 15:33 UTC
Labels: Bug, Revit
