### ISSUE TITLE
Zero z-coordinate in plane normal results in failed Solid.BySweep

### ISSUE THREAD

**Issue by Dewb** [DynamoDS/Dynamo#4598] opened 2015-05-28 19:49 UTC
Create a python node with the following code. It produces the warning "Unable to update solid by sweep : SWEEP_INVALID_RESULT -- Sweeping could not create a valid body." If the zero Z-coordinate in the normal vector, in the line below the comment, is changed to a nonzero value, the sweep succeeds. 

```c#
arc = 360.0 / 14.0;
theta1 = 0..360..arc;
theta2 = theta1 + arc/2.0;
theta3 = theta1 + arc;
r1 = 120;
r2 = 140;
p1 = Point.ByCoordinates(r1 * Math.Cos(theta1), r1 * Math.Sin(theta1), 0);
p2 = Point.ByCoordinates(r2 * Math.Cos(theta2), r2 * Math.Sin(theta2), 0);
p3 = Point.ByCoordinates(r1 * Math.Cos(theta3), r1 * Math.Sin(theta3), 0);
a = Arc.ByThreePoints(p1, p2, p3);
// change the 0 here to a nonzero value, then all the sweeps work
plane = Plane.ByOriginNormal(p2, Vector.ByCoordinates(p3.X-p1.X, p3.Y-p1.Y, 0.0));
profile = Rectangle.ByWidthHeight(plane, 5, 5);
solid = Solid.BySweep(profile, a);
```

**Comment by monikaprabhu** [comment] 2015-06-06 15:46
@Dewb - thanks for reporting the same - We would need to debug into the Geometry api to check what is the problem here. Will check with development and get back. @aparajit-pratap - could you please take a look at this ? I'm filing MAGN-7583 to track the issue.

**Comment by Benglin** [comment] 2015-07-28 02:23
Hello @Dewb, You can try below script. It is working on latest build.
The problem was with size of Rectangle. I changed it to 1 X 1 and its working now.

```csharp
arc = 360.0 / 14.0;
theta1 = 0..360..arc;
theta2 = theta1 + arc/2.0;
theta3 = theta1 + arc;
r1 = 120;
r2 = 140;
p1 = Autodesk.Point.ByCoordinates(r1 * Math.Cos(theta1), r1 * Math.Sin(theta1), 0);
p2 = Autodesk.Point.ByCoordinates(r2 * Math.Cos(theta2), r2 * Math.Sin(theta2), 0);
p3 = Autodesk.Point.ByCoordinates(r1 * Math.Cos(theta3), r1 * Math.Sin(theta3), 0);
a = Autodesk.Arc.ByThreePoints(p1, p2, p3);
// change the 0 here to a nonzero value, then all the sweeps work
plane = Autodesk.Plane.ByOriginNormal(p2, Vector.ByCoordinates(p3.X-p1.X, p3.Y-p1.Y, 0.0));
profile = Rectangle.ByWidthLength(plane, 1,1);
solid = Solid.BySweep(profile, a);
```

**Comment by monikaprabhu** [comment] 2015-07-29 08:41
@Dewb, @Benglin - I could not reproduce the issue with original script sent by Dewb with  size 5 X 5 either please try at your end.

**Comment by ikeough** [comment] 2016-05-02 04:44
@Dewb Closing this as it seems we are unable to reproduce with newer builds. Please re-open if it's still an issue.

**Closed by ikeough** 2016-05-02 04:44 UTC
Labels: Geometry
