### ISSUE TITLE
Dynamo crashes when it attempts to install LunchBox

### ISSUE THREAD

**Issue by phelpa** [DynamoDS/Dynamo#6069] opened 2016-02-03 16:47 UTC
http://dynamoprimer.com/08_Dynamo-for-Revit/8-5_Customizing.html

"Go to Packages>Search for a Package...
Search for "LunchBox" and download "LunchBox for Dynamo". This is a really helpful set of tools for geometry operations such as this."

When using the tutorial to learn dynamo I encountered this problem, when I try to install lunchbox as said in the tutorial my dynamo crashes and it says this :

Índice (baseado em zero) deve ser maior ou igual a zero e menor que o tamanho da lista de argumentos.

   em System.Text.StringBuilder.AppendFormat(IFormatProvider provider, String format, Object[] args)
   em System.String.Format(IFormatProvider provider, String format, Object[] args)
   em Dynamo.PackageManager.PackageManagerSearchViewModel.PackageOnExecuted(PackageManagerSearchElement element, PackageVersion version, String downloadPath)
   em System.Windows.Controls.Button.OnClick()
   em System.Windows.Controls.Primitives.ButtonBase.OnMouseLeftButtonUp(MouseButtonEventArgs e)
   em System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   em System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   em System.Windows.UIElement.ReRaiseEventAs(DependencyObject sender, RoutedEventArgs args, RoutedEvent newEvent)
   em System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   em System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   em System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   em System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   em System.Windows.Input.InputManager.ProcessStagingArea()
   em System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   em System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
   em System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   em System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   em MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   em MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   em System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   em MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(Object source, Delegate method, Object args, Int32 numArgs, Delegate catchHandler)
   em System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   em MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   em MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   em System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   em System.Windows.Application.RunInternal(Window window)
   em DynamoSandbox.Program.MakeStandaloneAndRun(String commandFilePath, DynamoViewModel& viewModel)
   em DynamoSandbox.Program.Main(String[] args)

**Comment by aparajit-pratap** [comment] 2016-04-22 06:39
@monikaprabhu you recently tested Lunchbox. Could you take a look at this?

**Comment by alfarok** [comment] 2017-10-30 17:36
@phelpa I was not able to reproduce this issue in Dynamo 1.3.  Please let us know if you are still experiencing issues.

**Comment by johnpierson** [comment] 2018-10-04 17:11
Closing as Lunchbox is now provided as a standalone installer.

**Closed by johnpierson** 2018-10-04 17:11 UTC
Labels: Package Manager
