### ISSUE TITLE
Editing custom node properties sets node visibility to false

### ISSUE THREAD

**Issue by andydandy74** [DynamoDS/Dynamo#8873] opened 2018-05-20 05:55 UTC
## Dynamo version

2.0.1.5000

## Operating system

Windows 10

## What did you do? 

Edited a custom node's property

## What did you expect to see?

Just the property changing, nothing else

## What did you see instead?

In the next Dynamo session the custom node was missing from the library because its ```IsVisibleInDynamoLibrary``` had been set to ```False```.
![grafik](https://user-images.githubusercontent.com/3014437/40276164-ef3d9fd6-5c02-11e8-85c1-53af35ca52b6.png)
Before:
![nodeinlibrary](https://user-images.githubusercontent.com/3014437/40276166-fd1746c0-5c02-11e8-9a84-8ca475deccdc.PNG)
After:
![nodegone](https://user-images.githubusercontent.com/3014437/40276168-035e76ac-5c03-11e8-9649-38b6c0947292.PNG)

## Steps to reproduce
- Place a JSON-based custom node on canvas
- Edit its properties via right click (e.g. change node description)
- Start a new Dynamo session
- Note that the node no longer appears in the library

## FYI
@mjkkirschner @Racel @kronz 
I think it's essential that this be fixed before the 2.0.1 release. Nodes disappearing from the library is not a good thing...

**Comment by kronz** [comment] 2018-05-20 12:26
@mjkkirschner @Racel, I can reproduce this pretty easily, thanks for the catch @andydandy74 .  So, just to clarify, I thinkcthat this is not happening with the 2.0.0 release, but seems to be introduced with the 2.0.1 pre-release build DynamoRevit2.0.1.20180519T0314.exe

**Comment by jnealb** [comment] 2018-05-20 13:54
will take a look

**Comment by mjkkirschner** [comment] 2018-05-20 16:06
@QilongTang  my guess is because the saved workspace view in your PR is a temp workspace view model it's not visible, so this goes false when saved - we can it manually to the value from the previous custom node workspace at save time from the functionNamePrompt handler and then write a test that asserts it does not change.

**Comment by mjkkirschner** [comment] 2018-05-20 16:16
https://github.com/DynamoDS/Dynamo/blob/70bcfb21eb584356c5a4320d060964a6b6a93276/src/DynamoCoreWpf/ViewModels/Core/WorkspaceViewModel.cs#L206

**Comment by QilongTang** [comment] 2018-05-20 23:04
@mjkkirschner Sorry but I don't think that is the reason here, this bug is not reproducable on XML dyfs which means there is a bug in our Json Custom Node workspace deserialization code there not respecting the filed `IsVisibleInDynamoLibrary` in the file. I will submit a PR for that soon.

**Comment by mjkkirschner** [comment] 2018-05-20 23:18
@QilongTang you might be right - this seems to be where it gets set:
https://github.com/DynamoDS/Dynamo/blob/b67417597caa3ae1918ce7061821a0be82702f93/src/DynamoCore/Models/DynamoModel.cs#L1497 on load, but

note above that @kronz says he cannot reproduce this on 2.0, only 2.0.1 which seems to indicate something else, please bear that in mind though.

**Comment by jnealb** [comment] 2018-05-21 13:13
This is tracked with QNTM-4329.

**Comment by Racel** [comment] 2018-05-21 13:39
@QilongTang Agree. Let us get this into 2.0.1.

@andydandy74 thanks for catching this.

**Comment by QilongTang** [comment] 2018-05-21 15:17
Closing as will-fix in 2.0.1

**Closed by QilongTang** 2018-05-21 15:17 UTC
Labels: 2.0.1 Release, Bug, JSON
