### ISSUE TITLE
Crash with List.Map

### ISSUE THREAD

**Issue by dbaldacchino** [DynamoDS/Dynamo#3989] opened 2015-03-14 21:28 UTC
I'm getting a crash when I wire this:

![2015-03-14_16-26-46](https://cloud.githubusercontent.com/assets/4656191/6653585/1d5d83e4-ca67-11e4-94c6-2e042877c1fd.png)

Here's the info in the dialog:

Exception of type 'ProtoCore.Exceptions.CompilerInternalException' was thrown.

   at ProtoCore.Utils.ArrayUtils.GetKeys(StackValue array, Core core)
   at ProtoCore.Lang.BuiltInFunctionEndPoint.Execute(Context c, List`1 formalParameters, StackFrame stackFrame, Core core)
   at ProtoCore.CallSite.ExecWithZeroRI(List`1 functionEndPoint, Context c, List`1 formalParameters, StackFrame stackFrame, Core core, FunctionGroup funcGroup, SingleRunTraceData previousTraceData, SingleRunTraceData newTraceData)
   at ProtoCore.CallSite.Execute(List`1 functionEndPoint, Context c, List`1 formalParameters, List`1 replicationInstructions, StackFrame stackFrame, Core core, FunctionGroup funcGroup)
   at ProtoCore.CallSite.DispatchNew(Context context, List`1 arguments, List`1 partialReplicationGuides, StackFrame stackFrame, Core core)
   at ProtoCore.Lang.FunctionPointerEvaluator.Evaluate(List`1 args, StackFrame stackFrame)
   at ProtoCore.Lang.ArrayUtilsForBuiltIns.Evaluate(StackValue function, StackValue parameters, StackValue unpackParams, Interpreter runtime, StackFrame stackFrame)
   at ProtoCore.Lang.BuiltInFunctionEndPoint.Execute(Context c, List`1 formalParameters, StackFrame stackFrame, Core core)
   at ProtoCore.CallSite.ExecWithZeroRI(List`1 functionEndPoint, Context c, List`1 formalParameters, StackFrame stackFrame, Core core, FunctionGroup funcGroup, SingleRunTraceData previousTraceData, SingleRunTraceData newTraceData)
   at ProtoCore.CallSite.Execute(List`1 functionEndPoint, Context c, List`1 formalParameters, List`1 replicationInstructions, StackFrame stackFrame, Core core, FunctionGroup funcGroup)
   at ProtoCore.CallSite.DispatchNew(Context context, List`1 arguments, List`1 partialReplicationGuides, StackFrame stackFrame, Core core)
   at ProtoCore.DSASM.Executive.Callr(Int32 functionIndex, Int32 classIndex, Int32 depth, Boolean& explicitCall, Boolean isDynamicCall, Boolean hasDebugInfo)
   at ProtoCore.DSASM.Executive.CALLR_Handler(Instruction instruction)
   at ProtoCore.DSASM.Executive.Execute(Int32 exeblock, Int32 entry, Language language)
   at ProtoCore.DSASM.Interpreter.Run(Int32 codeblock, Int32 entry, Language lang)
   at ProtoCore.Lang.JILFunctionEndPoint.Execute(Context c, List`1 formalParameters, StackFrame stackFrame, Core core)
   at ProtoCore.CallSite.ExecWithZeroRI(List`1 functionEndPoint, Context c, List`1 formalParameters, StackFrame stackFrame, Core core, FunctionGroup funcGroup, SingleRunTraceData previousTraceData, SingleRunTraceData newTraceData)
   at ProtoCore.CallSite.Execute(List`1 functionEndPoint, Context c, List`1 formalParameters, List`1 replicationInstructions, StackFrame stackFrame, Core core, FunctionGroup funcGroup)
   at ProtoCore.CallSite.DispatchNew(Context context, List`1 arguments, List`1 partialReplicationGuides, StackFrame stackFrame, Core core)
   at ProtoCore.Lang.FunctionPointerEvaluator.Evaluate(List`1 args, StackFrame stackFrame)
   at ProtoCore.Lang.ArrayUtilsForBuiltIns.Evaluate(StackValue function, StackValue parameters, StackValue unpackParams, Interpreter runtime, StackFrame stackFrame)
   at ProtoCore.Lang.BuiltInFunctionEndPoint.Execute(Context c, List`1 formalParameters, StackFrame stackFrame, Core core)
   at ProtoCore.CallSite.ExecWithZeroRI(List`1 functionEndPoint, Context c, List`1 formalParameters, StackFrame stackFrame, Core core, FunctionGroup funcGroup, SingleRunTraceData previousTraceData, SingleRunTraceData newTraceData)
   at ProtoCore.CallSite.Execute(List`1 functionEndPoint, Context c, List`1 formalParameters, List`1 replicationInstructions, StackFrame stackFrame, Core core, FunctionGroup funcGroup)
   at ProtoCore.CallSite.DispatchNew(Context context, List`1 arguments, List`1 partialReplicationGuides, StackFrame stackFrame, Core core)
   at ProtoCore.DSASM.Executive.Callr(Int32 functionIndex, Int32 classIndex, Int32 depth, Boolean& explicitCall, Boolean isDynamicCall, Boolean hasDebugInfo)
   at ProtoCore.DSASM.Executive.CALLR_Handler(Instruction instruction)
   at ProtoCore.DSASM.Executive.Execute(Int32 exeblock, Int32 entry, Language language)
   at ProtoAssociative.Executive.Execute(Int32 codeblock, Int32 entry, Context callContext, EventSink sink)
   at ProtoCore.Core.Bounce(Int32 exeblock, Int32 entry, Context context, StackFrame stackFrame, Int32 locals, EventSink sink)
   at ProtoScript.Runners.ProtoScriptTestRunner.Execute(Core core, Context context)
   at ProtoScript.Runners.LiveRunner.Execute()
   at ProtoScript.Runners.LiveRunner.PostExecution()
   at ProtoScript.Runners.LiveRunner.CompileAndExecuteForDeltaExecution(List`1 astList)
   at ProtoScript.Runners.LiveRunner.UpdateGraph(GraphSyncData syncData)
   at Dynamo.Core.Threading.AsyncTask.Execute()

**Comment by dbaldacchino** [comment] 2015-03-14 21:31
I'm running the stable build 0.7.5.3566. BTW, Im just experimenting and am not sure if the above should give me any result but I was trying to retrieve the indexes of the nsted lists. I can wire just one List.Map node and it gives me all indexes but was curious to see what I'd get if I wire two.

**Comment by monikaprabhu** [comment] 2015-03-16 10:27
@dbaldacchino I can reproduce this without using list.map. I think it crashes when the input for Getkeys is not a list.
To provide you a correct workaround I would need to see your entire graph. Im tracking this internally at MAGN-6684
a simple graph like following also throws exception due to the invalid input( not list)
![image](https://cloud.githubusercontent.com/assets/5218721/6664364/09e029a8-cc0a-11e4-9b93-39548ca68401.png)

**Comment by dbaldacchino** [comment] 2015-03-30 15:37
Hi, thanks for the followup. Unfortunately I don't have a specific graph. I managed to crash as I was trying to understand how GetKeys works :) So I must have wired some invalid input and caused the crash as you pointed out.

**Comment by ikeough** [comment] 2016-05-03 04:54
Internal task is closed in https://github.com/DynamoDS/Dynamo/pull/4025. Please re-open if you're still seeing this in newer builds.

**Closed by ikeough** 2016-05-03 04:54 UTC
Labels: Bug, Critical, Design Script
