### ISSUE TITLE
String Node stores value twice

### ISSUE THREAD

**Issue by phrmsilva** [DynamoDS/Dynamo#5572] opened 2015-10-20 20:25 UTC
Hey,
Looking at a simple string node in the .dyn file I noticed there are two different places the actual value shows up:

```
...
    <Dynamo.Nodes.StringInput guid="a9edd6f3-18a6-49a7-b42c-b3da0a0c1737" type="Dynamo.Nodes.StringInput" nickname="MyStringNode" x="433.65445026178" y="167.267015706806" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True">
      <System.String>"example"</System.String>         <!-- once -->
      <System.String value="&quot;example&quot;" />    <!-- twice -->
    </Dynamo.Nodes.StringInput>
...
```

Any particular reason why this would be doubled?

**Comment by alfarok** [comment] 2017-11-07 17:30
Closing as I am unable to reproduce in more recent dynamo builds.  Please feel free to reopen if you are still experiencing similar behavior in more newer releases.

**Closed by alfarok** 2017-11-07 17:30 UTC
Labels: Improvement, Nodes
