### ISSUE TITLE
Arc by three points returns wrong parameters

### ISSUE THREAD

**Issue by paoloemilioserra** [DynamoDS/Dynamo#7128] opened 2016-09-08 14:23 UTC
If this issue is with Dynamo for Revit, please post your issue on the [Dynamo for Revit Issues page](https://github.com/DynamoDS/DynamoRevit/issues).

If this issue is **not** a bug report or improvement request, please check the [Dynamo forum](https://forum.dynamobim.com/), and start a thread there to discuss your issue.
## Dynamo version

1.1.0.2065
## Operating system

Windows 7
## What did you do?

I created an arc by three points that works fine and later used its parameters to create an arc by center point radius and angle
## What did you expect to see?

I was hoping to see two identical arcs overlapping
## What did you see instead?

the second arc is starting from zero on the X axis and it's not overalpping with the arc by three points

![image](https://cloud.githubusercontent.com/assets/14221455/18352770/fe0c76c8-75df-11e6-800c-f0cc03ed3ddd.png)

**Comment by sharadkjaiswal** [comment] 2016-09-09 08:13
@paoloemilioserra, thanks for reporting this. I think the issue is with StartAngle, it always returns 0. We will look at it.

**Comment by aparajit-pratap** [comment] 2016-11-28 10:07
Fixed in https://git.autodesk.com/Dynamo/LibG/pull/414 (internal reference only)

**Closed by aparajit-pratap** 2016-11-28 10:07 UTC
Labels: Bug, Geometry
