### ISSUE TITLE
Graphic issues

### ISSUE THREAD

**Issue by vykrum** [DynamoDS/Dynamo#7233] opened 2016-10-02 13:20 UTC
## Dynamo version

1.2.0.2690
## Operating system

Windows 10
## What did you do?

Drew a circle
## What did you expect to see?

A circle
## What did you see instead?

![error-20101002-1](https://cloud.githubusercontent.com/assets/5621624/19020835/f91408b2-88d0-11e6-8849-742bcf2e4b3d.png)

**Comment by mjkkirschner** [comment] 2016-10-02 13:38
@aparajit-pratap going to guess this has to do with large units and the accuracy of the tessellation?

**Comment by josols** [comment] 2016-10-07 11:20
Don't know if related but I get the same for a mesh in mm. translated to a polysurface it looks normal. (see selected below) but the mesh extracted from topo is wrongfully displayed (the not selected one.)
![image](https://cloud.githubusercontent.com/assets/7080648/19188237/a613cf44-8c90-11e6-89bc-e69fb993bd6d.png)

**Comment by ikeough** [comment] 2016-10-07 12:27
@mjkkirschner This does have to do with the size of the units. You will see a similar effect for very large files in Revit, or any application really. It's why Revit gives you a warning if you load a file that's larger than a mile wide (at least it used to do this). It has to do with floating point precision. Unfortunately, Dynamo does not do tricks like some graphics engines do to re-center, or re-scale the the scene in this situation.

**Comment by ikeough** [comment] 2016-10-07 12:32
I'm going to close this because between what we would need to figure out to get ASM tessellation to work at this scale, and to get the graphics engine to display the results properly, we don't have the resource to solve this problem.

@vykrum I recommend setting your project units in Revit (if you're using Revit) to meters, or assuming meters in Dynamo Studio. I think this is reasonable given that your circle's origin is 3000m from the world origin.

**Comment by josols** [comment] 2016-10-11 12:09
In my case the mesh was close to zero. Have done this many times before and never had any problems with it before 1.2

**Comment by mjkkirschner** [comment] 2016-10-11 13:49
@josols I wonder if your issue is a revit units conversion issue, how are you extracting the mesh?

**Comment by josols** [comment] 2016-10-12 06:21
Just by "Select Model Element">"Topography.Mesh". (Got no access to PC right now..)

**Comment by aparajit-pratap** [comment] 2016-10-18 02:52
@ikeough there are some changes going into geometry tessellation as part of the ASM scaling work that will address this (as long as users select an appropriate scale in which they're working). More specifically large numbers (> 10,000 units) will be scaled down before passing them into ASM, therefore the numbers returned from ASM faceting will need to be scaled back up by the same scale factor before being added to tessellated data. I'll share more details soon.

**Comment by ikeough** [comment] 2016-10-18 03:55
Thanks for the update @aparajit-pratap! Please update this issue when the ASM scaling work is resolved. I've assigned it to you as a reminder.

**Comment by aparajit-pratap** [comment] 2017-01-24 05:48
@josols could you share your Revit model and Dynamo graph that you're using to extract a Topo mesh from? We have recently made fixes to handle large geometries in Dynamo and would like to test it with such examples.

**Comment by josols** [comment] 2017-01-24 09:32
I've shared a simple revit file and dyn here: https://www.dropbox.com/sh/k6nirvg795ml7q8/AAABzX8hioY5IoaKcqfPSJwMa?dl=0

**Comment by aparajit-pratap** [comment] 2017-01-25 10:18
![image](https://cloud.githubusercontent.com/assets/5710686/22285971/9a92ea6c-e328-11e6-93d2-aabe66ae0327.png)
@josols Thanks! It looks like this issue is solved using the new Geometry Scaling settings as shown here. The mesh is quite large as can be seen by the Surface.Area value and we know that since there are restrictions in the sizes of geometry that our geometry kernel (ASM) can handle (https://github.com/DynamoDS/Dynamo/issues/5681), the results obtained are arbitrary. We have recently implemented a solution to handle this that takes in the approximate modeling range from the user and based on that setting internally scales down the numbers within a reasonable range that the kernel can handle. The solution has also been tested with the example shared by @ParametricMonkey in #5681. More on this soon ... @kronz

**Comment by josols** [comment] 2017-01-25 16:24
Great! If you can please implement this in Revit also so that we can show imports etc. with real world coordinates that would be great! ;)

**Comment by aparajit-pratap** [comment] 2017-01-31 12:05
I tried a number of techniques to fix the graphic issue but not quite there yet. One was to bring the geometry to the origin, compute the tessellation and then to transform the faceted results - points, lines and facets back to their original location. I was guessing that ASM faceting was unstable for large coordinate values but apparently not as this didn't seem to make any difference. The ASM scaling work done recently doesn't help either in this case as not only do the coordinate values scale but also distance values so in the case of the circle, if we scale down the point coordinates, we end up scaling the unit radius by the same factor that probably eventually affects the tessellation due to floating point precision. Finally playing with ASM faceting variables such as tolerances and max segment values did not seem to make any difference either. I suppose @ikeough is right in pointing out changes in the graphics engine that are required to fix this and since we don't have that kind of support I'm closing this issue for now.

**Closed by aparajit-pratap** 2017-01-31 12:05 UTC
Labels: Geometry

**Comment by josols** [comment] 2017-01-31 14:52
Ok.  I'm just a simple engineer, but curious none the less..This is due to how coordinates are stored right? So if ASM could store/handle coordinates with some kind of high resolution coordinates then it could possibly work? though file sizes may bloat?
Were could we, as customers of Autodesk, tell the developers of ASM that we want this kind of functionality?

**Comment by aparajit-pratap** [comment] 2017-02-03 02:51
@josols to rephrase what I mentioned earlier, the issue is not with ASM, it's with the graphics engine used in Dynamo.

**Comment by monikaprabhu** [comment] 2017-02-16 05:53
@josols , @vykrum - ASM scaling issues is fixed and available in 1.2.3.xxxx daily builds available on DynamoBIM website. Ive tested the topomesh issue above and it seems fixed to me with the new scaling applied. (https://github.com/DynamoDS/Dynamo/pull/6991 ) Please retest and if you can reproduce let me know.
