### ISSUE TITLE
Convert Curve to Arcs at tangents

### ISSUE THREAD

**Issue by frogbuddy** [DynamoDS/Dynamo#3856] opened 2015-03-02 10:48 UTC
I'm working at Buro Happold, Bath and we are using Dynamo to model the structural frame in Revit. 
In Rhino under the convert to arcs command you can achieve a series of arcs at tangents. Is there a way of doing this to a curve geometry in Dynamo? And then being able to join arcs and use them as a single curve again but keeping the geometry. eg divide it as a curve not a polycurve. 
![rhino arcs at tangents](https://cloud.githubusercontent.com/assets/9006125/6439239/b7b11418-c0c8-11e4-8a10-8896365bf975.jpg)

**Comment by kronz** [comment] 2015-03-08 13:15
Hi @frogbuddy 
2 somewhat seperate issues here:  a) converting curves to arcs, and b) what structural framing can deal with.  
a) You could just use the Curve.ApproximateWithArcAndLineSegments to rationalize the curve.  This is pretty uncontrolled though, and may not give the kind of resolution (generally too detailed) that you want.  Alternatively, you can do this workflow which uses the Arc.ByStartEndAndTangencies node, and more finely control the number of curves generated.  
![2015-03-08_0901](https://cloud.githubusercontent.com/assets/3456818/6545879/848e1ed8-c572-11e4-863a-da34e628320e.png)
one thing to know about this workflow, the arc that are created this way have their directions set as end to end and start to start.  Putting them into a PolyCurve.ByJoinedCurves will align them all, and you can extract the curves for structural framing by using the PolyCurve.Curve tool.

b) Structural framing only takes a continuous curve, therefore, it will not take a polycurve.  That is, if you were going to draw a Structural Framing memeber manually in the Revit interface, the only sketch tools you have are single curve elements with no discontinuities (no collections of curves).  Using the Tangent End Arc tool in the interface is roughly equivalent to using the above workflow for Dynamo. 
![2015-03-08_0912](https://cloud.githubusercontent.com/assets/3456818/6545891/4fa3e198-c573-11e4-94c1-061f15c20a0e.png)

**Comment by smangarole** [comment] 2017-07-12 13:13
This is not a bug. Closing the issue.

**Closed by smangarole** 2017-07-12 13:13 UTC
Labels: Not a bug
