### ISSUE TITLE
dynamo 0.9.1 for revit2016 

### ISSUE THREAD

**Issue by zhadiqi** [DynamoDS/Dynamo#5525] opened 2015-10-14 13:46 UTC
![1111](https://cloud.githubusercontent.com/assets/1333685/10485480/0223a776-72bd-11e5-89c2-d0ee1dc76965.png)
![Uploading 1111.png…]()

**Comment by pboyer** [comment] 2015-10-14 16:48
Are you implementing your own `NodeModel`?

**Comment by zhadiqi** [comment] 2015-10-15 13:12
Click the DYNAMO icon to start with no interface. the Chinese version of revit.

**Comment by ke-yu** [comment] 2016-07-26 03:49
@zhadiqi is this issue still reproducible on 1.0 ?

**Comment by smangarole** [comment] 2017-06-19 17:57
We have released a new version of Dynamo since this issue was opened. The issue has been waiting for feedback for almost a year. Closing due to these reasons. Please reopen if this issue resurfaces.

**Closed by smangarole** 2017-06-19 17:57 UTC
Labels: Blocker, Bug, Revit, Waiting for feedback
