### ISSUE TITLE
Fail to launch Dynamo in Revit 2021

### ISSUE THREAD

**Issue by netsonicyxf** [DynamoDS/Dynamo#10619] opened 2020-04-30 10:38 UTC
Fail to launch Dynamo in Revit 2021

## Dynamo version

2.5

## Revit version

2021

## Operating system

Win 10 x64

## What did you do? 

Open revit, create a new revit file, launch Dynamo from revit panel

## What did you expect to see?

Dynamo launch screen

## What did you see instead?

![dynamo](https://user-images.githubusercontent.com/43513391/80701266-b5dbb080-8b11-11ea-85c8-055a78acae44.png)

**Comment by QilongTang** [comment] 2020-04-30 21:03
hi @netsonicyxf, were you able to continuously reproduce this. If this, may I request you to restart your computer and try this again. Thanks, let me know. This crash seems related to our analytics service. Your feedback will help me digest what's going on.

**Comment by netsonicyxf** [comment] 2020-05-01 00:41
Hi @QilongTang ,
I restart my PC and the result is the same. 
But the error info is different this time:
![dynamo 2](https://user-images.githubusercontent.com/43513391/80771915-72bc2480-8b87-11ea-9aff-c188870f79f6.png)

**Comment by mjkkirschner** [comment] 2020-05-01 01:24
similar report:
https://forum.dynamobim.com/t/dynamo-in-revit-2021-doesnt-want-to-work/50008/3

I think this can happen when some incompatible binary gets loaded into Dynamo at startup; (The Compiler exception)

my advice is the same - 
1.  delete the entries for dynamo under %appData% analytrics
2. delete any packages from your package folder
3. temporarily remove all revit addins

**Comment by netsonicyxf** [comment] 2020-05-01 01:39
@mjkkirschner 

1. delete the entries for dynamo under %appData% analytrics
I deleted CSharpAnalytics-MeasurementQueue and CSharpAnalytics-MeasurementSession under C:\Users\username\AppData\Roaming\Analytics, but they reappear every time I press "Dynamo" button on the revit.

2. delete any packages from your package folder
C:\Users\username\AppData\Roaming\Dynamo\Dynamo Revit\2.5\packages\ is empty.

3. temporarily remove all revit addins
C:\ProgramData\Autodesk\Revit\Addins\2021\ remove all the things under that folder.

Still can't launch Dynamo.

PS. I have old revit installed as well, hope they will not hurt 2021.

**Comment by mjkkirschner** [comment] 2020-05-01 01:41
@netsonicyxf - have you installed any addins yourself on Revit 2021?

**Comment by netsonicyxf** [comment] 2020-05-01 02:09
No, I didn't install any addin for 2021

**Comment by netsonicyxf** [comment] 2020-05-02 02:20
@mjkkirschner 
I have other Revit 2016, 2018 and 2020 with 3rd party addins, the Dynamo in these revits runs well. Hope the 3rd party addins in old versions of Revit will not interfere with Revit 2021 Dynamo.

**Comment by mjkkirschner** [comment] 2020-05-02 02:23
@netsonicyxf I don't think they would, but you could try removing addins from 2020.

If possible I would try installing 2021 into clean environment - at least to check if some interaction could be happening with something else on the machine.

**Comment by netsonicyxf** [comment] 2020-05-04 05:48
I tried Dynamo core 2.5.2, it runs well.

**Comment by netsonicyxf** [comment] 2020-05-10 02:49
I follow the [Dynamo is not launching from the manage tab in Revit](https://knowledge.autodesk.com/zh-hans/support/revit-products/troubleshooting/caas/sfdcarticles/sfdcarticles/CHS/Dynamo-is-not-launching-from-the-manage-tab-in-Revit.html),
I move the files in the following folders to temporary place
C:\ProgramData\Autodesk\Revit\Addins\2021
C:\ProgramData\Autodesk\ApplicationPlugins

But Dynamo still crash.

I also checked dynamo log file under C:\Users\yingx\AppData\Roaming\Dynamo\Dynamo Revit\2.5\Logs\ , but most of the log file has no content in it, they are 0 byte.
Some log file has  very littile content, such as 

> Dynamo log started 2020-05-10 01:29:06Z
2020-05-10 01:29:06Z : Python 妯℃澘璁剧疆涓洪粯璁ゃ€?

**Comment by netsonicyxf** [comment] 2020-06-12 14:20
any progress?

**Comment by Amoursol** [comment] 2020-07-09 14:46
Hello @netsonicyxf - We have filed an internal task and will be looking into this 🙌

**Comment by mjkkirschner** [comment] 2020-07-22 19:03
Hi @netsonicyxf I cannot reproduce this with a new install of 2021 using different languages.
I am going to close this until we can reproduce it. I would ask you to verify if the problem occurs on a clean machine with only Revit 2021.

**Closed by mjkkirschner** 2020-07-22 19:03 UTC
Labels: crash, needs investigation, tracked

**Comment by netsonicyxf** [comment] 2020-07-23 01:05
> Hi @netsonicyxf I cannot reproduce this with a new install of 2021 using different languages.
> I am going to close this until we can reproduce it. I would ask you to verify if the problem occurs on a clean machine with only Revit 2021.

The dynamo for 2021 works fine after I reinstalled win 10.
