### ISSUE TITLE
Excel Export/Import does not work

### ISSUE THREAD

**Issue by torkuen** [DynamoDS/Dynamo#5925] opened 2016-01-08 12:24 UTC
Hi there,
my Excel nodes don´t work on one of my computers.
Any ideas?
Thanks,
Torsten

Warnung:Excel.WriteToFile fehlgeschlagen.
Das COM-Objekt des Typs "Microsoft.Office.Interop.Excel.ApplicationClass" kann nicht in den Schnittstellentyp "Microsoft.Office.Interop.Excel._Application" umgewandelt werden.Dieser Vorgang konnte nicht durchgeführt werden, da der QueryInterface-Aufruf an die COM-Komponente für die Schnittstelle mit der IID "{000208D5-0000-0000-C000-000000000046}" aufgrund des folgenden Fehlers nicht durchgeführt werden konnte: Bibliothek nicht registriert. (Ausnahme von HRESULT: 0x8002801D (TYPE_E_LIBNOTREGISTERED)).

**Comment by torkuen** [comment] 2016-01-08 12:36
PS: sorry for giving the error message in german. As my Revit installation is originally in German, Dynamo starts in German as well. If I change the language by starting the Sandbox application, the error message only says "Warning: Excel.WriteToFile operation failed"

**Comment by ksobon** [comment] 2016-01-11 14:32
Check your Task Manager and make sure that you don't have any Excel instances running in the background. Close them all. This might be causing an issue. 

Also, there is an alternative to OOTB nodes in the name of Bumblebee. It's a custom package that you can get from Package Manager. It reads/writes to Excel and a lot more. Here is documentation: https://konradsobon.gitbooks.io/bumblebee-primer/content/

**Comment by aparajit-pratap** [comment] 2016-01-19 06:21
Hi @torkuen could you post the graph you were using to reproduce this issue. It would be helpful to us in debugging the problem. Thanks.

**Comment by smangarole** [comment] 2017-06-19 18:52
The issue has been waiting for feedback for almost a year. Closing due to this reason. Please reopen if this issue resurfaces.

**Closed by smangarole** 2017-06-19 18:52 UTC
Labels: Bug, Nodes, Waiting for feedback
