### ISSUE TITLE
Crash when I try to zoom extents to geometry preview

### ISSUE THREAD

**Issue by brianringley** [DynamoDS/Dynamo#5750] opened 2015-11-24 21:41 UTC
If I select the geometry view extents icon Dynamo crashes consistently in this particular file. Please let me know who to email the file to.

Revit 2016

Dynamo 0.9.0.3067

Rhynamo 2015.11.191

Windows 7

Details:

'NaN,NaN,NaN' is not a valid value for property 'From'.

   at System.Windows.DependencyObject.SetValueCommon(DependencyProperty dp, Object value, PropertyMetadata metadata, Boolean coerceWithDeferredReference, Boolean coerceWithCurrentValue, OperationType operationType, Boolean isInternal)
   at System.Windows.DependencyObject.SetValueInternal(DependencyProperty dp, Object value)
   at System.Windows.Media.Animation.Point3DAnimation..ctor(Point3D fromValue, Point3D toValue, Duration duration)
   at HelixToolkit.Wpf.SharpDX.CameraExtensions.AnimateTo(Camera camera, Point3D newPosition, Vector3D newDirection, Vector3D newUpDirection, Double animationTime)
   at HelixToolkit.Wpf.SharpDX.CameraExtensions.LookAt(Camera camera, Point3D target, Vector3D newLookDirection, Vector3D newUpDirection, Double animationTime)
   at HelixToolkit.Wpf.SharpDX.CameraExtensions.LookAt(Camera camera, Point3D target, Vector3D newLookDirection, Double animationTime)
   at HelixToolkit.Wpf.SharpDX.ViewportExtensions.ZoomExtents(Viewport3DX viewport, Point3D center, Double radius, Double animationTime)
   at HelixToolkit.Wpf.SharpDX.ViewportExtensions.ZoomExtents(Viewport3DX viewport, Rect3D bounds, Double animationTime)
   at HelixToolkit.Wpf.SharpDX.ViewportExtensions.ZoomExtents(Viewport3DX viewport, Double animationTime)
   at System.Windows.Controls.Button.OnClick()
   at System.Windows.Controls.Primitives.ButtonBase.OnMouseLeftButtonUp(MouseButtonEventArgs e)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.ReRaiseEventAs(DependencyObject sender, RoutedEventArgs args, RoutedEvent newEvent)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
   at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(Object source, Delegate method, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by jnealb** [comment] 2015-11-24 21:45
@brianringley Neal.burnham@autodesk.com. If it is not too much trouble, can you tell us if this still occurs with the 9.1 dailies?

**Comment by brianringley** [comment] 2015-11-26 16:29
Could test a daily on a VM - will probably have to wait until after AU. Thanks!

**Comment by ke-yu** [comment] 2016-07-13 06:28
@brianringley are you able to reproduce this crash?

**Comment by smangarole** [comment] 2017-06-19 18:02
The issue has been waiting for feedback for almost a year. Closing due to this reason. Please reopen if this issue resurfaces.

**Closed by smangarole** 2017-06-19 18:02 UTC
Labels: Graphics, Waiting for feedback
