### ISSUE TITLE
Crash report from Dynamo 2.3.0.5885

### ISSUE THREAD

**Issue by rabiadhikari** [DynamoDS/Dynamo#10724] opened 2020-06-02 01:33 UTC
# Issue Description:  Double clicked on the connector line and something appeared. Tried to Remove it and the connector wasn't cleared. There was a void and any attempt to reconnect crashed into this page.

Please fill in the following information to help us reproduce the issue:

### What did you do?
Double clicked on the connector line between two nodes.

### What did you expect to see?
After removing the new item that appeared in the connector line go away and the connection restored.

### What did you see instead?
The program crashed.

### What packages or external references (if any) were used?
Not a particular one. OOTB stuffs.

### Stack Trace
```
Object reference not set to an instance of an object.

   at Dynamo.ViewModels.ConnectorViewModel.Dispose()
   at Dynamo.ViewModels.WorkspaceViewModel.Connectors_ConnectorDeleted(ConnectorModel c)
   at Dynamo.Graph.Workspaces.WorkspaceModel.OnConnectorDeleted(ConnectorModel obj)
   at System.Action.Invoke()
   at Dynamo.Graph.Connectors.ConnectorModel.OnDeleted()
   at Dynamo.Models.DynamoModel.GetConnectorsToAddAndDelete(PortModel endPort, PortModel startPort)
   at Dynamo.Models.DynamoModel.EndConnection(Guid nodeId, Int32 portIndex, PortType portType)
   at Dynamo.Models.DynamoModel.MakeConnectionImpl(MakeConnectionCommand command)
   at Dynamo.Models.DynamoModel.ExecuteCommand(RecordableCommand command)
   at Dynamo.ViewModels.WorkspaceViewModel.StateMachine.HandlePortClicked(PortViewModel portViewModel)
   at Dynamo.ViewModels.PortViewModel.Connect(Object parameter)
   at System.Windows.Interactivity.InvokeCommandAction.Invoke(Object parameter)
   at System.Windows.Interactivity.TriggerBase.InvokeActions(Object parameter)
   at Dynamo.UI.Views.HandlingEventTrigger.OnEvent(EventArgs eventArgs)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.ReRaiseEventAs(DependencyObject sender, RoutedEventArgs args, RoutedEvent newEvent)
   at System.Windows.UIElement.OnMouseDownThunk(Object sender, MouseButtonEventArgs e)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.InputManager.ProcessInput(InputEventArgs input)
   at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
   at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
```

---
OS: `Microsoft Windows NT 10.0.18363.0`
CLR: `4.0.30319.42000`
Dynamo: `2.3.0.5885`

**Comment by QilongTang** [comment] 2020-06-02 02:48
@Amoursol @mjkkirschner What would double clicking on connector line do? I am not able to follow the steps because I was not aware any UI feature related to this.

**Comment by mjkkirschner** [comment] 2020-06-02 02:58
@rabiadhikari are you using archilab?
https://github.com/ksobon/archilab/pull/58

it adds an action on connector double click I guess. I think this crash should likely be redirected to that project.

**Comment by rabiadhikari** [comment] 2020-06-02 03:18
Yes Michael!
I have archilab package installed in Dynamo. I see why it behaves like that
now. Thank you!

**Comment by mjkkirschner** [comment] 2020-06-02 03:20
@rabiadhikari I'm going to close this then, I think you can file this issue in the archilab git repo with  steps to reproduce, and the author can take a look - if it turns out it's our fault we can reopen this one.
Thanks!

**Closed by mjkkirschner** 2020-06-02 03:20 UTC
Labels: needs more info
