### ISSUE TITLE
Autorun enabled by default

### ISSUE THREAD

**Issue by ksobon** [DynamoDS/Dynamo#4121] opened 2015-03-30 00:09 UTC
It's a bad idea to by default have Auto-run on in Dynamo. It's not Grasshopper and its performing a lot heavier operations than Grasshopper. I think it was good as it was before when it was on Manual to begin with and user could switch to Auto-run. Why? 
Well, for starters Dynamo doesn't Auto-save so any screw-up is a fatal one. There is no getting your work back. 
Second, it ports into Revit and does some heavy lifting. Any screw-up and you are going to crash faster than you can count to two. 
Please roll that change back to what it was. There is no benefit in Auto-running Dynamo.

**Comment by andydandy74** [comment] 2015-03-30 04:21
:+1: 
I guess in sandbox mode it would make more sense, but not on top of Revit.
Also, I noticed I managed to switch involuntarily from Manual to Autorun several times - probably because I was moving my scrollwheel and the dropdown was somehow focussed?

**Comment by monikaprabhu** [comment] 2015-03-30 05:47
http://adsk-oss.myjetbrains.com/youtrack/issue/MAGN-6825

**Comment by kronz** [comment] 2015-03-30 14:29
Hi Guys,
The run state is now saved with the file.  That is, when you open a new file, it is in run auto by default.  If you open an old file before run auto was the default state, the file will be in manual.  If you save a file in manual, it will open in manual.  If you save in auto, it will open in auto.   Does that make more sense to you?

Thanks
-Z

**Comment by dbaldacchino** [comment] 2015-03-30 15:26
We need a "safe mode". I've had a problem with a workspace that was saved with Auto enabled, and I couldn't get to open it to make edits as it kept crashing/hanging up. We need a way to go all manual so we can troubleshoot. Perhaps if Dynamo crashes it should open everything in Manual? Or give us an option to override the setting of each workspace and open in Manual (what I'm dubbing as "Safe Mode").

**Comment by ksobon** [comment] 2015-03-30 16:03
@kronz forcing/saving with autorun is a tricky proposition. You can do that in Grasshopper because it allows you to a: recover autosaved files if you crashed. b: if you crashed next time you open it doesn't try to resolve the definition. it shows you a warning and puts a lock on it so that your machine doesnt perpetually crash. Now since Dynamo doesnt have any of these abilities then for now its just better to always open in Manual mode. When I start a new file it should be manual and when I close it should switch it to manual. It was just fine as it was in previous releases.

**Comment by andydandy74** [comment] 2015-03-30 16:49
Couldn't agree more.

**Comment by holyjewsus** [comment] 2015-03-30 16:54
Hey Guys, crash protection atleast has been added in the last few days and should make it to daily builds soon.

**Comment by riteshchandawar** [comment] 2015-03-31 06:38
@dbaldacchino , for now if your file keeps on crashing on opening, then you can change its saved state by opening DYN in notepad and change RunType="Manual".

Thanks,
Ritesh

**Comment by monikaprabhu** [comment] 2015-03-31 07:46
Ive filed an issue MAGN-6825 to track this request from user - Change Default Run mode to Manual 
Why don't we save the last used option among (Run manual or auto) as the settings while loading Dynamo next time or when starting a new file. So the user is not forced to use Auto. Any body want to vote for this idea?

**Comment by andydandy74** [comment] 2015-03-31 08:13
If the default run mode for *new* files were changed to Manual, that'd be great. 
I don't have any strong feelings regarding saving the run mode as I barely ever use automatic run mode in any case.

**Comment by dbaldacchino** [comment] 2015-03-31 16:12
Thanks Ritesh., that should work.

I tend to turn on Automatic once I have a stable graph, but I can see it being a bit dangerous to have it on by default. for example what if you launch it when the wrong Revit file is active? It could do some serious damage. I also think that rather than just flash for a second when opened, that the Revit file that the graph will control should be made a bit more prominent and stay visible.

**Comment by dimven** [comment] 2015-04-03 04:19
+1 
I think that the option to save the run state between files is great, but please return the default behavior on a new file to Manual.

**Comment by kronz** [comment] 2015-04-06 13:31
Hi all, 
Thanks for the feedback on run automatic, it’s clear that we need to make some adjustments.  The Dynamo team has wanted to make this switch for a very long time and I’d like to say a little about why.
-Dynamo is an exploratory Language. For many operations, it is important for users to get immediate feedback on the work that they do.  This is recognized in many education and computer science circles as being very effective ways to work quickly without accumulating bugs that are difficult to track down later. Unlike code/compile/run types of operations, Dynamo has the opportunity to tighten the loop and give constant feedback on design decisions and constant feedback on code validation.
-Dynamo is a very different environment for design than many people are used to.  One of the things that we consistently see in new users is befuddlement about why they are not seeing any changes in their data when they make changes in the graph.  Our hypothesis is that the learning curve will be much more approachable when users have immediate response to early stage graphs.  
-Dynamo is increasingly becoming an application that interacts with more applications than Revit.  Revit is relatively slow, but there are many applications that have a faster response time.  We want to start pushing for higher performance rather than to the lowerest common denominator in terms of performance
-Dynamo is increasingly being used for more computation only needing internal executions.  As we see users relying on Dynamo geometry, Dynamo list management, and Dynamo data interactions in addition to and sometimes iinstead to Revit elements, we have the opportunity to give near instant feedback.
- Rather than backing off on run automatically, the intention is to allow for more fine grained control over where and when the graph executes.  So, imagine the ability to turn off the automatic execution of slow running operations rather than turning off the entire operation.

In the meantime, the expected behavior is this:
- New files created from scratch open in Auto, so users should get dynamic interaction until such time as things slow down, then they can change it to manual if needed.  Manual setting is then saved with the particular file and users will not have to think about it again if they don’t want to.
- Files Save their run state.  Files that have become slow or for users who prefer run auto, there is only a one time change that needs to happen to a file.
- Files that crash will automatically be saved in a manual state.  Any variation from this is a bug.  In the event that this manual state is not created for a crashing file, there is a “plan B” approach:  edit the .dyn file in a text editor, changing RunType="Automatic" to RunType="Manual"

**Comment by andydandy74** [comment] 2015-04-07 04:22
@kronz - *All* the user feedback you got here was to please *not* default to auto run. Which apparently is something you're not prepared to do for, lets say, philosophical reasons. Fine - after all it's your product. But why not make the default run mode something that can be saved as a setting? New users will likely not touch that setting and can use Dynamo in automatic mode as an "exploratory" language the way you're intending. And seasoned users can have Dynamo default to non-automatic execution if they so wish. 
I remember distinctly how annoying it was before Dynamo could save settings and we had to reconfigure stuff in each new session (turning on/off the console etc.). This (having to switch from auto to manual) is the same thing happening again, only we would now have to do it for each graph, not just once per session.

**Comment by kronz** [comment] 2015-04-07 12:45
@andydandy74 , yes, we are working on having both project level and application level settings available as a general "prerences" functionality, and this is a behavior that would be excellent to put in that area.  

Some questions, 
- when you are making your workflows, if you do leave on run automatically, how deep into a brand new file do you get before automatic execution creates lag? 
- Are you immediately placing nodes that create or modify Revit elements? (Say, the first 5 nodes?)
- How often are you starting a new file versus opening an older "seed" file to create a new workflow based on it?
- Is it a frequent occurrence that you are opening one Dynamo file in multiple Revit files? 
- Were you ever running into the problem before (0.7.5) of having the application in Run-Auto for a small/lightweight file and opening a big file that was now in run-automatic because of the application level setting?

**Comment by andydandy74** [comment] 2015-04-07 12:59
Preferences - that sounds very good.
As to your questions:
1) I hardly ever use Automatic when developing workflows. Basically I only use it in the class room - for which it is awesome btw.
2) No, usually I start with either a) computing stuff or b) retrieving element collections from a Revit model.
3) I work from new files perhaps 80% of the time.
4) Definitely - this is usually the case.
5) No.

**Comment by ksobon** [comment] 2015-04-07 15:12
1. I Disable AutoRun the minute I start Dynamo. That's what this whole fuss is all about. I think Dynamo has an Identity crisis and its trying too hard to be like that "other" visual programming software made by that "other" company. :-)
2. Sometimes I might. I know what you are getting at, and the issue is not how long it takes for me to crash Dynamo, but its more about that if I had unfortunately saved my file with the AutoRun on and then trying to open it crashes it. Manually changing the text file is not a very user friendly solution. I wouldnt mind there to be a AutoSave which I had already expressed, and in case that my file did crash and it was in the AutoRun state, why not just set up the AutoSave so that it saves after the last successful node evaluation. that will prevent a file from being saved with a problematic node in definition. Also, if for some reason there was still an issue with the file or someone simply wanted to change the state run, lets give users ability to disable solver when opening the file (of course not every time, but after a crash). 
3. I pretty much start a new file every time, but I would love to start from an existing one. Problem is that I can't copy between them so I spend a lot of time working around that issue.
4. I would do that only because I can't open multiple Dynamo definitions in one Revit session and my way to copy stuff from one to another is to open multiple sessions of Revit and Dynamo so I can see what I was working on previously if I need to borrow from it. It's quite annoying that one would have to do that. 
5. no

**Comment by dimven** [comment] 2015-04-10 10:25
Just now I **forgot**  _(Friday afternoon here and in a hurry to wrap things up and go home)_  to turn off AutoRun for a simple new graph that reads and writes some data to excel and got stuck into an infinite loop. No Revit loaded, just Dynamo 0.8 in  Sandbox mode.  :(

1) I don't. Usually it's on only when I forget to turn it off. However I do use it a lot when presenting a graphical workflow to somebody - it's really great for that.
2) Rarely. In most of those cases it's usually some python code which most of the times does not get affected by AutoRun.
3) I start a new file about 2/3 of the time.
4) I've never tried it, to be honest. I loosely remember that last time I had Dynamo running along two instances of Revit, I could only open one session of Dynamo.( it was probably back around version 0.74)
5) Nope.

**Comment by jbenoit44** [comment] 2015-04-17 07:03
when you are making your workflows, if you do leave on run automatically, how deep into a brand new file do you get before automatic execution creates lag?
1-never run auto until all is fine; because it freeze at each error
Are you immediately placing nodes that create or modify Revit elements? (Say, the first 5 nodes?)
2-no, first 5 usually collect data.
How often are you starting a new file versus opening an older "seed" file to create a new workflow based on it?
3-unless it is for an improvement, new 100%
Is it a frequent occurrence that you are opening one Dynamo file in multiple Revit files?
4-always
Were you ever running into the problem before (0.7.5) of having the application in Run-Auto for a small/lightweight file and opening a big file that was now in run-automatic because of the application level setting?
5-no. run auto is stable only when all is fine. my advice to user is to set Auto when they work on the topic the definition was meant for. 

My ideal behavior would be to have dynamo run on events, like save or SWC.  should be doable I guess.

**Comment by sharadkjaiswal** [comment] 2016-04-26 07:20
I think we have made considerable improvements in the stability and also add few new features to address some of the issues caused by Run Automatic, such  as automatic backup, open in manual mode etc. So at this point this may not be a real issue and I am going to close this issue. 

If you all still feel that this needs to be addressed please feel free to re-open this with your comments and arguments. Thanks for providing us your valuable feedback.

**Closed** 2016-04-26 07:20 UTC
Labels: Improvement
