### ISSUE TITLE
Freezing of Dynamo after long exploring of the watch node data 

### ISSUE THREAD

**Issue by Izzo3k** [DynamoDS/Dynamo#6803] opened 2016-06-28 14:57 UTC
If this issue is with Dynamo for Revit, please post your issue on the [Dynamo for Revit Issues page](https://github.com/DynamoDS/DynamoRevit/issues).

If this issue is **not** a bug report or improvement request, please check the [Dynamo forum](https://forum.dynamobim.com/), and start a thread there to discuss your issue.
## Dynamo version

1.0.0.1180
## Operating system

Windows 7
## What did you do?

Scrooled up and down watch node data
## What did you expect to see?

Only watch node data with no freezing
## What did you see instead?

Dynamo has freezed and showed no signs of life. When I pressed window close button, there was ABSOLUTELY NO REACTION, there even didn't apear message that Dynamo didn't respond. There was no options I could use except killing process with task manager.

![dynamo](https://cloud.githubusercontent.com/assets/20189252/16420370/b7493b2c-3d59-11e6-9cf3-032f97dfb606.jpg)

**Comment by ke-yu** [comment] 2016-06-29 04:17
Hi @Izzo3k , are you able to reproduce it?

**Comment by smangarole** [comment] 2017-06-19 18:59
I cannot reproduce this in latest Dynamo Studio (1.3.0). Closing this issue.

**Closed by smangarole** 2017-06-19 18:59 UTC
Labels: Waiting for feedback
