### ISSUE TITLE
Reading Data from Excel file workbook failed

### ISSUE THREAD

**Issue by mariusvanwyk2216** [DynamoDS/Dynamo#5282] opened 2015-09-11 11:50 UTC
Using Dynamo 0.8.2.2392 and trying to read excel file to then at the end create sheets in Revit 2015. Got stuck at reading from excel file. 

I am totally new to (never tried any form of programming before) a revit user trying to widen his horizons.....
![view of excel file and dynamo fail to read](https://cloud.githubusercontent.com/assets/14234026/9814137/f12c9be4-588b-11e5-8756-a7fac160e4b5.png)

**Comment by monikaprabhu** [comment] 2015-09-15 06:00
@mariusvanwyk2216 - what is the warning on the excel node - please click on the node that is yellow (excel node) and copy paste the warning displayed and send it back to us. check if the excel and sheet name are correct.

**Comment by mariusvanwyk2216** [comment] 2015-09-15 14:38
Hi,

I replaced the readfromfile with the read excel from bumblebee and it works.

[image: Inline images 1]

Marius Van Wyk
082-863-6651 [Mobile]

**Comment by aparajit-pratap** [comment] 2015-09-16 02:47
@monikaprabhu could you create a bug for this? I'll take a look later.

**Comment by monikaprabhu** [comment] 2015-09-17 04:04
@mariusvanwyk2216 , @aparajit-pratap  I cannot reproduce this on 0.8.2. 2392 or the latest daily. Please provide more info and send me the warning on excel node - so we know what is the error thrown - which version of Microsoft office are you using ?

**Comment by ikeough** [comment] 2016-05-04 21:42
We're closing this issue as it cannot be reproduced on more recent builds of Dynamo. Please re-open if you're still experiencing this problem, or have an example which reproduces the problem.

**Closed by ikeough** 2016-05-04 21:42 UTC
