### ISSUE TITLE
Copy-paste Notes

### ISSUE THREAD

**Issue by ondejcik** [DynamoDS/Dynamo#4133] opened 2015-03-30 12:47 UTC
Hi,

When copy pasting nodes and notes together, only nodes of copied objects are selected. This is very annoying especially when all objects are initially placed over other nodes.

**Comment by andydandy74** [comment] 2015-03-30 12:51
duplicate of #332

**Comment by monikaprabhu** [comment] 2015-03-31 06:54
@ondejcik , I tried to copy paste a few nodes and note together in latest daily build 
The pasted node is highlighted at my end, and not copied node. Are you using the latest build ? 
We already have an issue filed for this MAGN-263. 
![untitled](https://cloud.githubusercontent.com/assets/5218721/6913638/2588f836-d7b5-11e4-9017-348325bca6b8.png)

**Comment by ondejcik** [comment] 2015-03-31 07:26
@monikaprabhu , even at your picture NoDe is highlighted, but NOTE is not and that is my comment.

**Comment by monikaprabhu** [comment] 2015-03-31 07:34
@ondejcik , Thanks for clarifying! Yes I see that! MAGN-263 is to track the notes are not highlighted. Will follow up the developer on this.

**Comment by Benglin** [comment] 2015-04-06 02:31
Hi guys, this is now fixed with the following pull request:

https://github.com/DynamoDS/Dynamo/pull/4172

**Closed** 2016-06-23 05:58 UTC
Labels: Bug
