### ISSUE TITLE
Curve.Extrude - Warning: Internal error, please report: Dereferencing a non-pointer

### ISSUE THREAD

**Issue by sunda022** [DynamoDS/Dynamo#7221] opened 2016-09-29 16:19 UTC
If this issue is with Dynamo for Revit, please post your issue on the [Dynamo for Revit Issues page](https://github.com/DynamoDS/DynamoRevit/issues).

If this issue is **not** a bug report or improvement request, please check the [Dynamo forum](https://forum.dynamobim.com/), and start a thread there to discuss your issue.
## Dynamo version

1.1
## Operating system

 Windows 7

What did you do? 

Curve.Extrude. Entered an array of curves and one vector. Recieved an error "
Warning: Internal error, please report: Dereferencing a non-pointer"
## What did you expect to see?

Extruded curves
## What did you see instead?

Warning

**Comment by ke-yu** [comment] 2016-10-07 02:54
hi @sunda022 could you provide more information about this error? Or could you share .dyn file?

**Comment by johnpierson** [comment] 2018-11-29 15:53
Closing this as the issue is very old and we needed more information. Please reopen and update if this is still an issue for you.

**Closed by johnpierson** 2018-11-29 15:53 UTC
Labels: 1.x
