### ISSUE TITLE
Crash report from Dynamo 2.3.0.5885

### ISSUE THREAD

**Issue by DavePlumb** [DynamoDS/Dynamo#10418] opened 2020-02-26 15:34 UTC
# Issue Description
Please fill in the following information to help us reproduce the issue:

### What did you do?
Copy a Group from one graph & Paste into another
Crash happened @ Paste

### What did you expect to see?
(Fill in here)

### What did you see instead?
(Fill in here)

### What packages or external references (if any) were used?
(Fill in here)

### Stack Trace
```
(From the Dynamo crash window select 'Details' -> 'Copy' and paste here)
```

---
OS: `Microsoft Windows NT 10.0.18363.0`
CLR: `4.0.30319.42000`
Dynamo: `2.3.0.5885`

**Comment by Amoursol** [comment] 2020-03-09 20:39
Hello @DavePlumb,

In order to reproduce this crash we need a little more information as I have been unable to reproduce this. Would you be able to please attach the Dynamo graph that this fails upon?

**Comment by Amoursol** [comment] 2020-03-30 20:29
Hello @DavePlumb - As we have not received any additional information to this issue and cannot progress any further, we are going to close it for now. Please reopen with additional information if you run into this issue again.

**Closed by Amoursol** 2020-03-30 20:29 UTC
Labels: crash, needs more info
