### ISSUE TITLE
List.RemoveItemAtIndex doesn't work with negative index

### ISSUE THREAD

**Issue by josols** [DynamoDS/Dynamo#13162] opened 2022-08-02 13:01 UTC
If this issue is with Dynamo for Revit, please post your issue on the [Dynamo for Revit Issues page](https://github.com/DynamoDS/DynamoRevit/issues).

If this issue is **not** a bug report or improvement request, please check the [Dynamo forum](https://forum.dynamobim.com/), and start a thread there to discuss your issue.

## Dynamo version

2.15

## Operating system

win 10 entreprise

## What did you do? 

Tried to use List.RemoveItemAtIndex with negative index marker

## What did you expect to see?

With -1 as integer input I would expect last item in list to be removed. I'm pretty sure it has worked this way before?

## What did you see instead?

Nothing happens and no error message:
![image](https://user-images.githubusercontent.com/7080648/182380785-0bb75314-a018-424f-b501-d965f5815367.png)

**Comment by QilongTang** [comment] 2022-08-02 13:25
Thank you @josols for reporting this, we appreciate you noticing this. This behavior has been modified around 8 years ago in this commit: https://github.com/DynamoDS/Dynamo/commit/966aedbc4f99538d711951370342015415f39e67. Ever since that, Dynamo has been only capable of dealing with non-negative indices. I believe we had to fix it in cases of other bugs it causes.

**Comment by josols** [comment] 2022-08-03 08:54
Right. I figured out that List.DropItems works with negative integers, so I probably switched the two nodes up. I guess then it can be closed if there is no plausible fix.

**Comment by QilongTang** [comment] 2022-08-03 19:26
@josols I'm afraid that is the case, closing

**Closed by QilongTang** 2022-08-03 19:26 UTC

**Comment by mjkkirschner** [comment] 2022-08-04 15:28
Thanks @QilongTang for looking into some of the history here - I did want to add a bit more confusion to the mix!
While it appears that all indexing nodes no longer work with negative indices by design - DesignScript and the internal indexing methods actually do. (`ValueAtIndex`) as it is part of the language spec and grammar - (I am working on indexing in MSIL atm, so this is an issue for me currently)


![Screen Shot 2022-08-04 at 11 25 50 AM](https://user-images.githubusercontent.com/508936/182885894-f21aa54c-f66c-427c-9eb4-269f8755c82d.png)

Doesn't change anything about your above conversation, but it is worth noting.
