### ISSUE TITLE
Read-Only server permissions and Node/Package Paths

### ISSUE THREAD

**Issue by rbosborne** [DynamoDS/Dynamo#5711] opened 2015-11-13 02:40 UTC
I set up all the common packages and scripts in one location on our server thinking I could enable all users to use a common set of packages and custom nodes (using 0.8.2 - holding off on deploying 0.9 for a few weeks), tested it and it worked fine.....for me (I have full priviledges).  Then after pushing out to everyone, I start getting the calls that..."This doesn't work at all...Dynamo freezes up and won't run".  Lo and behold - it's the write permissions. 

Apparently, if the Custom Node and Package Path (and/or the location where pre-made scripts are saved) is Read-Only ....Dynamo-No-Go.  It literally freezes up as it starts to open.  Change the node paths to a location with full permission and open a script from your desktop - it works great.  Dynamo seemingly insists on having full write permission to ANY custom node/package path and to the location where a script is opened from.

Here's the rub - just because we want people using scripts we create doesn't mean we trust them enough to give them full permissions.  I think this needs to be addressed before 1.0 comes out for sure.....it's analogous to Revit Libraries - we have them set up as read-only to protect them from unwanted editors - once someone has loaded something, they can edit and use in their project, but the read-only permission on the server does not prevent them from opening Revit and loading files from the read-only library - it only prevents them from saving.  In Dynamo - the read-only permission literally prevents Dynamo from fully opening from the start.

Ideally, I would keep all of my scripts (intended for repeated re-use) and nodes/packages in a safe location on the server that can be accessed by all but not written to.  The user would then open a script from that location, run it on their project, and either throw away after it's run or save it to their project folder.  

Is there something in the way Dynamo is built that makes this impossible or is it just an oversight that can be easily fixed? I'm not good enough to work on the source code so all i can do is just post and hope someone can shed some light on this..

**Comment by mjkkirschner** [comment] 2015-11-13 02:46
@rbosborne I believe we have this tracked - I think the issue is a backup folder wanting to be created. I will try to find the tracking number.

**Comment by ikeough** [comment] 2016-04-21 21:51
@mjkkirschner Ever find that tracking number? :)

**Comment by mynovmbr** [comment] 2016-04-21 22:04
@ikeough @mjkkirschner Interesting, I'm also trying to find some server solution today, looking forward to the answer too! If you guys have time, please also take a look at my post on forum: http://dynamobim.org/forums/topic/dynamo-packagecustom-nodes-deployment/#post-44417 Thanks!

**Comment by kronz** [comment] 2016-04-26 13:08
Internally tracking as MAGN-10004

**Comment by jnealb** [comment] 2016-05-24 20:07
@mynovmbr @rbosborne We believe this is fixed with the latest daily build, can you please check?

**Comment by kronz** [comment] 2016-05-31 01:55
https://github.com/DynamoDS/Dynamo/pull/6661

**Closed by kronz** 2016-05-31 01:55 UTC
Labels: Improvement, Major, Package Manager

**Comment by QilongTang** [comment] 2016-05-31 01:58
https://github.com/DynamoDS/Dynamo/pull/6657
