### ISSUE TITLE
Crash report from Dynamo 2.4.0.6186

### ISSUE THREAD

**Issue by cromlyngames** [DynamoDS/Dynamo#10047] opened 2019-10-10 13:54 UTC
# Issue Description
Please fill in the following information to help us reproduce the issue:

### What did you do?
tried to move a yellowed out box in dynamo sandbox. Yellow error was saying it could not find a file in system

### What did you expect to see?
(Fill in here)

### What did you see instead?
(Fill in here)

### What packages or external references (if any) were used?
dynamo sandbox

### Stack Trace
```
Could not load file or assembly 'file:///C:\WINDOWS\system32\LibG.ProtoInterface.dll' or one of its dependencies. The system cannot find the file specified.

   at Autodesk.DesignScript.Geometry.HostFactory.get_Factory()
   at Autodesk.DesignScript.Geometry.Vector.XAxis()
   at Dynamo.Manipulation.MousePointManipulator.AssignInputNodes()
   at Dynamo.Manipulation.NodeManipulator.GenerateRenderPackages()
   at Dynamo.Manipulation.NodeManipulator.DrawManipulator()
   at Dynamo.Manipulation.NodeManipulator..ctor(NodeModel node, DynamoManipulationExtension manipulatorContext)
   at Dynamo.Manipulation.MousePointManipulatorFactory.Create(NodeModel node, DynamoManipulationExtension manipulatorContext)
   at System.Linq.Enumerable.WhereSelectArrayIterator`2.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Dynamo.Manipulation.ZeroTouchManipulatorFactory.Create(NodeModel node, DynamoManipulationExtension manipulatorContext)
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Dynamo.Manipulation.ManipulatorDaemon.CreateManipulator(NodeModel model, DynamoManipulationExtension manipulatorContext)
   at Dynamo.Manipulation.DynamoManipulationExtension.TryCreateManipulator(NodeModel node)
   at Dynamo.Manipulation.DynamoManipulationExtension.CreateManipulators(IEnumerable`1 nodes)
   at Dynamo.Wpf.Extensions.ViewLoadedParams.OnSelectionCollectionChanged(Object sender, NotifyCollectionChangedEventArgs notifyCollectionChangedEventArgs)
   at System.Collections.Specialized.NotifyCollectionChangedEventHandler.Invoke(Object sender, NotifyCollectionChangedEventArgs e)
   at System.Collections.ObjectModel.ObservableCollection`1.OnCollectionChanged(NotifyCollectionChangedEventArgs e)
   at System.Collections.ObjectModel.ObservableCollection`1.InsertItem(Int32 index, T item)
   at Dynamo.Models.DynamoModel.SelectModelImpl(SelectModelCommand command)
   at Dynamo.Models.DynamoModel.ExecuteCommand(RecordableCommand command)
   at Dynamo.Controls.NodeView.topControl_MouseLeftButtonDown(Object sender, MouseButtonEventArgs e)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.ReRaiseEventAs(DependencyObject sender, RoutedEventArgs args, RoutedEvent newEvent)
   at System.Windows.UIElement.OnMouseDownThunk(Object sender, MouseButtonEventArgs e)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.InputManager.ProcessInput(InputEventArgs input)
   at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
   at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at DynamoSandbox.DynamoCoreSetup.RunApplication(Application app)
```

---
OS: `Microsoft Windows NT 6.2.9200.0`
CLR: `4.0.30319.42000`
Dynamo: `2.4.0.6186`

**Comment by mjkkirschner** [comment] 2019-10-10 14:00
@aparajit-pratap - this looks like a crash coming from the direct manipulation extension if libG is not fully loaded?

**Comment by cromlyngames** [comment] 2019-10-10 14:18
yeah, I think so, I'm just not sure why LibG is missing. Sandbox was only installed yesterday!

**Comment by mjkkirschner** [comment] 2019-10-10 15:11
@cromlyngames - sandbox requires specific adsk products to be installed for libG to load properly DynamoSandbox will work without geometry (or should) - in this case if you do not have any of those adsk products -

revit,civil3d,formit,robot structural analysis - then I would expect geometry not to work - 
what is unexpected is the crash.

**Comment by aparajit-pratap** [comment] 2019-10-11 14:24
I think I put in a guard to disable direct manipulation altogether when LibG fails to load here: https://github.com/DynamoDS/Dynamo/pull/7029 so I'm not sure what could cause this to reoccur. Will need to investigate.

**Comment by mjkkirschner** [comment] 2019-10-11 14:55
@aparajit-pratap what if the output is a list<null>

**Comment by cromlyngames** [comment] 2019-10-14 10:41
> @cromlyngames - sandbox requires specific adsk products to be installed for libG to load properly DynamoSandbox will work without geometry (or should) - in this case if you do not have any of those adsk products -
> 
> revit,civil3d,formit,robot structural analysis - then I would expect geometry not to work -
> what is unexpected is the crash.

The only reason I looked at Sandbox was because it was supposed to run fine without Revit. I don't really want to spend £700  on a program that is not being used. 

I do have LibG.Interface.dll  is this a totally different file to LibG.ProtoInterface.dll ?

**Comment by aparajit-pratap** [comment] 2019-10-14 13:40
@cromlyngames, yes, you should be having both LibG.Interface.dll and LibG.ProtoInterface.dll. They come with sandbox however, I think the problem here is you don't have a copy of ASM without which geometry will fail to work in sandbox. ASM dll's come with installations of certain Autodesk products like Revit. Do you have any other Autodesk products installed like AutoCAD? If not, you'll be unable to use geometry nodes in sandbox. The rest should work fine and this crash too is unexpected.

**Comment by cromlyngames** [comment] 2019-10-15 13:26
ok, so the reported error message is not the actual error?  Nuts.
The only other autodesk Product I have is 3dsMax. I'll have to try and find
how everyone else on my uni course is running Dynamo sandbox.

**Comment by cromlyngames** [comment] 2019-10-21 13:08
There is something fundamentally broken here. I have installed Autocad 2018, dynamomax sandbox is still broken. different geometry boxes give different errors.

[TEMP.txt](https://github.com/DynamoDS/Dynamo/files/3750925/TEMP.txt)
![temp](https://user-images.githubusercontent.com/18384618/67207814-30fa3680-f40c-11e9-8bab-96edf78971c8.png)

**Comment by mjkkirschner** [comment] 2019-10-21 15:42
Hi @cromlyngames - 
currently only these applications will enable the geometry library in DynamoSandbox:
`revit, civil3d, formit, robot structural analysis` autocad is not on that list.

it's possible something else is going on, but to debug properly it would be helpful to be in a known good state.

**Comment by cromlyngames** [comment] 2019-10-21 16:54
aparajit-pratap mentioned Autocad as another possible. Time to see if I can get my money back. I'll try with revit now, but this is seriously souring me on the whole thing.

**Comment by mjkkirschner** [comment] 2019-10-21 16:58
if you're in a uni course as you stated above you can download Revit etc for free - https://www.autodesk.com/education/free-software/revit

**Comment by aparajit-pratap** [comment] 2019-10-29 19:03
@cromlyngames sorry that Autocad didn't work for you. I probably gave you inaccurate information as I thought Civil3D piggybacked on Autocad. Anyway, now that you have Autocad, and if you don't want to install other products, you can also copy all ASM, TBB and T-Splines dll's from your AutoCAD install location and paste them into your sandbox install location here: `C:\Program Files\Dynamo\Dynamo Core\2\libg_224_4_0`. Note that you need to choose the `libg_xxx` folder where the `xxx` matches with the ASM version you have in AutoCAD. 
![image](https://user-images.githubusercontent.com/5710686/67800169-359e9a80-fa5d-11e9-9580-7c71b247a19b.png)

**Comment by cromlyngames** [comment] 2019-11-01 09:30
Thanks @aparajit-pratap that seems to have done the trick.

@mjkkirschner - i have been able to run the student download stack on my personal computer, but I'm a part time student who is expected to bring the skills into work. I'm trying to avoid potential clashes between academic and commercial licences as far as possible. At the same time, I'm encouraged to learn as much as I can and develop these skills, and dynamo might get a wider userbase. 
I've not been able to install revit to my work computer - it just errors out. That's a different bug I'm pursuing elsewhere :)

**Comment by mjkkirschner** [comment] 2019-11-18 18:34
bringing this into the backlog to better communicate what adsk products are required for geometry to workin sandbox. It's arguable that the initial crash would not have occurred if we have better communicated requirements.

**Comment by cromlyngames** [comment] 2019-11-18 21:40
I was able to get both methods working - revit student + sandbox on my
personal laptop,   autocad library transplant + dynamo sandbox on my work
laptop.
The joys of being a part time student :)  Thankyou both for your help.

**Comment by QilongTang** [comment] 2019-11-19 10:20
@cromlyngames Thank you for working with us. Closing.

**Comment by aparajit-pratap** [comment] 2019-11-19 21:30
The crash with direct manipulation is yet to be resolved. It is reproducible; I've created a task here: https://github.com/DynamoDS/Dynamo/issues/10047. Reopening.

**Closed** 2020-06-19 17:03 UTC
Labels: 2.x, Graphics, crash, error/warning/crash, good first issue, tracked
