### ISSUE TITLE
Dynamo 1.0.0 will not install dynamo core

### ISSUE THREAD

**Issue by jluebker** [DynamoDS/Dynamo#6555] opened 2016-04-30 19:05 UTC
Dynamo 1.0.0
windows 8.1

Tried installing the latest stable build (1.0.0) and received the error that "Dynamo Core will not be installed as there is already a newer version installed."

![capture](https://cloud.githubusercontent.com/assets/4041748/14937980/442eff80-0ecb-11e6-9ecd-8789c224d078.PNG)

I've tried removing all previous version of dynamo (0.9.2, and a daily build of 1.0.1), removing all left over files of any version of dynamo, removed any left overs of github repositories, run a clean of any temp files and a registry repair using ccleaner, and manually deleted any other vestiges of dynamo on the computer, and of course restated after all this.

The error persists and dynamo will not install correctly so that I am unable to install this version at all.

**Comment by mjkkirschner** [comment] 2016-04-30 21:59
@Racel @kronz similar to what you guys experienced? What was the fix again?

**Comment by jluebker** [comment] 2016-04-30 22:12
Currently none. I've moved on to manually purging any mention of dynamo from the registry. But still getting the error....

**Comment by mjkkirschner** [comment] 2016-04-30 22:14
@kronz and @Racel may know more, but I *think* https://support.microsoft.com/en-us/mats/program_install_and_uninstall this helped them.

use with caution.

**Comment by jluebker** [comment] 2016-04-30 23:20
did it work for you? dynamo was not in the list of programs did you find the program key there "not in list" option?

**Comment by sharadkjaiswal** [comment] 2016-05-01 15:22
Dynamo For Revit 1.0 onwards installs two components, DynamoCore and DynamoRevit. Since you were using the daily build 1.0.1 which is higher than DynamoCore 1.0.0, it didn't install DynamoCore. However if you want to uninstall the existing DynamoCore, then you can uninstall it from Add and Remove Program of Control Panel.

**Comment by jluebker** [comment] 2016-05-01 15:24
I did uninstall the daily build. Infact I scrubbed it from my registry and removed all traces of "dynamo" from both the registry and the file system. The problem still persists...

**Comment by jluebker** [comment] 2016-05-01 15:30
I went ahead and installed the latest daily build for the time being.

**Comment by QilongTang** [comment] 2016-05-02 04:57
@sharadkjaiswal @mjkkirschner @jluebker  I had a similar issue, uninstalled everything then the first install of 1.0 from our website failed, then I used Fixit, even though the dynamo was not in the list, it did the magic for me. The second install succeeded.

**Comment by Racel** [comment] 2016-05-02 12:31
@jluebker - I had a similar problem, but in order for everything to work, I had to uninstall everything (including any folders associated with Dynamo) and run Microsoft fix-it (download from @mjkkirschner's link above). 

I had to uninstall all the folders found in the following:
-> Program Files\ Dynamo (everything in here needs to go)
-> Autodesk\Dynamo Studio 201x (if you have this)
-> ProgramData\Dynamo
-> Users\yourusername\AppData\Roaming\Autodesk\Dynamo Studio (if you have this)
-> Users\yourusername\AppData\Roaming\Dynamo (be careful, you may want to make copies of these folders elsewhere as these are where your custom nodes and packages are stored)
 
Hope this helps

**Comment by kronz** [comment] 2016-05-02 18:00
@sharadkjaiswal Can you share any information here about what is happening?
Just so everyone on the thread is clear, the INTENDED behavior is that, even with pre-release builds, the uninstall process needs to be clean and get ride of Core when it is uninstalled, allowing fo ra clean re-install. Anything else is a bug.

**Comment by jluebker** [comment] 2016-05-02 18:24
@Racel Yep checked all of those... ill double check again though...
@kronz the uninstall is NOT cleaning out everything. I had uninstalled the daily build and dynamo studio and it still left TONS of stuff which is what i think is causing the problems...

**Comment by sh4nnongoh** [comment] 2016-05-03 07:36
Hi @jluebker. 

When components do not get uninstalled during the uninstall process, it means that a previous installed product was not uninstalled properly. This is because whenever an application gets installed, each component in the application will be given a unique GUID and this GUID will be written to registry. During the uninstallation process, if there are components still being referenced in the registry, the product will not be uninstalled. 

The usual scenarios of why this happens is because (1) the user deletes the application's data in the installed location, and/or (2) delete the registry keys manually without uninstalling it through the Add/Remove Programs.

When installing an application, the installer writes to the registry in multiple places. Some of these keypaths do not have the "Dynamo" name but are addressed by the component GUIDs. Hence, if you wish to delete the registry manually you should also find all the components written to registry and delete it; not just those named "Dynamo". But of cause this will be a daunting task.

The Microsoft Fix-It tool will help resolve all the component GUIDs errors. However you mentioned, the tool does not list any Dynamo products installed in your system. This is because you have deleted all the keypaths with "Dynamo" within them in the registry, hence the tool couldn't locate any Dynamo product. What you can do now is to find it through the product key by selecting "Not Listed". Below are the list of product keys you can try to search for and delete:

![image](https://cloud.githubusercontent.com/assets/13437033/14977215/c4323da2-1144-11e6-937c-155a3c30791b.png)

**Comment by jluebker** [comment] 2016-05-03 15:50
ok so the keys are not working. i keep getting an error "please enter a valid 38 character key". but i tried reinstalling each version of the daily builds i've installed in reverse order and using fixit to uninstall them. however by the time i got to one from earlier last month, even though it was installed fixit couldn't find it. And interestingly enough, when i've reinstalled 9.2 fixit is not seeing it either...
guess i really broke it this time... lol

**Comment by jluebker** [comment] 2016-05-03 15:53
@sh4nnongoh, thanks for the great tips. this is actually the first time i've had to resort to manually purging dynamo from y computer. i've uninstalled each version before installing the next one using windows uninstaller. so im baffled...

**Comment by jnealb** [comment] 2016-05-03 21:08
@jluebker @sh4nnongoh Classic consequence of switching installers. Going forward it should no longer happen.

**Comment by ParametricMonkey** [comment] 2016-09-19 01:05
@kronz  This is still an issue when trying to install version 1.1. It says unable to install DynamoCore 1.1 msi and fails.

**Comment by ParametricMonkey** [comment] 2016-09-19 01:25
FixIt didn't work for me. I had to use MicrosoftProgram_Install_and_Uninstall.meta.diagcab instead

**Comment by sharadkjaiswal** [comment] 2016-09-19 03:14
@ParametricMonkey can you please try installing one of the latest Dynamo 1.2.0 builds from http://dynamobuilds.com and see if the issue is resolved?

**Comment by ParametricMonkey** [comment] 2016-09-19 03:44
@sharadkjaiswal Same issue. However installer says it has been successfully installed but it doesn't appear in programs or in the Revit ribbon

**Comment by sharadkjaiswal** [comment] 2016-09-19 04:23
@ParametricMonkey, Please help me with following queries:

- Do you see Dynamo Core\1.2 folder at your install location? The default location is `C:\Program Files\Dynamo\Dynamo Core\1.2\`
- Can you try to launch Dynamo Revit\1.2\DynamoSandbox.exe, does it work? 
- By any chance, can I get access to your system through screen sharing to diagnose the issue?

**Comment by ParametricMonkey** [comment] 2016-09-19 04:25
@sharadkjaiswal 
1. yes folder is there
2. This folder/file does not exist
3. Sorry I can't allow this

**Comment by sharadkjaiswal** [comment] 2016-09-19 04:29
@ParametricMonkey so it seems DynamoCore is installed by Dynamo Revit is not installed. Can you please send me dump of list of files in Dynamo Core\1.2 folder, by using dir /s /b from command line.

**Comment by ParametricMonkey** [comment] 2016-09-20 00:12
There are no files in C:\Program Files\Dynamo\Dynamo Core\1.2 only a README.txt file

**Comment by johnpierson** [comment] 2018-11-28 14:10
Closing this as it relates to an older release. If this persists in newer versions of Dynamo please feel free to reopen and update as needed.

**Closed by johnpierson** 2018-11-28 14:10 UTC
Labels: Install, Major, bug
