### ISSUE TITLE
Dynamo crashing when using manage custom paths to folder without write permisson

### ISSUE THREAD

**Issue by ondejcik** [DynamoDS/Dynamo#6569] opened 2016-05-03 12:52 UTC
## Dynamo version
1.0.0 , 0.9.2

## Operating system
W7 64bit

## What did you do? 
We have a library of node and packages linked between several users to one place, where some users have only read permission (thay cannot write files). This was crashing dynamo on load totally. Problem was fixed when files was moved to location where user has read and write permission.

How ever i would like to have a possibility to have a central library where cutom nodes and packages are curated and not avaiable to be changed by all.

**Comment by jnealb** [comment] 2016-05-03 12:58
@ondejcik We are aware of this and are working towards a solution. Thanks.

**Comment by StevenRowland** [comment] 2016-05-03 13:15
Dynamo does not completely crash during this event, rather the process never resolves itself. Would be good if there could be an eventual timeout or validation exception thrown by an inaccessible or write protected path.

**Comment by kronz** [comment] 2016-05-03 16:55
Duplicate of 
https://github.com/DynamoDS/Dynamo/issues/5711
Pursuing internally MAGN-10004

**Closed by kronz** 2016-05-03 16:55 UTC

**Comment by jnealb** [comment] 2016-05-24 20:08
@ondejcik @StevenRowland We believe this is fixed with the latest daily build, can you please check?

**Comment by kronz** [comment] 2016-05-31 01:56
https://github.com/DynamoDS/Dynamo/pull/6661

**Comment by QilongTang** [comment] 2016-05-31 01:58
https://github.com/DynamoDS/Dynamo/pull/6657
https://github.com/DynamoDS/Dynamo/pull/6661

**Comment by ondejcik** [comment] 2016-06-09 11:12
Hi, i have let it checked, and i got report back now, that it seems to be working just fine for my colleagues without persmission to drive, thanks!
