### ISSUE TITLE
Data types in custom node inputs are not resolved correctly after migrating to JSON

### ISSUE THREAD

**Issue by andydandy74** [DynamoDS/Dynamo#8690] opened 2018-03-24 18:05 UTC
## Dynamo version

2.0.0.4467

## Operating system

Windows 7

## What did you do? 

Upgrade a custom node to JSON-based format

## What did you expect to see?

Data types in inputs to resolve correctly

## What did you see instead?

Data types in inputs not resolving correctly

Dynamo 1.3:
![grafik](https://user-images.githubusercontent.com/3014437/37867241-91955a52-2f95-11e8-90fe-43f94c060681.png)
Dynamo 2:
![grafik](https://user-images.githubusercontent.com/3014437/37867245-a1ee6240-2f95-11e8-9bfe-3c6618afbd39.png)
Warning says: Type 'DateTime' not found
Custom nodes attached below:
[ClassResolutionIssue.zip](https://github.com/DynamoDS/Dynamo/files/1844657/ClassResolutionIssue.zip)

**Comment by mjkkirschner** [comment] 2018-03-24 18:28
@aparajit-pratap @QilongTang thoughts?
@QilongTang I think we worked together on input type migration?

**Comment by mjkkirschner** [comment] 2018-03-24 18:29
@andydandy74 so in your original custom node you had written System.DateTime as the type but the migration lost information? - is that correct?

**Comment by mjkkirschner** [comment] 2018-03-24 18:31
@gregmarr thanks for checking the file, seems like a change to the `typedParameter` or `inputNode` might cause this.

**Comment by andydandy74** [comment] 2018-03-24 18:33
@mjkkirschner Correct. I included the original version in the attached zip file. 
What I found weird is that on opening the 1.3 node in 2.0 (and after saving it) the input type is correct. Only when I open it again in a new Dynamo session it looks as shown in the screenshot.

**Comment by gregmarr** [comment] 2018-03-24 18:34
@andydandy74 Can you save another copy when it shows the incorrect type?

**Comment by andydandy74** [comment] 2018-03-24 18:44
@gregmarr Sure. Attached here:
[DateTime.IsEarlier_Resaved.dyf.zip](https://github.com/DynamoDS/Dynamo/files/1844684/DateTime.IsEarlier_Resaved.dyf.zip)
Have a look at what's happening here:
![grafik](https://user-images.githubusercontent.com/3014437/37867593-65023748-2f9b-11e8-962a-0e2b44d067d1.png)
Also, the category gets wiped:
![grafik](https://user-images.githubusercontent.com/3014437/37867599-78d6d008-2f9b-11e8-8a0c-cfaca52e97ee.png)
And why would nodes and connectors neet to get new IDs?
![grafik](https://user-images.githubusercontent.com/3014437/37867623-a50041aa-2f9b-11e8-963d-1c37d5f6a767.png)

**Comment by gregmarr** [comment] 2018-03-24 18:53
So the error on the InputNode happens when reading from JSON.

They shouldn't be getting new IDs when read from JSON if they're already UUIDs.  They should definitely be keeping the ones they have already.

**Comment by mjkkirschner** [comment] 2018-03-24 19:18
@andydandy74 would you mind trying this on the latest master?

**Comment by mjkkirschner** [comment] 2018-03-24 19:19
@QilongTang @Racel it definitely appears this is a bug with deserialization of input nodes inside custom nodes.

**Comment by mjkkirschner** [comment] 2018-03-24 19:27
@QilongTang my guess is this PR:
https://github.com/DynamoDS/Dynamo/pull/8135/files

**Comment by mjkkirschner** [comment] 2018-03-24 19:36
filed as QNTM-3786

**Comment by andydandy74** [comment] 2018-03-24 20:06
@mjkkirschner I have never built Dynamo from source. I wouldn't even know where to start.

**Comment by mjkkirschner** [comment] 2018-03-25 14:55
@QilongTang @jnealb  I think this is caused by:
https://github.com/DynamoDS/Dynamo/blob/master/src/DynamoCore/Library/TypedParameter.cs#L143

**Comment by QilongTang** [comment] 2018-03-26 16:11
PR from @ramramps will address this https://github.com/DynamoDS/Dynamo/pull/8692

**Comment by jnealb** [comment] 2018-03-30 20:05
@andydandy74 @QilongTang Actually the issue is deeper and tracked with QNTM-3872.

**Comment by mjkkirschner** [comment] 2018-04-02 14:30
@andydandy74 - this won't be in the daily builds until it gets merged to RC2.0, but should be soon.

**Comment by kronz** [comment] 2018-04-13 13:31
This has been merged into 2.0

**Closed by kronz** 2018-04-13 13:31 UTC
Labels: Custom Nodes
