### ISSUE TITLE
Crash of the work program for any action

### ISSUE THREAD

**Issue by brichev** [DynamoDS/Dynamo#5714] opened 2015-11-13 14:55 UTC
Try create simple geometry (cuboid , cilinder)

**Comment by monikaprabhu** [comment] 2015-11-23 09:50
@brichev - Are you still able to reproduce this ? If so please provide information on the build number - 0.9.1.3261.

**Comment by smangarole** [comment] 2017-06-19 17:58
We have released a new version of Dynamo since this issue was opened. The issue has been waiting for feedback for almost a year. Closing due to these reasons. Please reopen if this issue resurfaces.

**Closed by smangarole** 2017-06-19 17:58 UTC
Labels: Waiting for feedback
