### ISSUE TITLE
Crash report from Dynamo 2.3.0.5331

### ISSUE THREAD

**Issue by vykrum** [DynamoDS/Dynamo#9817] opened 2019-06-27 06:25 UTC
# Issue Description
Please fill in the following information to help us reproduce the issue:

### What did you do?
Altered a function that is nested within another

### What did you expect to see?
The altered result

### What did you see instead?
A crash

### What packages or external references (if any) were used?
None

### Stack Trace
```
Exception of type 'ProtoCore.Exceptions.CompilerInternalException' was thrown.

   at ProtoCore.Core.BfsBuildSequenceTable(CodeBlock codeBlock, SymbolTable[] runtimeSymbols)
   at ProtoCore.Core.BfsBuildSequenceTable(CodeBlock codeBlock, SymbolTable[] runtimeSymbols)
   at ProtoCore.Core.BfsBuildSequenceTable(CodeBlock codeBlock, SymbolTable[] runtimeSymbols)
   at ProtoCore.Core.GenerateExecutable()
   at ProtoScript.Runners.LiveRunner.Compile(List`1 astList, Core targetCore)
   at ProtoScript.Runners.LiveRunner.CompileAndExecute(List`1 astList)
   at ProtoScript.Runners.LiveRunner.CompileAndExecuteForDeltaExecution(List`1 astList)
   at ProtoScript.Runners.LiveRunner.SynchronizeInternal(GraphSyncData syncData)
   at ProtoScript.Runners.LiveRunner.UpdateGraph(GraphSyncData syncData)
   at Dynamo.Scheduler.UpdateGraphAsyncTask.HandleTaskExecutionCore()
   at Dynamo.Scheduler.AsyncTask.Execute()
```

---
OS: `Microsoft Windows NT 6.2.9200.0`
CLR: `4.0.30319.42000`
Dynamo: `2.3.0.5331`

**Comment by mjkkirschner** [comment] 2019-08-09 16:01
@vykrum do you mean you altered a function definition that was nested inside another function definition or you only altered the inputs to a function called from inside another function?

**Comment by vykrum** [comment] 2019-08-11 10:39
@mjkkirschner Altered inputs to to function within another

**Comment by aparajit-pratap** [comment] 2019-09-09 20:28
@vykrum do you have a graph that you can share that we can use to reproduce this?

**Comment by mjkkirschner** [comment] 2019-10-07 19:46
I'm going to leave this open for now - but currently I cannot reproduce it without more specific repro steps.

**Comment by mjkkirschner** [comment] 2019-11-18 18:58
@vykrum -  thanks for reporting it, going to close this as after repeated testing we cannot reproduce it. Please reopen if it happens again.

**Closed by mjkkirschner** 2019-11-18 18:58 UTC
Labels: 2.x, Design Script, PTAL, crash, error/warning/crash
