### ISSUE TITLE
bug: Geometry.Translate node internal error

### ISSUE THREAD

**Issue by Arek3dim** [DynamoDS/Dynamo#5812] opened 2015-12-06 18:49 UTC
I hade an internal error telling me to report, here I am, is this how this works?
Warning: Internal error, please report: Dereferencing a non-pointer. (3f47aacd)
This was with the Geometry.Translate node.

![123](https://cloud.githubusercontent.com/assets/5740504/11614921/7476b084-9c6b-11e5-9c78-93cfdefd317e.png)

**Comment by mjkkirschner** [comment] 2015-12-06 23:29
@Arek3dim what was your direction input - it's hard to tell from the image, and what custom node were you using to collect the geometry? did the node actually perform the intended function and also return that warning? - thanks for reporting.

**Comment by Arek3dim** [comment] 2015-12-07 20:41
The node did not perform the intended function. However, I have noticed some "bugginess" in the custom node I was using before it, which was "RoofOrFloor.SlabShapeByPoints" from Clockwork, as I had to "copy" + "delete" + "paste" it and run manually to make it work properly, I apologize if I had to report this elsewhere.

![11](https://cloud.githubusercontent.com/assets/5740504/11639105/311417b2-9d44-11e5-9598-b0b7654f2c7a.png)

**Comment by aparajit-pratap** [comment] 2016-04-22 06:51
@Arek3dim sorry for the late response but do you still have the DYN file with you for us to reproduce this?

**Comment by smangarole** [comment] 2017-06-19 18:50
The issue has been waiting for feedback for almost a year. Closing due to this reason. Please reopen if this issue resurfaces.

**Closed by smangarole** 2017-06-19 18:50 UTC
Labels: Geometry, Revit, Waiting for feedback
