### ISSUE TITLE
Error open Dynamo

### ISSUE THREAD

**Issue by rogodra** [DynamoDS/Dynamo#7649] opened 2017-02-28 12:36 UTC
## Dynamo version 1.2
Revit 2016

## Operating system
Windows 10

## What did you do?
Open Dynamo
Dynamo works if revit is opened with Administrator or with NVIDIA graphics.

## Error:
> HRESULT: [0x80070057], Module: [General], ApiCode: [E_INVALIDARG/Invalid Arguments], Message: El parámetro no es correcto.
> 
>    en SharpDX.Result.CheckError()
>    en SharpDX.Direct3D11.Device.CreateTexture2D(Texture2DDescription& descRef, DataBox[] initialDataRef, Texture2D texture2DOut)
>    en HelixToolkit.Wpf.SharpDX.DPFCanvas.CreateAndBindTargets()
>    en HelixToolkit.Wpf.SharpDX.DPFCanvas.StartD3D()
>    en HelixToolkit.Wpf.SharpDX.DPFCanvas.RenderTechniquesManagerPropertyChanged()
>    en System.Windows.DependencyObject.OnPropertyChanged(DependencyPropertyChangedEventArgs e)
>    en System.Windows.FrameworkElement.OnPropertyChanged(DependencyPropertyChangedEventArgs e)
>    en System.Windows.DependencyObject.NotifyPropertyChange(DependencyPropertyChangedEventArgs args)
>    en System.Windows.DependencyObject.UpdateEffectiveValue(EntryIndex entryIndex, DependencyProperty dp, PropertyMetadata metadata, EffectiveValueEntry oldEntry, EffectiveValueEntry& newEntry, Boolean coerceWithDeferredReference, Boolean coerceWithCurrentValue, OperationType operationType)
>    en System.Windows.DependencyObject.SetValueCommon(DependencyProperty dp, Object value, PropertyMetadata metadata, Boolean coerceWithDeferredReference, Boolean coerceWithCurrentValue, OperationType operationType, Boolean isInternal)
>    en System.Windows.DependencyObject.SetValue(DependencyProperty dp, Object value)
>    en HelixToolkit.Wpf.SharpDX.Viewport3DX.RenderTechniquesManagerPropertyChanged()
>    en System.Windows.DependencyObject.OnPropertyChanged(DependencyPropertyChangedEventArgs e)
>    en System.Windows.FrameworkElement.OnPropertyChanged(DependencyPropertyChangedEventArgs e)
>    en System.Windows.DependencyObject.NotifyPropertyChange(DependencyPropertyChangedEventArgs args)
>    en System.Windows.DependencyObject.UpdateEffectiveValue(EntryIndex entryIndex, DependencyProperty dp, PropertyMetadata metadata, EffectiveValueEntry oldEntry, EffectiveValueEntry& newEntry, Boolean coerceWithDeferredReference, Boolean coerceWithCurrentValue, OperationType operationType)
>    en System.Windows.DependencyObject.InvalidateProperty(DependencyProperty dp, Boolean preserveCurrentValue)
>    en System.Windows.Data.BindingExpressionBase.Invalidate(Boolean isASubPropertyChange)
>    en System.Windows.Data.BindingExpression.TransferValue(Object newValue, Boolean isASubPropertyChange)
>    en System.Windows.Data.BindingExpression.Activate(Object item)
>    en System.Windows.Data.BindingExpression.AttachToContext(AttachAttempt attempt)
>    en System.Windows.Data.BindingExpression.MS.Internal.Data.IDataBindEngineClient.AttachToContext(Boolean lastChance)
>    en MS.Internal.Data.DataBindEngine.Task.Run(Boolean lastChance)
>    en MS.Internal.Data.DataBindEngine.Run(Object arg)
>    en System.Windows.ContextLayoutManager.fireLayoutUpdateEvent()
>    en System.Windows.ContextLayoutManager.UpdateLayout()
>    en System.Windows.ContextLayoutManager.UpdateLayoutCallback(Object arg)
>    en System.Windows.Media.MediaContext.FireInvokeOnRenderCallbacks()
>    en System.Windows.Media.MediaContext.RenderMessageHandlerCore(Object resizedCompositionTarget)
>    en System.Windows.Media.MediaContext.RenderMessageHandler(Object resizedCompositionTarget)
>    en System.Windows.Interop.HwndTarget.OnResize()
>    en System.Windows.Interop.HwndTarget.HandleMessage(WindowMessage msg, IntPtr wparam, IntPtr lparam)
>    en System.Windows.Interop.HwndSource.HwndTargetFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
>    en MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
>    en MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
>    en System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
>    en System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by alfarok** [comment] 2017-10-18 13:26
Cannot reproduce without more info, closing

**Closed by alfarok** 2017-10-18 13:26 UTC
