### ISSUE TITLE
Package Manager UI

### ISSUE THREAD

**Issue by dbaldacchino** [DynamoDS/Dynamo#3920] opened 2015-03-08 15:38 UTC
I'm noticing a few things in the Manage Package dialog, some of which might be considered "wishes for improvements" and some might be bugs. I'm running 0.7.5.3566.

a) When in the Package Manager, I see the packages installed but I have no way of telling who the author is. If we're required to go to the website to find out, it would be nice to have a direct link to that package (ex: right-click context menu?).

b) When selecting "Show Contents", the mouse scroll does not work. You have to pick on the tiny scroll bar and move it, which can be a bit of a painful experience.

c) Shouldn't "Show Contents" receive a check mark or change name to "Hide Contents" when this is invoked? It is unintuitive to click on "Show Contents" again to hide the contents.

d) When I opened a .dyn workspace that depended on a few custom .dyf nodes on a machine that did not have them installed, I received no warning. The workspace just seemed to stop working around the custom nodes, at which point then I realized what was happening. After installing the packages and closing and re-opening Dynamo, then things started working again. There needs to be better support for this, such as perhaps automatically prompting the user to download and install the relevant packages. This is even more important when custom nodes are wrapped within other custom nodes and the problem why a custom node isn't working will not be as easily identified by the average user.

My apologies if the above have already been logged! Thanks.

**Comment by dimven** [comment] 2015-03-10 03:58
If I may add a tiny comment on the Package manager UI. The voting system seems to confuse some people. I guess they press the down vote arrow thinking it will expand the package information. The result is that some of the most downloaded and useful packages have negative votes. Not a biggie, because the vote system doesn't seem to be all that useful anyway.

**Comment by Racel** [comment] 2017-10-16 19:24
Closing this as it is a duplicate of other newer issues.

**Closed by Racel** 2017-10-16 19:24 UTC
Labels: Improvement, Package Manager, UI
